<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <Version>1.0.0</Version>
        <PackageId>ingot.Core</PackageId>
        <Title>ingot</Title>
        <Authors>pyroboots</Authors>
        <Copyright>Copyright (c) 2024-2026 pyroboots</Copyright>
        <Description>A C# framework to programmatically create Minecraft Bedrock Edition packs.</Description>
        <PackageTags>minecraft;bedrock;addon;ingot</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/pyroboots/ingot</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/pyroboots/ingot</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="TraitSystem\Traits\Entity\Behaviour\" />
      <Folder Include="TraitSystem\Traits\Item\" />
    </ItemGroup>

</Project>