// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Adds per-instance metadata for this block.
/// </summary>
[Trait("minecraft:block_entity", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IBlockEntity : IItemTrait
{
    /// <summary>
    /// Sets dynamic-properties capabilities on the block-entity.
    /// </summary>
    [TraitProperty]
    public virtual bool DynamicProperties => false;
}
