// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// This defines how a block reacts to a chest being opened underneath it.
/// </summary>
[Trait("minecraft:chest_obstruction", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IChestObstruction : IBlockTrait
{
    /// <summary>Equivalent to <c>always</c></summary>
    public const string ChestObstructionRule_Always = "always";
    /// <summary>Equivalent to <c>never</c></summary>
    public const string ChestObstructionRule_Never = "never";
    /// <summary>Equivalent to <c>shape</c></summary>
    public const string ChestObstructionRule_Shape = "shape";
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "always","never","shape")]
    public virtual string ObstructionRule => "shape";
}
