// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_chest_obstruction?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:chest_obstruction", TraitSystem.TraitType.Block)]
public interface IChestObstruction : IBlockTrait
{
    /// <summary>
    /// [optional] How the block should be evaluated by a chest during chest opening.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? ObstructionRule => null;
}
