// autogenerated by ingot
// log: unable to resolve type  on property Origin
// log: unable to resolve type  on property Size

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Defines the area of the block that collides with entities. If set to true, default values are used. If set to false, the block's collision with entities is disabled. If this component is omitted, default values are used.
/// </summary>
[Trait("minecraft:collision_box", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface ICollisionBox : IItemTrait
{
    /// <summary>
    /// Minimal position of the bounds of the collision box.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Origin => null;
    /// <summary>
    /// Size of each side of the collision box.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Size => null;
}
