// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_connection_rule?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;

using ingot.Core.Common;

/// <summary>
/// Defines whether other blocks such as fences, walls, bars, and glass panes are allowed to connect to this block.
/// </summary>
[Trait("minecraft:connection_rule", TraitSystem.TraitType.Block)]
public interface IConnectionRule : IBlockTrait
{
    /// <summary>
    /// The type of block allowed to connect to this block. Note that the "only_fences" option allows connections from all Vanilla fences excluding NetherBrick.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? AcceptsConnectionsFrom => null;

    /// <summary>
    /// The cardinal directions that connection is enabled for. Note that if "none" is specified for "accepts_connections_from", this field will not be used.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? EnabledDirections => null;
}