// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_connection_rule?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:connection_rule", TraitSystem.TraitType.Block)]
public interface IConnectionRule : IBlockTrait
{
    [TraitProperty]
    /* The type of block allowed to connect to this block. Note that the "only_fences" option allows connections from all Vanilla fences excluding NetherBrick. */
    public virtual dynamic? AcceptsConnectionsFrom => null;

    [TraitProperty]
    /* The cardinal directions that connection is enabled for. Note that if "none" is specified for "accepts_connections_from", this field will not be used. */
    public virtual dynamic? EnabledDirections => null;
}
