// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_crafting_table?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:crafting_table", TraitSystem.TraitType.Block)]
public interface ICraftingTable : IBlockTrait
{
    [TraitProperty]
    /* Defines the tags recipes should define to be crafted on this table. Limited to 64 tags. Each tag is limited to 64 characters. Value must have at most 64 items. */
    public abstract string CraftingTags { get; }

    [TraitProperty]
    /* Specifies the language file key that maps to what text will be displayed in the UI of this table. */
    public abstract string TableName { get; }
}
