// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Describes the destructible by mining properties for this block. If set to true, the block will take the default number of seconds to destroy. If set to false, this block is indestructible by mining. If the component is omitted, the block will take the default number of seconds to mine.
/// </summary>
[Trait("minecraft:destructible_by_mining", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IDestructibleByMining : IItemTrait
{
    /// <summary>
    /// Optional array with item specific mining speeds.
    /// </summary>
    [TraitProperty]
    public virtual string[] ItemSpecificSpeeds => [];
    /// <summary>
    /// Sets the number of seconds it takes to mine the block with base equipment. Greater numbers result in greater mining times. A negative number means the block can't be mined
    /// </summary>
    [TraitProperty]
    public abstract float SecondsToDestroy { get; }
}
