// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_destructible_by_explosion?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:destructible_by_explosion", TraitSystem.TraitType.Block)]
public interface IDestructibleByExplosion : IBlockTrait
{
    /// <summary>
    /// Sets the explosion resistance for the block.
    /// </summary>
    [TraitProperty]
    public virtual float ExplosionResistance => 0f;
}
