// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_destruction_particles?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:destruction_particles", TraitSystem.TraitType.Block)]
public interface IDestructionParticles : IBlockTrait
{
    /// <summary>
    /// Sets number of particles to spawn on block destruction. Value must be &lt;= 255.
    /// </summary>
    [TraitProperty]
    public virtual int ParticleCount => 100;

    /// <summary>
    /// The texture name used for the particle.
    /// </summary>
    [TraitProperty]
    public abstract string Texture { get; }

    /// <summary>
    /// Tint multiplied to the color. Tint method logic varies, but often refers to the "rain" and "temperature" of the biome the block is placed in to compute the tint.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? TintMethod => null;
}
