// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Sets the particles that will be used when block is destroyed. This component can be omitted.
/// </summary>
[Trait("minecraft:destruction_particles", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IDestructionParticles : IBlockTrait
{
    /// <summary>Equivalent to <c>none</c></summary>
    public const string TintMethod_None = "none";
    /// <summary>Equivalent to <c>default_foliage</c></summary>
    public const string TintMethod_DefaultFoliage = "default_foliage";
    /// <summary>Equivalent to <c>birch_foliage</c></summary>
    public const string TintMethod_BirchFoliage = "birch_foliage";
    /// <summary>Equivalent to <c>evergreen_foliage</c></summary>
    public const string TintMethod_EvergreenFoliage = "evergreen_foliage";
    /// <summary>Equivalent to <c>dry_foliage</c></summary>
    public const string TintMethod_DryFoliage = "dry_foliage";
    /// <summary>Equivalent to <c>grass</c></summary>
    public const string TintMethod_Grass = "grass";
    /// <summary>Equivalent to <c>water</c></summary>
    public const string TintMethod_Water = "water";
    /// <summary>
    /// Sets number of particles to spawn on block destruction.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 0,255)]
    public virtual int ParticleCount => 100;
    /// <summary>
    /// The texture name used for the particle.
    /// </summary>
    [TraitProperty]
    public abstract string Texture { get; }
    /// <summary>
    /// Sets the tint method of the particle. Tint method logic varies, but often refers to the "rain" and "temperature" of the biome the block is placed in to compute the tint. Supported tint methods are "none", "default_foliage", "birch_foliage", "evergreen_foliage", "dry_foliage", "grass" and "water"
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "none","default_foliage","birch_foliage","evergreen_foliage","dry_foliage","grass","water")]
    public virtual string TintMethod => "none";
}
