// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Describes the destructible by explosion properties for this block. If set to true, the block will have the default explosion resistance. If set to false, this block is indestructible by explosion. If the component is omitted, the block will have the default explosion resistance.
/// </summary>
[Trait("minecraft:destructible_by_explosion", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IDestructibleByExplosion : IBlockTrait
{
    /// <summary>
    /// Sets the explosion resistance for the block. Greater values result in greater resistance to explosions. The scale will be different for different explosion power levels. A negative value or 0 means it will easily explode; larger numbers increase level of resistance.
    /// </summary>
    [TraitProperty]
    public abstract float ExplosionResistance { get; }
}
