// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_destructible_by_explosion?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;

using ingot.Core.Common;

/// <summary>
/// Describes the destructible by explosion properties for this block. If set to true, the block will have the default explosion resistance. If set to false, this block is indestructible by explosion. If the component is omitted, the block will have the default explosion resistance.
/// </summary>
[Trait("minecraft:destructible_by_explosion", TraitSystem.TraitType.Block)]
public interface IDestructibleByExplosion : IBlockTrait
{
    /// <summary>
    /// Sets the explosion resistance for the block.
    /// </summary>
    [TraitProperty]
    public virtual float ExplosionResistance => 0f;
}