// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_destructible_by_mining?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:destructible_by_mining", TraitSystem.TraitType.Block)]
public interface IDestructibleByMining : IBlockTrait
{
    /// <summary>
    /// Optional array of objects to describe item specific block destroy speeds, each object contains an 'item' ItemDescriptor and a 'destroy_speed' float.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? ItemSpecificSpeeds { get; }

    /// <summary>
    /// Sets the number of seconds it takes to destroy the block with base equipment. Greater numbers result in greater mining times.
    /// </summary>
    [TraitProperty]
    public virtual float SecondsToDestroy => 0f;
}
