// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Specifies the language file key that maps to what text will be displayed when you hover over the block in your inventory and hotbar. If the string given can not be resolved as a loc string, the raw string given will be displayed. If this component is omitted, the name of the block will be used as the display name.
/// </summary>
[Trait("minecraft:display_name", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IDisplayName : IItemTrait
{
    /// <summary>
    /// Specifies the language file key that maps to what text will be displayed when you hover over the block in your inventory and hotbar. If the string given can not be resolved as a loc string, the raw string given will be displayed. If this component is omitted, the name of the block will be used as the display name.
    /// </summary>
    [TraitProperty]
    public abstract string Value { get; }
}
