// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_entity_fall_on?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:entity_fall_on", TraitSystem.TraitType.Block)]
public interface IEntityFallOn : IBlockTrait
{
    /// <summary>
    /// The minimum distance in blocks that an actor needs to fall before events are triggered.
    /// </summary>
    [TraitProperty]
    public virtual float MinFallDistance => 0f;

    /// <summary>
    /// The minimum distance in blocks that an entity needs to fall before events are raised.
    /// </summary>
    [TraitProperty]
    public virtual float MinimumFallDistance => 1f;
}
