// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Configures the behavior of an entity falling on this block. The minimum distance in blocks that an actor needs to fall before events are triggered.
/// </summary>
[Trait("minecraft:entity_fall_on", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IEntityFallOn : IBlockTrait
{
    /// <summary>
    /// The minimum distance in blocks that an actor needs to fall before events are triggered.
    /// </summary>
    [TraitProperty]
    public virtual float MinFallDistance => 0;
}
