// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_flammable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;

using ingot.Core.Common;

/// <summary>
/// Describes the flammable properties for this block. If set to true, default values are used (catch: 5, destroy: 20). Note that the default value of lava_flammable is false for backwards compatibility. If set to false, or if this component is omitted, the block will not be able to catch on fire naturally from neighbors, but it can still be directly ignited.
/// </summary>
[Trait("minecraft:flammable", TraitSystem.TraitType.Block)]
public interface IFlammable : IBlockTrait
{
    /// <summary>
    /// A modifier affecting the chance that this block will catch flame when next to a fire.
    /// </summary>
    [TraitProperty]
    public virtual int CatchChanceModifier => 5;

    /// <summary>
    /// A modifier affecting the chance that this block will be destroyed by flames when on fire.
    /// </summary>
    [TraitProperty]
    public virtual int DestroyChanceModifier => 20;
}