// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_flammable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:flammable", TraitSystem.TraitType.Block)]
public interface IFlammable : IBlockTrait
{
    [TraitProperty]
    /* A modifier affecting the chance that this block will catch flame when next to a fire. */
    public virtual int CatchChanceModifier => 5;

    [TraitProperty]
    /* A modifier affecting the chance that this block will be destroyed by flames when on fire. */
    public virtual int DestroyChanceModifier => 20;
}
