// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_geometry?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:geometry", TraitSystem.TraitType.Block)]
public interface IGeometry : IBlockTrait
{
    [TraitProperty]
    /* An optional list of true/false values that define the visibility of individual bones in the geometry file. */
    public abstract bool BoneVisibility { get; }

    [TraitProperty]
    /* An optional identifer of a culling definition. */
    public abstract string Culling { get; }

    [TraitProperty]
    /* [Experimental] - A string that allows culling rule to group multiple blocks together when comparing them. */
    public virtual string CullingLayer => "minecraft:culling_layer.undefined";

    [TraitProperty]
    /* Currently only available with the VoxelShape experiment on. */
    public virtual string CullingShape => "minecraft:empty";

    [TraitProperty]
    /* Specifies the geometry description identifier to use to render this block. This identifier must match an existing geometry identifier in any of the currently loaded resource packs. */
    public abstract string Identifier { get; }

    [TraitProperty]
    /* A Boolean locking UV orientation of all bones in the geometry, or an array of strings locking UV orientation of specific bones in the geometry. */
    public abstract string UvLock { get; }
}
