// autogenerated by ingot
// log: unable to resolve type  on property Offset

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Allows a block to have a lead tied to it.
/// </summary>
[Trait("minecraft:leashable", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface ILeashable : IBlockTrait
{
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    public virtual dynamic Offset => null;
}
