// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The definitions for how a block behaves when detecting liquid. Only one rule definition is allowed per liquid type - if multiple are specified, the first will be used and the rest will be ignored.
/// </summary>
[Trait("minecraft:liquid_detection", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface ILiquidDetection : IBlockTrait
{
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    public abstract string[] DetectionRules { get; }
}
