// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_map_color?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Sets the color of the block when rendered to a map. If this component is omitted, the block will not show up on the map.
/// </summary>
[Trait("minecraft:map_color", TraitSystem.TraitType.Block)]
public interface IMapColor : IBlockTrait
{
    /// <summary>
    /// The color is represented as a hex value in the format "#RRGGBB". May also be expressed as an array of [R, G, B] from 0 to 255.
    /// </summary>
    [TraitProperty]
    public abstract string Color { get; }

    /// <summary>
    /// Optional, tint multiplied to the color.
    /// </summary>
    [TraitProperty]
    public abstract string TintMethod { get; }
}
