// autogenerated by ingot
// log: unable to resolve type  on property Color

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Sets the color of the block when rendered to a map.Can be a direct color representation or an object with a "color" and "tint_method" field.
/// </summary>
[Trait("minecraft:map_color", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IMapColor : IItemTrait
{
    /// <summary>Equivalent to <c>none</c></summary>
    public const string TintMethod_None = "none";
    /// <summary>Equivalent to <c>default_foliage</c></summary>
    public const string TintMethod_DefaultFoliage = "default_foliage";
    /// <summary>Equivalent to <c>birch_foliage</c></summary>
    public const string TintMethod_BirchFoliage = "birch_foliage";
    /// <summary>Equivalent to <c>evergreen_foliage</c></summary>
    public const string TintMethod_EvergreenFoliage = "evergreen_foliage";
    /// <summary>Equivalent to <c>dry_foliage</c></summary>
    public const string TintMethod_DryFoliage = "dry_foliage";
    /// <summary>Equivalent to <c>grass</c></summary>
    public const string TintMethod_Grass = "grass";
    /// <summary>Equivalent to <c>water</c></summary>
    public const string TintMethod_Water = "water";
    /// <summary>
    /// Sets the color of the block when rendered to a map.
    /// </summary>
    [TraitProperty]
    public abstract dynamic Color { get; }
    /// <summary>
    /// Sets the tint method of the block when rendered to a map. Tint method logic varies, but often refers to the "rain" and "temperature" of the biome the block is placed in to compute the tint. Supported tint methods are "none", "default_foliage", "birch_foliage", "evergreen_foliage", "dry_foliage", "grass" and "water"
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "none","default_foliage","birch_foliage","evergreen_foliage","dry_foliage","grass","water")]
    public virtual string TintMethod => "none";
}
