// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_movable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// This defines how a block reacts to being moved by another block like a piston.
/// </summary>
[Trait("minecraft:movable", TraitSystem.TraitType.Block)]
public interface IMovable : IBlockTrait
{
    /// <summary>
    /// How the block reacts to being pushed by another block like a piston.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? MovementType => null;

    /// <summary>
    /// How the block should handle adjacent blocks around it when being pushed by another block like a piston.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Sticky => null;
}
