// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// This defines how a block reacts to being moved by another block like a piston.
/// </summary>
[Trait("minecraft:movable", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IMovable : IItemTrait
{
    /// <summary>Equivalent to <c>push_pull</c></summary>
    public const string MovementType_PushPull = "push_pull";
    /// <summary>Equivalent to <c>push</c></summary>
    public const string MovementType_Push = "push";
    /// <summary>Equivalent to <c>popped</c></summary>
    public const string MovementType_Popped = "popped";
    /// <summary>Equivalent to <c>immovable</c></summary>
    public const string MovementType_Immovable = "immovable";
    /// <summary>Equivalent to <c>none</c></summary>
    public const string StickyType_None = "none";
    /// <summary>Equivalent to <c>same</c></summary>
    public const string StickyType_Same = "same";
    /// <summary>
    /// How the block reacts to being pushed by another block like a piston. The options are: "push_pull" - The default value for this field. The block will be pushed and pulled by a piston. "push" - The block will only be pulled by a piston and will ignore a sticky piston. "popped" - The block is destroyed when moved by a piston. "immovable" - The block is unaffected by a piston.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "push_pull","push","popped","immovable")]
    public abstract string MovementType { get; }
    /// <summary>
    /// How the block should handle adjacent blocks around it when being pushed by another block like a piston. The options are: "same" - Adjacent blocks to this block will be moved when moved. This excludes other blocks with the "same" property. This will only work with the movement_type: "push_pull". "none" - The default and will not move adjacent blocks.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "none","same")]
    public virtual string Sticky => "none";
}
