// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_movable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:movable", TraitSystem.TraitType.Block)]
public interface IMovable : IBlockTrait
{
    [TraitProperty]
    /* How the block reacts to being pushed by another block like a piston. */
    public virtual dynamic? MovementType => null;

    [TraitProperty]
    /* How the block should handle adjacent blocks around it when being pushed by another block like a piston. */
    public virtual dynamic? Sticky => null;
}
