// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// 
/// </summary>
[Trait("minecraft:placement_filter", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IPlacementFilter : IBlockTrait
{
    /// <summary>
    /// List of conditions where the block can be placed/survive
    /// </summary>
    [TraitProperty]
    public virtual string[] Conditions => [];
}
