// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_placement_filter?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:placement_filter", TraitSystem.TraitType.Block)]
public interface IPlacementFilter : IBlockTrait
{
    [TraitProperty]
    /* List of conditions where the block can be placed/survive Value must have at most 64 items. */
    public virtual string[] Conditions => Array.Empty<string>();
}
