// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_placement_filter?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Sets rules for under what conditions the block can be placed and survive. If the placement conditions are not met, the block cannot be placed. If the block is already placed and the conditions become invalid (e.g., the supporting block is removed), the block will pop off and drop as an item. If the blocks in the filter are liquid blocks, ensure that an item block is created with a 'liquid_clipped' component set to 'true' and a 'block_placer' component with 'replace_block_item' set to 'true'.
/// </summary>
[Trait("minecraft:placement_filter", TraitSystem.TraitType.Block)]
public interface IPlacementFilter : IBlockTrait
{
    /// <summary>
    /// List of conditions where the block can be placed/survive Value must have at most 64 items.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Conditions => null;
}
