// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_precipitation_interactions?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:precipitation_interactions", TraitSystem.TraitType.Block)]
public interface IPrecipitationInteractions : IBlockTrait
{
    /// <summary>
    /// What behavior should the block have. Possible values: obrain, obstruct_rain_accumulate_snow, snowlogging, and none
    /// </summary>
    [TraitProperty]
    public virtual dynamic? PrecipitationBehavior => null;
}
