// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Determines interactions the block will have with different precipitations. Three possible values: obstruct_rain, obstruct_rain_accumulate_snow and none
/// </summary>
[Trait("minecraft:precipitation_interactions", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IPrecipitationInteractions : IItemTrait
{
    /// <summary>Equivalent to <c>none</c></summary>
    public const string PrecipitationBehavior_None = "none";
    /// <summary>Equivalent to <c>obstruct_rain</c></summary>
    public const string PrecipitationBehavior_ObstructRain = "obstruct_rain";
    /// <summary>Equivalent to <c>obstruct_rain_accumulate_snow</c></summary>
    public const string PrecipitationBehavior_ObstructRainAccumulateSnow = "obstruct_rain_accumulate_snow";
    /// <summary>Equivalent to <c>snowlogging</c></summary>
    public const string PrecipitationBehavior_Snowlogging = "snowlogging";
    /// <summary>
    /// What behavior should the block have. Possible values: obstruct_rain, obstruct_rain_accumulate_snow, snowlogging, and none
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "none","obstruct_rain","obstruct_rain_accumulate_snow","snowlogging")]
    public abstract string PrecipitationBehavior { get; }
}
