// autogenerated by ingot
// log: unable to resolve type object on property X
// log: unable to resolve type object on property Y
// log: unable to resolve type object on property Z

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// This component defines a random offset for the block, seeded based on the block's position and the specified range and steps. It affects the block's rendered position, outline, and collision.If the random offset causes the collision box to extend beyond the bounds of a cube, the offset range will automatically adjust to keep the collision box within the cube.Culling for this block is performed without considering the random offset.
/// </summary>
[Trait("minecraft:random_offset", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IRandomOffset : IBlockTrait
{
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    public virtual dynamic X => null;
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    public virtual dynamic Y => null;
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    public virtual dynamic Z => null;
}
