// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_random_offset?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;

using ingot.Core.Common;

/// <summary>
/// This component defines a random offset for the block, seeded based on the block's position and the specified range and steps. It affects the block's rendered position, outline, and collision. If the random offset causes the collision box to extend beyond the bounds of a cube, the offset range will automatically adjust to keep the collision box within the cube. Culling for this block is performed without considering the random offset.
/// </summary>
[Trait("minecraft:random_offset", TraitSystem.TraitType.Block)]
public interface IRandomOffset : IBlockTrait
{
    /// <summary>
    /// X coordinate
    /// </summary>
    [TraitProperty]
    public virtual dynamic? X => null;

    /// <summary>
    /// Y coordinate
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Y => null;

    /// <summary>
    /// Z coordinate
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Z => null;
}