// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_random_offset?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:random_offset", TraitSystem.TraitType.Block)]
public interface IRandomOffset : IBlockTrait
{
    /// <summary>
    /// X coordinate
    /// </summary>
    [TraitProperty]
    public virtual dynamic? X => null;

    /// <summary>
    /// Y coordinate
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Y => null;

    /// <summary>
    /// Z coordinate
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Z => null;
}
