// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_redstone_conductivity?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:redstone_conductivity", TraitSystem.TraitType.Block)]
public interface IRedstoneConductivity : IBlockTrait
{
    [TraitProperty]
    /* Specifies if redstone wire can stair-step downward on the block. */
    public virtual bool AllowsWireToStepDown => true;

    [TraitProperty]
    /* Specifies if the block can be powered by redstone. */
    public virtual bool RedstoneConductor => false;
}
