// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_redstone_consumer?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// A component describing how a block can consume and potentially propagate a redstone signal. This component is not available for block permutations.
/// </summary>
[Trait("minecraft:redstone_consumer", TraitSystem.TraitType.Block)]
public interface IRedstoneConsumer : IBlockTrait
{
    /// <summary>
    /// Optional minimum value for incoming signal strength.
    /// </summary>
    [TraitProperty]
    public virtual int MinPower => 0;

    /// <summary>
    /// Optional Boolean to control whether a signal can pass through this block or not, defaults to false.
    /// </summary>
    [TraitProperty]
    public virtual bool PropagatesPower => false;
}
