// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The definitions for how a block can produce a redstone signal.
/// </summary>
[Trait("minecraft:redstone_producer", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IRedstoneProducer : IBlockTrait
{
    /// <summary>Equivalent to <c>down</c></summary>
    public const string Facing_Down = "down";
    /// <summary>Equivalent to <c>up</c></summary>
    public const string Facing_Up = "up";
    /// <summary>Equivalent to <c>north</c></summary>
    public const string Facing_North = "north";
    /// <summary>Equivalent to <c>south</c></summary>
    public const string Facing_South = "south";
    /// <summary>Equivalent to <c>west</c></summary>
    public const string Facing_West = "west";
    /// <summary>Equivalent to <c>east</c></summary>
    public const string Facing_East = "east";
    /// <summary>
    /// The list of faces that are considered connected to the circuit. If a face is not connected, it will not provide power to the block touching that face.By default, all faces are connected.
    /// </summary>
    [TraitProperty]
    public virtual string[] ConnectedFaces => [];
    /// <summary>
    /// The strength of the redstone signal produced by this block. 0 means no signal and higher numbers mean stronger signal.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 0,15)]
    public abstract int Power { get; }
    /// <summary>
    /// The block touching this face will become strongly powered with the signal level strength of "power".Strongly powered blocks will power adjacent blocks.By default, the block will not strongly power any face.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "down","up","north","south","west","east")]
    public abstract string StronglyPoweredFace { get; }
    /// <summary>
    /// If true, the "strongly_powered_face" and "connected_faces" properties will be rotated according to the "minecraft:transformation" component.
    /// </summary>
    [TraitProperty]
    public virtual bool TransformRelative => true;
}
