// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// A block with this component can be replaced when another block is placed in the same block position.
/// </summary>
[Trait("minecraft:replaceable", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface IReplaceable : IBlockTrait
{
}
