// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockcomponents/minecraftblock_tick?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Block;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Causes the block to tick based on a regular interval equal to a number of ticks randomly chosen from the internal_range parameter. This ticking will send the onTick event to blocks with custom components subscribed for the event. Custom components listening to the onTick event that are added to a block that does not have the minecraft:tick component will cause a content error.
/// </summary>
[Trait("minecraft:tick", TraitSystem.TraitType.Block)]
public interface ITick : IBlockTrait
{
    /// <summary>
    /// A range of values, specified in ticks, to decide the next tick interval for a block.
    /// </summary>
    [TraitProperty]
    public virtual int[] IntervalRange => [0, 0];

    /// <summary>
    /// If false, the block will only be ticked once after a delay equal to a number of ticks randomly chosen from the interval_range and no further ticking will occur.
    /// </summary>
    [TraitProperty]
    public virtual bool Looping => true;
}
