// autogenerated by ingot
// log: unable to resolve type  on property Rotation
// log: unable to resolve type  on property RotationPivot
// log: unable to resolve type  on property Scale
// log: unable to resolve type  on property ScalePivot
// log: unable to resolve type  on property Translation

namespace ingot.Core.TraitSystem.Traits.Block;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// 
/// </summary>
[Trait("minecraft:transformation", TraitSystem.TraitType.Block)]
[TraitFormatVersion("1.26.20")]
public interface ITransformation : IItemTrait
{
    /// <summary>
    /// The block's rotation in increments of 90 degrees
    /// </summary>
    [TraitProperty]
    public virtual dynamic Rotation => null;
    /// <summary>
    /// The block's rotation pivot
    /// </summary>
    [TraitProperty]
    public virtual dynamic RotationPivot => null;
    /// <summary>
    /// The block's scale
    /// </summary>
    [TraitProperty]
    public virtual dynamic Scale => null;
    /// <summary>
    /// The block's scale pivot
    /// </summary>
    [TraitProperty]
    public virtual dynamic ScalePivot => null;
    /// <summary>
    /// The block's translation
    /// </summary>
    [TraitProperty]
    public virtual dynamic Translation => null;
}
