using ingot.Core.Common;
using ingot.Core.TraitSystem;

using Version = System.Version;

namespace ingot.Generators;

public class TraitInterfaceBuilder
{
    private readonly string[] _usings;
    public string Description;
    public string Name;
    public Identifier Component;
    public TraitSystem.TraitType Type;
    public Version FormatVersion;
    public string Namespace;
    public string[] ExtraHeaders = [];
    
    /// <param name="id">Schema ID</param>
    /// <param name="description">Description of the component</param>
    /// <param name="name">Name of interface without the "I" prefix</param>
    /// <param name="componentId">Identifier of the component this interface is for</param>
    /// <param name="type">Type of trait interface</param>
    /// <param name="formatVer">Minimum format version for this trait</param>
    /// <param name="ns">Namespace</param>
    /// <param name="usings">Array of usings to insert</param>
    public TraitInterfaceBuilder(string description, string name, Identifier componentId, TraitSystem.TraitType type,
        Version formatVer, string ns, string[]? usings = null)
    {
        _usings = usings ?? [];
        Description = description;
        Name = name;
        Component = componentId;
        Type = type;
        FormatVersion = formatVer;
        Namespace = ns;
    }

    private readonly List<InterfaceProperty> _properties = new();
    private readonly Dictionary<string, string[]> _enums = new();
    
    private record InterfaceProperty(string Description, string Name, bool Required, string Type, object? DefaultValue, 
        TraitPropertyConstraintAttribute[] Constraints, TraitPropertyWarningAttribute[] Warnings);
    public void AddProperty(string desc, string name, bool required, string type, object? defaultValue = null,
        TraitPropertyConstraintAttribute[]? constraints = null, TraitPropertyWarningAttribute[]? warnings = null) 
        => _properties.Add(new(desc, name, required, type, defaultValue, constraints ?? [], warnings ?? []));

    public void Enum(string name, params string[] values) => _enums.Add(name, values);
    
    // in case things ever get renamed, generator stays up to date
    private static string TraitAttribute => nameof(Core.TraitSystem.TraitAttribute);
    private static string FmtVerAttribute => nameof(TraitFormatVersionAttribute);
    private static string ItemTraitInterface => nameof(Core.TraitSystem.Traits.IItemTrait);
    private static string TraitPropertyAttribute => nameof(Core.TraitSystem.TraitPropertyAttribute);
    private static string TraitPropertyConstraintAttribute => nameof(Core.TraitSystem.TraitPropertyConstraintAttribute);
    private static string TraitPropertyWarningAttribute => nameof(Core.TraitSystem.TraitPropertyConstraintAttribute);
    
    public string Generate()
    {
        StringWriter sw = new();
        
        sw.WriteLine($"// autogenerated by ingot");
        foreach (string header in ExtraHeaders)
            sw.WriteLine($"// {header}");
        sw.WriteLine();
        sw.WriteLine(Namespace);
        foreach (string import in _usings)
            sw.WriteLine($"using {import};");
        sw.WriteLine();
        sw.WriteLine("/// <summary>");
        sw.WriteLine($"/// {Description}");
        sw.WriteLine("/// </summary>");
        sw.WriteLine($"[{TraitAttribute}(\"{Component}\", TraitSystem.TraitType.{System.Enum.GetName(Type)})]");
        sw.WriteLine($"[{FmtVerAttribute}(\"{FormatVersion}\")]");
        sw.WriteLine($"public interface I{Name} : {ItemTraitInterface}");
        sw.WriteLine("{");

        foreach (var enumeration in _enums) foreach (string enumerations in enumeration.Value)
            sw.WriteLine($"    public const string {enumeration.Key}_{Formatting.SnakeToPascalCase(enumerations)} = \"{enumerations}\";");
        
        foreach (InterfaceProperty prop in _properties)
        {
            sw.WriteLine("    /// <summary>");
            sw.WriteLine($"    /// {prop.Description}");
            sw.WriteLine("    /// </summary>");

            string sanitisedDefaultValue;
            if (prop.DefaultValue is null) sanitisedDefaultValue = "null";
            else sanitisedDefaultValue = prop.DefaultValue is string ? $"\"{prop.DefaultValue.ToString().Replace("\"", "\\\"")}\"" : prop.DefaultValue.ToString();
            
            sw.WriteLine($"    [{TraitPropertyAttribute}]");
            foreach (TraitPropertyConstraintAttribute constraint in prop.Constraints)
            {
                string values = string.Join(',',
                    constraint.Values.Select((v) => v is string ? $"\"{v}\"" : v.ToString()));
                
                // [TraitPropertyConstraint(TraitPropertyConstraint.Constraint.OneOf, "use", "attack")]
                sw.WriteLine($"    [{TraitPropertyConstraintAttribute}(TraitPropertyConstraint.Constraint.{System.Enum.GetName(constraint.Operation)}, {values})]");
            }
            foreach (TraitPropertyWarningAttribute warning in prop.Warnings)
            {
                string values = string.Join(',',
                    warning.Values.Select((v) => v is string ? $"\"{v}\"" : v.ToString()));
                
                // [TraitPropertyWarning("warning", TraitPropertyConstraint.Constraint.Equal, 1)]
                sw.WriteLine($"    [{TraitPropertyWarningAttribute}(\"{warning.Warning}\", TraitPropertyConstraint.Constraint.{System.Enum.GetName(warning.Operation)}, {values})]");
            }
            
            // public abstract float Duration { get; }
            if (prop.Required) sw.WriteLine($"    public abstract {prop.Type} {prop.Name} {{ get; }}");
            // public virtual dynamic? Type => null;
            else sw.WriteLine($"    public virtual {prop.Type} {prop.Name} => {sanitisedDefaultValue};");
            
        }
        
        sw.WriteLine("}");
        
        string s = sw.ToString();
        sw.Dispose();
        return s;
    }
}