// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_dig?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to dig into the ground before despawning.
/// </summary>
[Trait("minecraft:behavior.dig", TraitSystem.TraitType.Entity)]
public interface IBehaviorDig : IEntityTrait
{
    /// <summary>
    /// If true, this behavior can run when this entity is named. Otherwise not.
    /// </summary>
    [TraitProperty]
    public virtual bool AllowDigWhenNamed => false;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Indicates that the actor should start digging when it sees daylight
    /// </summary>
    [TraitProperty]
    public virtual bool DigsInDaylight => false;

    /// <summary>
    /// Goal duration in seconds
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 0f;

    /// <summary>
    /// The minimum idle time in seconds between the last detected disturbance to the start of digging.
    /// </summary>
    [TraitProperty]
    public virtual float IdleTime => 0f;

    /// <summary>
    /// Event(s) to run when the goal starts.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnStart => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// If true, finding new suspicious locations count as disturbances that may delay the start of this goal.
    /// </summary>
    [TraitProperty]
    public virtual bool SuspicionIsDisturbance => false;

    /// <summary>
    /// If true, vibrations count as disturbances that may delay the start of this goal.
    /// </summary>
    [TraitProperty]
    public virtual bool VibrationIsDisturbance => false;
}
