// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_to_water?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to move back into water when on land.
/// </summary>
[Trait("minecraft:behavior.move_to_water", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveToWater : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 0.5f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The number of randomly selected blocks each tick that the mob will check within its search range and height for a valid block to move to.
    /// </summary>
    [TraitProperty]
    public virtual int SearchCount => 10;

    /// <summary>
    /// Height in blocks the mob will look for water to move towards Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 1;

    /// <summary>
    /// The distance in blocks it will look for water to move towards Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
