// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_pet_sleep_with_owner?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the pet mob to move onto a bed with its owner while sleeping.
/// </summary>
[Trait("minecraft:behavior.pet_sleep_with_owner", TraitSystem.TraitType.Entity)]
public interface IBehaviorPetSleepWithOwner : IEntityTrait
{
    /// <summary>
    /// Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 0.5f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public abstract int Priority { get; }

    /// <summary>
    /// Height in blocks from the owner the pet can be to sleep with owner.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 1;

    /// <summary>
    /// The distance in blocks from the owner the pet can be to sleep with owner.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
