// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_around_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to move around a target.If the entity is too close(i.e.closer than destination range min and height difference limit) it will try to move away from its target.If the entity is too far away from its target it will try to move closer to a random position within the destination range.A randomized amount of those positions will be behind the target, and the spread can be tweaked with 'destination_pos_spread_degrees'.
/// </summary>
[Trait("minecraft:behavior.move_around_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveAroundTarget : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// This angle (in degrees) is used for controlling the spread when picking a destination position behind the target.
    /// </summary>
    [TraitProperty]
    public virtual float DestinationPosSpreadDegrees => 90f;

    /// <summary>
    /// The range of distances from the target entity within which the goal should look for a position to move the owner entity to.
    /// </summary>
    [TraitProperty]
    public virtual dynamic DestinationPositionRange => null;

    /// <summary>
    /// Conditions that need to be met for the behavior to start.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Filters => null;

    /// <summary>
    /// Distance in height (in blocks) between the owner entity and the target has to be less than this value when owner checks if it is too close and should move away from the target.
    /// </summary>
    [TraitProperty]
    public virtual float HeightDifferenceLimit => 10f;

    /// <summary>
    /// Horizontal search distance (in blocks) when searching for a position to move away from target.
    /// </summary>
    [TraitProperty]
    public virtual int HorizontalSearchDistance => 5;

    /// <summary>
    /// The speed with which the entity should move to its target position.
    /// </summary>
    [TraitProperty]
    public virtual float MovementSpeed => 0.6000000238418579f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Vertical search distance (in blocks) when searching for a position to move away from target.
    /// </summary>
    [TraitProperty]
    public virtual int VerticalSearchDistance => 5;
}
