// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_guardian_attack?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to use a laser beam attack. Can only be used by Guardians and Elder Guardians.
/// </summary>
[Trait("minecraft:behavior.guardian_attack", TraitSystem.TraitType.Entity)]
public interface IBehaviorGuardianAttack : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Amount of additional damage dealt from an elder guardian's magic attack. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int ElderExtraMagicDamage => 2;

    /// <summary>
    /// In hard difficulty, amount of additional damage dealt from a guardian's magic attack. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int HardModeExtraMagicDamage => 2;

    /// <summary>
    /// Amount of damage dealt from a guardian's magic attack. Magic attack damage is added to the guardian's base attack damage. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int MagicDamage => 1;

    /// <summary>
    /// Guardian attack behavior stops if the target is closer than this distance (doesn't apply to elders).
    /// </summary>
    [TraitProperty]
    public virtual float MinDistance => 3f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Time (in seconds) to wait after starting an attack before playing the guardian attack sound. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float SoundDelayTime => 0.5f;

    /// <summary>
    /// Maximum rotation (in degrees), on the X-axis, this entity can rotate while trying to look at the target. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float XMaxRotation => 90f;

    /// <summary>
    /// Maximum rotation (in degrees), on the Y-axis, this entity can rotate its head while trying to look at the target. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float YMaxHeadRotation => 90f;
}
