// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_look_at_trading_player?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Compels an entity to look at the player that is currently trading with the entity.
/// </summary>
[Trait("minecraft:behavior.look_at_trading_player", TraitSystem.TraitType.Entity)]
public interface IBehaviorLookAtTradingPlayer : IEntityTrait
{
    /// <summary>
    /// The angle in degrees that the mob can see rotated on the Y-axis (left-right). Value must be &lt;= 360.
    /// </summary>
    [TraitProperty]
    public virtual int AngleOfViewHorizontal => 360;

    /// <summary>
    /// The angle in degrees that the mob can see rotated on the X-axis (up-down). Value must be &lt;= 360.
    /// </summary>
    [TraitProperty]
    public virtual int AngleOfViewVertical => 360;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The distance in blocks from which the entity will look at the nearest entity.
    /// </summary>
    [TraitProperty]
    public virtual float LookDistance => 8f;

    /// <summary>
    /// Time range to look at the nearest entity.
    /// </summary>
    [TraitProperty]
    public virtual dynamic LookTime => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The probability of looking at the target. A value of 1.00 is 100%. Value must be &lt;= 1.
    /// </summary>
    [TraitProperty]
    public virtual float Probability => 0.019999999552965164f;
}
