// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_follow_target_captain?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows mob to move towards its current target captain.
/// </summary>
[Trait("minecraft:behavior.follow_target_captain", TraitSystem.TraitType.Entity)]
public interface IBehaviorFollowTargetCaptain : IEntityTrait
{
    /// <summary>
    /// Defines the distance in blocks the mob will stay from its target while following.
    /// </summary>
    [TraitProperty]
    public virtual float FollowDistance => 0f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public abstract int Priority { get; }

    /// <summary>
    /// Defines the maximum distance in blocks a mob can get from its target captain before giving up trying to follow it.
    /// </summary>
    [TraitProperty]
    public virtual float WithinRadius => 0f;
}
