// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_melee_attack?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to deal damage through a melee attack.
/// </summary>
[Trait("minecraft:behavior.melee_attack", TraitSystem.TraitType.Entity)]
public interface IBehaviorMeleeAttack : IEntityTrait
{
    /// <summary>
    /// Allows the mob to perform this melee attack behavior only once during its lifetime.
    /// </summary>
    [TraitProperty]
    public virtual bool AttackOnce => false;

    /// <summary>
    /// Defines the entity types this entity will attack.
    /// </summary>
    [TraitProperty]
    public abstract string AttackTypes { get; }

    /// <summary>
    /// Allows the mob, if on fire and empty handed, to ignite its target upon a successful attack.
    /// </summary>
    [TraitProperty]
    public virtual bool CanSpreadOnFire => false;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Cooldown time, in seconds, between consecutive attacks.
    /// </summary>
    [TraitProperty]
    public virtual float CooldownTime => 1f;

    /// <summary>
    /// Time, in seconds, added to the attack path recalculation interval when the target is beyond "path_inner_boundary".
    /// </summary>
    [TraitProperty]
    public virtual float InnerBoundaryTimeIncrease => 0.25f;

    /// <summary>
    /// Maximum base time, in seconds, before recalculating a new attack path to the target (before increases are applied).
    /// </summary>
    [TraitProperty]
    public virtual float MaxPathTime => 0.550000011920929f;

    /// <summary>
    /// Field of view, in degrees, used by the hard-coded sensing component to detect a valid attack target.
    /// </summary>
    [TraitProperty]
    public virtual float MeleeFov => 90f;

    /// <summary>
    /// Minimum base time, in seconds, before recalculating a new attack path to the target (before increases are applied).
    /// </summary>
    [TraitProperty]
    public virtual float MinPathTime => 0.20000000298023224f;

    /// <summary>
    /// Defines the event to trigger when this entity successfully attacks.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnAttack => null;

    /// <summary>
    /// Defines the event to trigger when this entity kills the target.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnKill => null;

    /// <summary>
    /// Time, in seconds, added to the attack path recalculation interval when the target is beyond "path_outer_boundary".
    /// </summary>
    [TraitProperty]
    public virtual float OuterBoundaryTimeIncrease => 0.5f;

    /// <summary>
    /// Time, in seconds, added to the attack path recalculation interval when the mob cannot move along the current path.
    /// </summary>
    [TraitProperty]
    public virtual float PathFailTimeIncrease => 0.75f;

    /// <summary>
    /// Distance at which to increase attack path recalculation by "inner_boundary_time_increase".
    /// </summary>
    [TraitProperty]
    public virtual float PathInnerBoundary => 16f;

    /// <summary>
    /// Distance at which to increase attack path recalculation by "outer_boundary_time_increase".
    /// </summary>
    [TraitProperty]
    public virtual float PathOuterBoundary => 32f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Defines a 1-in-N chance for the mob to stop its current attack, where N equals "random_stop_interval".
    /// </summary>
    [TraitProperty]
    public virtual int RandomStopInterval => 0;

    /// <summary>
    /// Used with the base size of the entity to determine minimum target-distance before trying to deal attack damage.
    /// </summary>
    [TraitProperty]
    public virtual float ReachMultiplier => 2f;

    /// <summary>
    /// Specifies whether a full navigation path from the mob to the target is required.
    /// </summary>
    [TraitProperty]
    public virtual bool RequireCompletePath => false;

    /// <summary>
    /// Multiplier applied to the mob's movement speed when moving toward its target.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Allows the mob to track its target even if it lacks a hard-coded sensing component.
    /// </summary>
    [TraitProperty]
    public virtual bool TrackTarget => false;

    /// <summary>
    /// Maximum rotation, in degrees, on the X-axis while the mob is trying to look at its target.
    /// </summary>
    [TraitProperty]
    public virtual float XMaxRotation => 30f;

    /// <summary>
    /// Maximum rotation, in degrees, on the Y-axis while the mob is trying to look at its target.
    /// </summary>
    [TraitProperty]
    public virtual float YMaxHeadRotation => 30f;
}
