// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_to_random_block?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows mob to move towards a random block.
/// </summary>
[Trait("minecraft:behavior.move_to_random_block", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveToRandomBlock : IEntityTrait
{
    /// <summary>
    /// Defines the distance from the mob, in blocks, that the block to move to will be chosen.
    /// </summary>
    [TraitProperty]
    public virtual float BlockDistance => 16f;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Defines the distance in blocks the mob has to be from the block for the movement to be finished.
    /// </summary>
    [TraitProperty]
    public virtual float WithinRadius => 0f;
}
