// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_find_mount?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to look around for another mob to ride atop it.
/// </summary>
[Trait("minecraft:behavior.find_mount", TraitSystem.TraitType.Entity)]
public interface IBehaviorFindMount : IEntityTrait
{
    /// <summary>
    /// If true, the mob will not go into water blocks when going towards a mount
    /// </summary>
    [TraitProperty]
    public virtual bool AvoidWater => false;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Number of attempts to find mount
    /// </summary>
    [TraitProperty]
    public virtual int MaxFailedAttempts => 20;

    /// <summary>
    /// This is the distance the mob needs to be, in blocks, from the desired mount to mount it. If the value is below 0, the mob will use its default attack distance
    /// </summary>
    [TraitProperty]
    public virtual float MountDistance => -1f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Time the mob will wait before starting to move towards the mount
    /// </summary>
    [TraitProperty]
    public virtual int StartDelay => 0;

    /// <summary>
    /// If true, the mob will only look for a mount if it has a target
    /// </summary>
    [TraitProperty]
    public virtual bool TargetNeeded => false;

    /// <summary>
    /// Distance in blocks within which the mob will look for a mount
    /// </summary>
    [TraitProperty]
    public virtual float WithinRadius => 0f;
}
