// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_eat_block?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to consume a block, replace the eaten block with another block, and trigger an event as a result.
/// </summary>
[Trait("minecraft:behavior.eat_block", TraitSystem.TraitType.Entity)]
public interface IBehaviorEatBlock : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// A collection of pairs of blocks; the first ("eat_block") is the block the entity should eat, the second ("replace_block") is the block that should replace the eaten block.
    /// </summary>
    [TraitProperty]
    public virtual dynamic EatAndReplaceBlockPairs => null;

    /// <summary>
    /// The event to trigger when the block eating animation has completed.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnEat => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// A molang expression defining the success chance the entity has to consume a block.
    /// </summary>
    [TraitProperty]
    public virtual string SuccessChance => "0.019999999552965164";

    /// <summary>
    /// The amount of time (in seconds) it takes for the block to be eaten upon a successful eat attempt.
    /// </summary>
    [TraitProperty]
    public virtual float TimeUntilEat => 1.7999999523162842f;
}
