// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_follow_owner?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows a mob to follow the player that owns it.
/// </summary>
[Trait("minecraft:behavior.follow_owner", TraitSystem.TraitType.Entity)]
public interface IBehaviorFollowOwner : IEntityTrait
{
    /// <summary>
    /// Defines if the mob will teleport to its owner when too far away.
    /// </summary>
    [TraitProperty]
    public virtual bool CanTeleport => true;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Defines if the mob should disregard following its owner after detecting a recent vibration.
    /// </summary>
    [TraitProperty]
    public virtual bool IgnoreVibration => false;

    /// <summary>
    /// The maximum distance the mob can be from its owner to start following it. Applicable only when "can_teleport" is set to false.
    /// </summary>
    [TraitProperty]
    public virtual float MaxDistance => 60f;

    /// <summary>
    /// Defines how far (in blocks) the entity will be from its owner after teleporting. If not specified, it defaults to "stop_distance" + 1, allowing the entity to seamlessly resume navigation.
    /// </summary>
    [TraitProperty]
    public virtual int PostTeleportDistance => 3;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// The minimum distance the mob must be from its owner to start following it.
    /// </summary>
    [TraitProperty]
    public virtual float StartDistance => 10f;

    /// <summary>
    /// The distance at which the mob will stop following its owner.
    /// </summary>
    [TraitProperty]
    public virtual float StopDistance => 2f;
}
