// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_investigate_suspicious_location?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to move towards a "suspicious" position based on data gathered in minecraft:suspect_tracking.
/// </summary>
[Trait("minecraft:behavior.investigate_suspicious_location", TraitSystem.TraitType.Entity)]
public interface IBehaviorInvestigateSuspiciousLocation : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Distance in blocks within the entity considers it has reached it's target position.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 1.5f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
