// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_jump_around_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to jump around a target.
/// </summary>
[Trait("minecraft:behavior.jump_around_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorJumpAroundTarget : IEntityTrait
{
    /// <summary>
    /// Enables collision checks when calculating the jump. Setting check_collision to true may affect performance and should be used with care.
    /// </summary>
    [TraitProperty]
    public virtual bool CheckCollision => false;

    /// <summary>
    /// Scaling temporarily applied to the entity's AABB bounds when jumping. A smaller bounding box reduces the risk of collisions during the jump. When check_collision is true it also increases the chance of being able to jump when close to obstacles.
    /// </summary>
    [TraitProperty]
    public virtual float EntityBoundingBoxScale => 0.7f;

    /// <summary>
    /// Conditions that need to be met for the behavior to start.
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? Filters => null;

    /// <summary>
    /// The jump angles in float degrees that are allowed when performing the jump. The order in which the angles are chosen is randomized.
    /// </summary>
    [TraitProperty]
    public virtual string[] JumpAngles => new[] { "[ 40.0", "55.0", "60.0", "75.0", "80.0 ]" };

    /// <summary>
    /// The time in seconds to spend in cooldown before this goal can be used again.
    /// </summary>
    [TraitProperty]
    public virtual float JumpCooldownDuration => 0.5f;

    /// <summary>
    /// The time in seconds to spend in cooldown after being hurt before this goal can be used again.
    /// </summary>
    [TraitProperty]
    public virtual float JumpCooldownWhenHurtDuration => 0.1f;

    /// <summary>
    /// The range deciding how close to and how far away from the target the landing position can be when jumping.
    /// </summary>
    [TraitProperty]
    public abstract int LandingDistanceFromTarget { get; }

    /// <summary>
    /// This angle (in degrees) is used for controlling the spread when picking a landing position behind the target. A zero spread angle means the landing position will be straight behind the target with no variance. A 90 degree spread angle means the landing position can be up to 45 degrees to the left and to the right of the position straight behind the target's view direction.
    /// </summary>
    [TraitProperty]
    public virtual int LandingPositionSpreadDegrees => 90;

    /// <summary>
    /// If the entity was hurt within these last seconds, the jump_cooldown_when_hurt_duration will be used instead of jump_cooldown_duration.
    /// </summary>
    [TraitProperty]
    public virtual float LastHurtDuration => 2f;

    /// <summary>
    /// If the entity's line of sight towards its target is obstructed by an obstacle with a height below this number, the obstacle will be ignored, and the goal will try to find a valid landing position.
    /// </summary>
    [TraitProperty]
    public virtual int LineOfSightObstructionHeightIgnore => 4;

    /// <summary>
    /// Maximum velocity a jump can be performed at.
    /// </summary>
    [TraitProperty]
    public virtual float MaxJumpVelocity => 1.4f;

    /// <summary>
    /// The time in seconds to spend preparing for the jump.
    /// </summary>
    [TraitProperty]
    public virtual float PrepareJumpDuration => 0.5f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public abstract int Priority { get; }

    /// <summary>
    /// The number of blocks above the entity's head that has to be air for this goal to be usable.
    /// </summary>
    [TraitProperty]
    public virtual int RequiredVerticalSpace => 4;

    /// <summary>
    /// The number of blocks above and below from the jump target position that will be checked to find a surface to land on.
    /// </summary>
    [TraitProperty]
    public virtual int SnapToSurfaceBlockRange => 10;

    /// <summary>
    /// Target needs to be within this range for the jump to happen.
    /// </summary>
    [TraitProperty]
    public abstract int ValidDistanceToTarget { get; }
}
