// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_fertilize_farm_block?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to search within an area for a growable crop block. If found, the mob will use any available fertilizer in their inventory on the crop. This goal will not execute if the mob does not have a fertilizer item in its inventory.
/// </summary>
[Trait("minecraft:behavior.fertilize_farm_block", TraitSystem.TraitType.Entity)]
public interface IBehaviorFertilizeFarmBlock : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Distance in blocks within the mob considers it has reached it's target position. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 1.5f;

    /// <summary>
    /// The maximum number of times the mob will use fertilzer on the target block. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int MaxFertilizerUsage => 1;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The maximum amount of time in seconds that the goal can take before searching again. The time is chosen between 0 and this number. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float SearchCooldownMaxSeconds => 8f;

    /// <summary>
    /// The number of randomly selected blocks each tick that the mob will check within its search range and height for a valid block to move to.
    /// </summary>
    [TraitProperty]
    public virtual int SearchCount => 9;

    /// <summary>
    /// The height in blocks the mob will search within to find a valid target position. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 1;

    /// <summary>
    /// The distance in blocks the mob will search within to find a valid target position. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 1;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 0.5f;
}
