// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_hover?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to hover in place.
/// </summary>
[Trait("minecraft:behavior.hover", TraitSystem.TraitType.Entity)]
public interface IBehaviorHover : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    [TraitProperty]
    public virtual int Priority => 0;
}
