// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_drop_item_for?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to move toward a target, and drop an item near the target.
/// </summary>
[Trait("minecraft:behavior.drop_item_for", TraitSystem.TraitType.Entity)]
public interface IBehaviorDropItemFor : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Total time that the goal is on cooldown before it can be used again.
    /// </summary>
    [TraitProperty]
    public virtual float Cooldown => 0.25f;

    /// <summary>
    /// The percent chance the entity will drop an item when using this goal. Value must be &lt;= 1.
    /// </summary>
    [TraitProperty]
    public virtual float DropItemChance => 1f;

    /// <summary>
    /// The list of conditions another entity must meet to be a valid target to drop an item for.
    /// </summary>
    [TraitProperty]
    public virtual dynamic EntityTypes => null;

    /// <summary>
    /// Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 0.5f;

    /// <summary>
    /// The loot table that contains the possible loot the entity can drop with this goal.
    /// </summary>
    [TraitProperty]
    public virtual string? LootTable => null;

    /// <summary>
    /// The maximum height the entities head will look at when dropping the item. The entity will always be looking at its target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxHeadLookAtHeight => 10f;

    /// <summary>
    /// If the target position is farther away than this distance on any tick, the entity will teleport to the target position.
    /// </summary>
    [TraitProperty]
    public virtual float MinimumTeleportDistance => 2f;

    /// <summary>
    /// The preferred distance the entity tries to be from the target it is dropping an item for.
    /// </summary>
    [TraitProperty]
    public virtual float OfferingDistance => 1f;

    /// <summary>
    /// The event to trigger when the entity attempts to drop an item.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnDropAttempt => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The number of randomly selected blocks each tick that the mob will check within its search range and height for a valid block to move to.
    /// </summary>
    [TraitProperty]
    public virtual int SearchCount => 0;

    /// <summary>
    /// The height in blocks the entity will search within to find a valid target position. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 1;

    /// <summary>
    /// The distance in blocks the entity will search within to find a valid target position. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// The numbers of seconds that will pass before the dropped entity can be picked up from the ground.
    /// </summary>
    [TraitProperty]
    public virtual float SecondsBeforePickup => 0f;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// The range in blocks within which the entity searches to find a target to drop an item for.
    /// </summary>
    [TraitProperty]
    public virtual int[] TargetRange => [1, 1, 1];

    /// <summary>
    /// When the entity teleports, offset the teleport position by this many blocks in the X, Y, and Z coordinate.
    /// </summary>
    [TraitProperty]
    public virtual int[] TeleportOffset => [0, 1, 0];

    /// <summary>
    /// The valid times of day that this goal can be used. For reference: noon is 0.0, sunset is 0.25, midnight is 0.5, and sunrise is 0.75, and back to noon for 1.0.
    /// </summary>
    [TraitProperty]
    public virtual dynamic TimeOfDayRange => null;
}
