// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_to_village?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to move into a random location within a village.
/// </summary>
[Trait("minecraft:behavior.move_to_village", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveToVillage : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Time in seconds the mob has to wait before using the goal again
    /// </summary>
    [TraitProperty]
    public virtual float CooldownTime => 8f;

    /// <summary>
    /// Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 1.5f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The distance in blocks to search for villages. If &lt;= 0, find the closest village regardless of distance.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
