// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_follow_mob?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to follow other mobs.
/// </summary>
[Trait("minecraft:behavior.follow_mob", TraitSystem.TraitType.Entity)]
public interface IBehaviorFollowMob : IEntityTrait
{
    /// <summary>
    /// If non-empty, provides criteria for filtering which nearby Mobs can be followed.
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? Filters => null;

    /// <summary>
    /// The type of actor to prefer following. If left unspecified, a random actor among those in range will be chosen.
    /// </summary>
    [TraitProperty]
    public virtual string? PreferredActorType => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public abstract int Priority { get; }

    /// <summary>
    /// The distance in blocks it will look for a mob to follow
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// The distance in blocks this mob stops from the mob it is following
    /// </summary>
    [TraitProperty]
    public virtual float StopDistance => 2f;

    /// <summary>
    /// If true, the mob will respect the 'minecraft:home' component's 'restriction_radius' field when choosing a target to follow.
    /// </summary>
    [TraitProperty]
    public virtual bool UseHomePositionRestriction => true;
}
