// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_barter?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Enables the mob to barter for items that have been configured as barter currency. Must be used in combination with the barter component.
/// </summary>
[Trait("minecraft:behavior.barter", TraitSystem.TraitType.Entity)]
public interface IBehaviorBarter : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
