// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_random_stroll?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows a mob to randomly stroll around.
/// </summary>
[Trait("minecraft:behavior.random_stroll", TraitSystem.TraitType.Entity)]
public interface IBehaviorRandomStroll : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// A random value to determine when to randomly move somewhere. This has a 1/interval chance to choose this goal
    /// </summary>
    [TraitProperty]
    public virtual int Interval => 120;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Distance in blocks on ground that the mob will look for a new spot to move to. Must be at least 1
    /// </summary>
    [TraitProperty]
    public virtual int XzDist => 10;

    /// <summary>
    /// Distance in blocks that the mob will look up or down for a new spot to move to. Must be at least 1
    /// </summary>
    [TraitProperty]
    public virtual int YDist => 7;
}
