// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_owner_hurt_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to target a mob that is hurt by their owner.
/// </summary>
[Trait("minecraft:behavior.owner_hurt_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorOwnerHurtTarget : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// List of entity types that this entity can target if the potential target is hurt by this mob's owner
    /// </summary>
    [TraitProperty]
    public virtual dynamic EntityTypes => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
