// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_controlled_by_player?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to be controlled by the player using an item in the item_controllable property (required). On every tick, the entity will attempt to rotate towards where the player is facing with the control item whilst simultaneously moving forward.
/// </summary>
[Trait("minecraft:behavior.controlled_by_player", TraitSystem.TraitType.Entity)]
public interface IBehaviorControlledByPlayer : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The entity will attempt to rotate to face where the player is facing each tick.
    /// </summary>
    [TraitProperty]
    public virtual float FractionalRotation => 0.5f;

    /// <summary>
    /// Limits the total degrees the entity can rotate to face where the player is facing on each tick.
    /// </summary>
    [TraitProperty]
    public virtual float FractionalRotationLimit => 5f;

    /// <summary>
    /// Speed multiplier of mount when controlled by player.
    /// </summary>
    [TraitProperty]
    public virtual float MountSpeedMultiplier => 1f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
