// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_outdoors?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to move outdoors.
/// </summary>
[Trait("minecraft:behavior.move_outdoors", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveOutdoors : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The radius away from the target block to count as reaching the goal
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 2f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The amount of times to try finding a random outdoors position before failing
    /// </summary>
    [TraitProperty]
    public virtual int SearchCount => 10;

    /// <summary>
    /// The y range to search for an outdoors position for
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 5;

    /// <summary>
    /// The x and z range to search for an outdoors position for
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 15;

    /// <summary>
    /// The movement speed modifier to apply to the entity while it is moving outdoors
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 0.5f;

    /// <summary>
    /// The cooldown time in seconds before the goal can be reused after pathfinding fails
    /// </summary>
    [TraitProperty]
    public virtual float TimeoutCooldown => 8f;
}
