// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_explore_outskirts?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to first travel to a random point on the outskirts of the village, and then explore random points within a small distance.
/// </summary>
[Trait("minecraft:behavior.explore_outskirts", TraitSystem.TraitType.Entity)]
public interface IBehaviorExploreOutskirts : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The distance from the boundary the villager must be within in to explore the outskirts.
    /// </summary>
    [TraitProperty]
    public virtual int[] DistFromBoundary => [5, 0, 5];

    /// <summary>
    /// Total distance in blocks the the entity will explore beyond the village bounds when choosing its travel point.
    /// </summary>
    [TraitProperty]
    public virtual float ExploreDist => 5f;

    /// <summary>
    /// This is the maximum amount of time an entity will attempt to reach it's travel point on the outskirts of the village before the goal exits.
    /// </summary>
    [TraitProperty]
    public virtual float MaxTravelTime => 60f;

    /// <summary>
    /// The wait time in seconds between choosing new explore points will be chosen on a random interval between this value and the minimum wait time.
    /// </summary>
    [TraitProperty]
    public virtual float MaxWaitTime => 0f;

    /// <summary>
    /// The entity must be within this distance for it to consider it has successfully reached its target.
    /// </summary>
    [TraitProperty]
    public virtual float MinDistFromTarget => 2.25f;

    /// <summary>
    /// The minimum perimeter of the village required to run this goal.
    /// </summary>
    [TraitProperty]
    public virtual float MinPerimeter => 1f;

    /// <summary>
    /// The wait time in seconds between choosing new explore points will be chosen on a random interval between this value and the maximum wait time.
    /// </summary>
    [TraitProperty]
    public virtual float MinWaitTime => 3f;

    /// <summary>
    /// A new explore point will randomly be chosen within this XZ distance of the current target position when navigation has finished and the wait timer has elapsed.
    /// </summary>
    [TraitProperty]
    public virtual int NextXz => 5;

    /// <summary>
    /// A new explore point will randomly be chosen within this Y distance of the current target position when navigation has finished and the wait timer has elapsed.
    /// </summary>
    [TraitProperty]
    public virtual int NextY => 3;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The multiplier for speed while using this goal. 1.0 maintains the speed.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Each new explore point will be chosen on a random interval between the minimum and the maximum wait time, divided by this value.
    /// </summary>
    [TraitProperty]
    public virtual float TimerRatio => 2f;
}
