// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_go_home?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to move back to the position they were spawned.
/// </summary>
[Trait("minecraft:behavior.go_home", TraitSystem.TraitType.Entity)]
public interface IBehaviorGoHome : IEntityTrait
{
    /// <summary>
    /// Distance in blocks that the mob is considered close enough to the end of the current path. A new path will then be calculated to continue toward home.
    /// </summary>
    [TraitProperty]
    public virtual float CalculateNewPathRadius => 2f;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 0.5f;

    /// <summary>
    /// A random value to determine when to randomly move somewhere. This has a 1/interval chance to choose this goal.
    /// </summary>
    [TraitProperty]
    public virtual int Interval => 120;

    /// <summary>
    /// Event(s) to run when this goal fails.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnFailed => null;

    /// <summary>
    /// Event(s) to run when this mob gets home.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnHome => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
