// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_flee_sun?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to run away from direct sunlight and seek shade.
/// </summary>
[Trait("minecraft:behavior.flee_sun", TraitSystem.TraitType.Entity)]
public interface IBehaviorFleeSun : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
