// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_croak?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to croak at a random time interval with configurable conditions.
/// </summary>
[Trait("minecraft:behavior.croak", TraitSystem.TraitType.Entity)]
public interface IBehaviorCroak : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Random range in seconds after which the croaking stops. Can also be a constant. Check that the limits imposed on the range (minimum, maximum and maximum distance between values) are respected
    /// </summary>
    [TraitProperty]
    public virtual dynamic Duration => null;

    /// <summary>
    /// Conditions for the behavior to start and keep running. The interval between runs only starts after passing the filters.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Filters => null;

    /// <summary>
    /// Random range in seconds between runs of this behavior. Can also be a constant. Check that the limits imposed on the range (minimum, maximum and maximum distance between values) are respected
    /// </summary>
    [TraitProperty]
    public virtual dynamic Interval => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
