// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_indoors?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to move indoors.
/// </summary>
[Trait("minecraft:behavior.move_indoors", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveIndoors : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The movement speed modifier to apply to the entity while it is moving indoors.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 0.800000011920929f;

    /// <summary>
    /// The cooldown time in seconds before the goal can be reused after pathfinding fails
    /// </summary>
    [TraitProperty]
    public virtual float TimeoutCooldown => 8f;
}
