// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_drink_potion?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to drink potions based on specified environment conditions.
/// </summary>
[Trait("minecraft:behavior.drink_potion", TraitSystem.TraitType.Entity)]
public interface IBehaviorDrinkPotion : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// A list of potions that this entity can drink. Each potion entry has the following parameters:
    /// </summary>
    [TraitProperty]
    public virtual dynamic Potions => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The movement speed modifier to apply to the entity while it is drinking a potion. A value of 0 represents no change in speed.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedModifier => 0f;
}
