// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_beg?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this mob to look at and follow the player that holds food they like.
/// </summary>
[Trait("minecraft:behavior.beg", TraitSystem.TraitType.Entity)]
public interface IBehaviorBeg : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// List of items that this mob likes
    /// </summary>
    [TraitProperty]
    public virtual string Items => "[]";

    /// <summary>
    /// Distance in blocks the mob will beg from
    /// </summary>
    [TraitProperty]
    public virtual float LookDistance => 8f;

    /// <summary>
    /// The range of time in seconds this mob will stare at the player holding a food they like, begging for it
    /// </summary>
    [TraitProperty]
    public virtual dynamic LookTime => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
