// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_emerge?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to emerge from the ground.
/// </summary>
[Trait("minecraft:behavior.emerge", TraitSystem.TraitType.Entity)]
public interface IBehaviorEmerge : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Time in seconds the mob has to wait before using the goal again
    /// </summary>
    [TraitProperty]
    public virtual float CooldownTime => 0.5f;

    /// <summary>
    /// Goal duration in seconds
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 5f;

    /// <summary>
    /// Trigger to be executed when the goal execution is about to end
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnDone => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
