// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_leap_at_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows monsters to jump at and attack their target. Can only be used by hostile mobs.
/// </summary>
[Trait("minecraft:behavior.leap_at_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorLeapAtTarget : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// If true, the mob will only jump at its target if its on the ground. Setting it to false will allow it to jump even if its already in the air
    /// </summary>
    [TraitProperty]
    public virtual bool MustBeOnGround => true;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Allows the actor to be set to persist upon targeting a player
    /// </summary>
    [TraitProperty]
    public virtual bool SetPersistent => false;

    /// <summary>
    /// The height in blocks the mob jumps when leaping at its target
    /// </summary>
    [TraitProperty]
    public virtual float Yd => 0f;
}
