// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_admire_item?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Enables the mob to admire items that have been configured as admirable.
/// </summary>
[Trait("minecraft:behavior.admire_item", TraitSystem.TraitType.Entity)]
public interface IBehaviorAdmireItem : IEntityTrait
{
    /// <summary>
    /// The sound event to play when admiring the item
    /// </summary>
    [TraitProperty]
    public virtual string? AdmireItemSound => null;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Event to run when the mob starts admiring an item.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnAdmireItemStart => null;

    /// <summary>
    /// Event to run when the mob stops admiring an item.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnAdmireItemStop => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The range of time in seconds to randomly wait before playing the sound again. Can be a number, an array [min, max], or an object with range_min and range_max.
    /// </summary>
    [TraitProperty]
    public virtual dynamic SoundInterval => null;
}
