// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_offer_flower?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to offer a flower to another mob with the minecraft:take_flower behavior.
/// </summary>
[Trait("minecraft:behavior.offer_flower", TraitSystem.TraitType.Entity)]
public interface IBehaviorOfferFlower : IEntityTrait
{
    /// <summary>
    /// Percent chance that the mob will start this goal from 0.0 to 1.0 (where 1.0 = 100%). Value must be &lt;= 1.
    /// </summary>
    [TraitProperty]
    public virtual float ChanceToStart => 0.0001250000059371814f;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Conditions that need to be met for the behavior to start.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Filters => null;

    /// <summary>
    /// Maximum rotation (in degrees), on the Y-axis, this entity can rotate its head while trying to look at the target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxHeadRotationY => 30f;

    /// <summary>
    /// The max amount of time (in seconds) that the mob will offer the flower for before exiting the Goal.
    /// </summary>
    [TraitProperty]
    public virtual float MaxOfferFlowerDuration => 20f;

    /// <summary>
    /// Maximum rotation (in degrees), on the X-axis, this entity can rotate while trying to look at the target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxRotationX => 30f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The dimensions of the AABB used to search for a potential mob to offer flower to.
    /// </summary>
    [TraitProperty]
    public virtual int[] SearchArea => [6, 2, 6];
}
