// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_towards_home_restriction?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows entities with a minecraft:home component to move towards their home position. If restriction_radius is set, entities will be able to run this behavior only if outside of it.
/// </summary>
[Trait("minecraft:behavior.move_towards_home_restriction", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveTowardsHomeRestriction : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// This multiplier modifies the entity's speed when moving towards its restriction.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
