// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_celebrate_survive?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the player to trade with this mob. When the goal starts, it will stop the mob's navigation.
/// </summary>
[Trait("minecraft:behavior.celebrate_survive", TraitSystem.TraitType.Entity)]
public interface IBehaviorCelebrateSurvive : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The duration in seconds that the celebration lasts for.
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 30f;

    /// <summary>
    /// Minimum and maximum time between firework (positive, in seconds).
    /// </summary>
    [TraitProperty]
    public virtual dynamic FireworksInterval => null;

    /// <summary>
    /// The event to trigger when the goal's duration expires.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnCelebrationEndEvent => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
