// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_avoid_block?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to avoid certain blocks.
/// </summary>
[Trait("minecraft:behavior.avoid_block", TraitSystem.TraitType.Entity)]
public interface IBehaviorAvoidBlock : IEntityTrait
{
    /// <summary>
    /// The sound event to play when the mob is avoiding a block.
    /// </summary>
    [TraitProperty]
    public virtual dynamic AvoidBlockSound => null;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Event triggers that fire when the entity escapes from the avoided block. Can be a single trigger or an array of triggers.
    /// </summary>
    [TraitProperty]
    public virtual Either<Dictionary<string, object>, Dictionary<string, object>[]>? OnEscape => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Maximum distance to look for a block in y.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 0;

    /// <summary>
    /// Maximum distance to look for a block in xz.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// The range of time in seconds to randomly wait before playing the sound again.
    /// </summary>
    [TraitProperty]
    public virtual dynamic SoundInterval => null;

    /// <summary>
    /// Modifier for sprint speed. 1.0 means keep the regular speed, while higher numbers make the sprint speed faster.
    /// </summary>
    [TraitProperty]
    public virtual float SprintSpeedModifier => 1f;

    /// <summary>
    /// List of block types this mob avoids.
    /// </summary>
    [TraitProperty]
    public virtual string TargetBlocks => "[]";

    /// <summary>
    /// Block search method.
    /// </summary>
    [TraitProperty]
    public virtual string TargetSelectionMethod => "nearest";

    /// <summary>
    /// Should start tick interval.
    /// </summary>
    [TraitProperty]
    public virtual int TickInterval => 1;

    /// <summary>
    /// Modifier for walking speed. 1.0 means keep the regular speed, while higher numbers make the walking speed faster.
    /// </summary>
    [TraitProperty]
    public virtual float WalkSpeedModifier => 1f;
}
