// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_mingle?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to go to the village bell and mingle with other entities.
/// </summary>
[Trait("minecraft:behavior.mingle", TraitSystem.TraitType.Entity)]
public interface IBehaviorMingle : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Time in seconds the mob has to wait before using the goal again
    /// </summary>
    [TraitProperty]
    public virtual float CooldownTime => 0f;

    /// <summary>
    /// Amount of time in seconds that the entity will chat with another entity
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 1f;

    /// <summary>
    /// The distance from its partner that this entity will mingle. If the entity type is not the same as the entity, this value needs to be identical on both entities.
    /// </summary>
    [TraitProperty]
    public virtual float MingleDistance => 2f;

    /// <summary>
    /// The entity type that this entity is allowed to mingle with
    /// </summary>
    [TraitProperty]
    public abstract string MinglePartnerType { get; }

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
