// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_towards_restriction?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// AI goal that drives entities back toward their designated home area when they've wandered too far. Works with components like minecraft:home to define the restriction zone. Used for village-bound mobs, territorial creatures, or any entity that should patrol or return to a specific location.
/// </summary>
[Trait("minecraft:behavior.move_towards_restriction", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveTowardsRestriction : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// This multiplier modifies the entity's speed when moving towards its restriction.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
