// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_to_poi?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to move to a POI if able to.
/// </summary>
[Trait("minecraft:behavior.move_to_poi", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveToPoi : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Tells the goal what POI type it should be looking for
    /// </summary>
    [TraitProperty]
    public virtual dynamic PoiType => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
