// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_avoid_mob_type?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to run away from other entities that meet the criteria specified.
/// </summary>
[Trait("minecraft:behavior.avoid_mob_type", TraitSystem.TraitType.Entity)]
public interface IBehaviorAvoidMobType : IEntityTrait
{
    /// <summary>
    /// The sound event to play when the mob is avoiding another mob.
    /// </summary>
    [TraitProperty]
    public virtual dynamic AvoidMobSound => null;

    /// <summary>
    /// The next target position the entity chooses to avoid another entity will be chosen within this XZ Distance.
    /// </summary>
    [TraitProperty]
    public virtual int AvoidTargetXz => 16;

    /// <summary>
    /// The next target position the entity chooses to avoid another entity will be chosen within this Y Distance.
    /// </summary>
    [TraitProperty]
    public virtual int AvoidTargetY => 7;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The list of conditions another entity must meet to be a valid target to avoid.
    /// </summary>
    [TraitProperty]
    public virtual dynamic EntityTypes => null;

    /// <summary>
    /// Whether or not to ignore direct line of sight while this entity is running away from other specified entities.
    /// </summary>
    [TraitProperty]
    public virtual bool IgnoreVisibility => false;

    /// <summary>
    /// Maximum distance to look for an avoid target for the entity.
    /// </summary>
    [TraitProperty]
    public virtual float MaxDist => 3f;

    /// <summary>
    /// How many blocks away from its avoid target the entity must be for it to stop fleeing from the avoid target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxFlee => 10f;

    /// <summary>
    /// Event that is triggered when escaping from a mob.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnEscapeEvent => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Percent chance this entity will stop avoiding another entity based on that entity's strength, where 1.0 = 100%. Value must be &lt;= 1.
    /// </summary>
    [TraitProperty]
    public virtual float ProbabilityPerStrength => 1f;

    /// <summary>
    /// Determine if we should remove target when fleeing or not.
    /// </summary>
    [TraitProperty]
    public virtual bool RemoveTarget => false;

    /// <summary>
    /// Multiplier for speed when following river. 1.0 means keep the regular speed, while higher numbers make the speed faster.
    /// </summary>
    [TraitProperty]
    public virtual float RiverSpeedMultiplier => 0.75f;

    /// <summary>
    /// The range of time in seconds to randomly wait before playing the sound again.
    /// </summary>
    [TraitProperty]
    public virtual dynamic SoundInterval => null;

    /// <summary>
    /// How many blocks within range of its avoid target the entity must be for it to begin sprinting away from the avoid target.
    /// </summary>
    [TraitProperty]
    public virtual float SprintDistance => 7f;

    /// <summary>
    /// Multiplier for sprint speed. 1.0 means keep the regular speed, while higher numbers make the sprint speed faster.
    /// </summary>
    [TraitProperty]
    public virtual float SprintSpeedMultiplier => 1f;

    /// <summary>
    /// Multiplier for walking speed. 1.0 means keep the regular speed, while higher numbers make the walking speed faster.
    /// </summary>
    [TraitProperty]
    public virtual float WalkSpeedMultiplier => 1f;
}
