// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_go_and_give_items_to_owner?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// The entity will attempt to toss the items from its inventory to its owner.
/// </summary>
[Trait("minecraft:behavior.go_and_give_items_to_owner", TraitSystem.TraitType.Entity)]
public interface IBehaviorGoAndGiveItemsToOwner : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Event(s) to run when this mob throws items.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnItemThrow => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Sets the desired distance to be reached before giving items to owner.
    /// </summary>
    [TraitProperty]
    public virtual float ReachMobDistance => 3f;

    /// <summary>
    /// Sets the entity's speed when running toward the owner.
    /// </summary>
    [TraitProperty]
    public virtual float RunSpeed => 1f;

    /// <summary>
    /// Sets the throw force.
    /// </summary>
    [TraitProperty]
    public virtual float ThrowForce => 0.20000000298023224f;

    /// <summary>
    /// Sound to play when this mob throws an item.
    /// </summary>
    [TraitProperty]
    public virtual dynamic ThrowSound => null;

    /// <summary>
    /// Sets the vertical throw multiplier that is applied on top of the throw force in the vertical direction.
    /// </summary>
    [TraitProperty]
    public virtual float VerticalThrowMul => 1.5f;
}
