// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_charge_held_item?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to charge and use their held item.
/// </summary>
[Trait("minecraft:behavior.charge_held_item", TraitSystem.TraitType.Entity)]
public interface IBehaviorChargeHeldItem : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The list of items that can be used to charge the held item. This list is required and must have at least one item in it. Value must have at least 1 items.
    /// </summary>
    [TraitProperty]
    public virtual string Items => "NA";

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
