// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_random_look_around?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to randomly look around.
/// </summary>
[Trait("minecraft:behavior.random_look_around", TraitSystem.TraitType.Entity)]
public interface IBehaviorRandomLookAround : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// The range of time in seconds the mob will stay looking in a random direction before looking elsewhere
    /// </summary>
    [TraitProperty]
    public virtual dynamic LookTime => null;

    /// <summary>
    /// The rightmost angle a mob can look at on the horizontal plane with respect to its initial facing direction.
    /// </summary>
    [TraitProperty]
    public virtual float MaxAngleOfViewHorizontal => 180f;

    /// <summary>
    /// The leftmost angle a mob can look at on the horizontal plane with respect to its initial facing direction.
    /// </summary>
    [TraitProperty]
    public virtual float MinAngleOfViewHorizontal => -180f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The probability of randomly looking around.
    /// </summary>
    [TraitProperty]
    public virtual float Probability => 0.019999999552965164f;
}
