// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_eat_carried_item?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// If the mob is carrying a food item, the mob will eat it and the effects will be applied to the mob.
/// </summary>
[Trait("minecraft:behavior.eat_carried_item", TraitSystem.TraitType.Entity)]
public interface IBehaviorEatCarriedItem : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Time in seconds the mob should wait before eating the item.
    /// </summary>
    [TraitProperty]
    public virtual float DelayBeforeEating => 0f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
