// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_move_towards_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows mob to move towards its current target.
/// </summary>
[Trait("minecraft:behavior.move_towards_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorMoveTowardsTarget : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Defines the radius in blocks that the mob tries to be from the target. A value of 0 means it tries to occupy the same block as the target
    /// </summary>
    [TraitProperty]
    public virtual float WithinRadius => 0f;
}
