// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_open_door?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to open doors. Requires the mob to be able to path through doors, otherwise the mob won't even want to try opening them.
/// </summary>
[Trait("minecraft:behavior.open_door", TraitSystem.TraitType.Entity)]
public interface IBehaviorOpenDoor : IEntityTrait
{
    /// <summary>
    /// If true, the mob will close the door after opening it and going through it.
    /// </summary>
    [TraitProperty]
    public virtual bool CloseDoorAfter => true;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
