// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_lay_egg?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to lay an egg block on certain types of blocks if the mob is pregnant.
/// </summary>
[Trait("minecraft:behavior.lay_egg", TraitSystem.TraitType.Entity)]
public interface IBehaviorLayEgg : IEntityTrait
{
    /// <summary>
    /// Allows the mob to lay its eggs from below the target if it can't get there. This is useful if the target block is water with air above, since mobs may not be able to get to the air block above water.
    /// </summary>
    [TraitProperty]
    public virtual bool AllowLayingFromBelow => false;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Block type for the egg to lay. If this is a turtle egg, the number of eggs in the block is randomly set.
    /// </summary>
    [TraitProperty]
    public virtual string EggType => "minecraft:turtle_egg";

    /// <summary>
    /// Distance in blocks within the mob considers it has reached the goal. This is the "wiggle room" to stop the AI from bouncing back and forth trying to reach a specific spot. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual float GoalRadius => 0.5f;

    /// <summary>
    /// Name of the sound event played when laying the egg. Defaults to lay_egg, which is used for Turtles.
    /// </summary>
    [TraitProperty]
    public virtual dynamic LayEggSound => null;

    /// <summary>
    /// Duration of the laying egg process in seconds. From 1.26.10 onward, lay_seconds only accepts values greater than or equal to 0; entity JSON with negative values will fail to load.
    /// </summary>
    [TraitProperty]
    public virtual float LaySeconds => 10f;

    /// <summary>
    /// Event to run when this mob lays the egg.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OnLay => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// The height in blocks the mob will look for the block to move towards. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 1;

    /// <summary>
    /// The distance in blocks it will look for the block to move towards. Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SearchRange => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Blocks that the mob can lay its eggs on top of.
    /// </summary>
    [TraitProperty]
    public virtual string[] TargetBlocks => new[] { "[minecraft:sand]" };

    /// <summary>
    /// Types of materials that can exist above the target block. Valid types are Air, Water, and Lava.
    /// </summary>
    [TraitProperty]
    public virtual string[] TargetMaterialsAboveBlock => new[] { "[air]" };

    /// <summary>
    /// Specifies if the default lay-egg animation should be played when the egg is placed or not.
    /// </summary>
    [TraitProperty]
    public virtual bool UseDefaultAnimation => true;
}
