// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_charge_attack?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to damage a target by using a running attack.
/// </summary>
[Trait("minecraft:behavior.charge_attack", TraitSystem.TraitType.Entity)]
public interface IBehaviorChargeAttack : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// A charge attack cannot start if the entity is farther than this distance to the target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxDistance => 3f;

    /// <summary>
    /// A charge attack cannot start if the entity is closer than this distance to the target.
    /// </summary>
    [TraitProperty]
    public virtual float MinDistance => 2f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    [TraitProperty]
    public virtual dynamic SoundEvent => null;

    /// <summary>
    /// Modifies the entity's speed when charging toward the target.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Percent chance this entity will start a charge attack, if not already attacking (1.0 = 100%).
    /// </summary>
    [TraitProperty]
    public virtual float SuccessRate => 0.1428000032901764f;
}
