// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_hide?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows a mob with the hide component to attempt to move to - and hide at - an owned or nearby POI.
/// </summary>
[Trait("minecraft:behavior.hide", TraitSystem.TraitType.Entity)]
public interface IBehaviorHide : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Amount of time in seconds that the mob reacts.
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 1f;

    /// <summary>
    /// Tells the goal what POI type it should be looking for
    /// </summary>
    [TraitProperty]
    public virtual dynamic PoiType => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this goal.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// The cooldown time in seconds before the goal can be reused after a internal failure or timeout condition.
    /// </summary>
    [TraitProperty]
    public virtual float TimeoutCooldown => 8f;
}
