// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_lay_down?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows mobs to lay down at times.
/// </summary>
[Trait("minecraft:behavior.lay_down", TraitSystem.TraitType.Entity)]
public interface IBehaviorLayDown : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// A random value to determine at what intervals something can occur. This has a 1/interval chance to choose this goal
    /// </summary>
    [TraitProperty]
    public virtual int Interval => 120;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// A random value in which the goal can use to pull out of the behavior. This is a 1/interval chance to stop laying down
    /// </summary>
    [TraitProperty]
    public virtual int RandomStopInterval => 120;
}
