// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_float?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to stay afloat while swimming. Passengers will be kicked out the moment the mob's head goes underwater, which may not happen for tall mobs.
/// </summary>
[Trait("minecraft:behavior.float", TraitSystem.TraitType.Entity)]
public interface IBehaviorFloat : IEntityTrait
{
    /// <summary>
    /// Probability per tick (0-1) that the entity will attempt to float when in water.
    /// </summary>
    [TraitProperty]
    public virtual float ChancePerTickToFloat => 0.8f;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// If true, the mob will keep sinking as long as it has passengers.
    /// </summary>
    [TraitProperty]
    public virtual bool SinkWithPassengers => false;

    /// <summary>
    /// Time in seconds the entity must spend with its head underwater before any passengers are dismounted.
    /// </summary>
    [TraitProperty]
    public virtual float TimeUnderWaterToDismountPassengers => 0f;
}
