// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_follow_caravan?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to follow mobs that are in a caravan.
/// </summary>
[Trait("minecraft:behavior.follow_caravan", TraitSystem.TraitType.Entity)]
public interface IBehaviorFollowCaravan : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Number of entities that can be in the caravan
    /// </summary>
    [TraitProperty]
    public virtual int EntityCount => 1;

    /// <summary>
    /// List of entity types that this mob can follow in a caravan. Can be a single filter object or an array of filter objects.
    /// </summary>
    [TraitProperty]
    public virtual Either<EntityFilter, EntityFilter[]>? EntityTypes => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
