// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_eat_mob?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to eat a specified Mob.
/// </summary>
[Trait("minecraft:behavior.eat_mob", TraitSystem.TraitType.Entity)]
public interface IBehaviorEatMob : IEntityTrait
{
    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Sets the time in seconds the eat animation should play for.
    /// </summary>
    [TraitProperty]
    public virtual float EatAnimationTime => 1f;

    /// <summary>
    /// Sets the sound that should play when eating a mob.
    /// </summary>
    [TraitProperty]
    public virtual string? EatMobSound => null;

    /// <summary>
    /// The loot table for loot to be dropped when eating a mob.
    /// </summary>
    [TraitProperty]
    public virtual string? LootTable => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Sets the force which the mob-to-be-eaten is pulled towards the eating mob.
    /// </summary>
    [TraitProperty]
    public virtual float PullInForce => 1f;

    /// <summary>
    /// Sets the desired distance to be reached before eating the mob.
    /// </summary>
    [TraitProperty]
    public virtual float ReachMobDistance => 1f;

    /// <summary>
    /// Sets the entity's speed when running toward the target.
    /// </summary>
    [TraitProperty]
    public virtual float RunSpeed => 1f;
}
