// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_hurt_by_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the mob to target another mob that hurts them.
/// </summary>
[Trait("minecraft:behavior.hurt_by_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorHurtByTarget : IEntityTrait
{
    /// <summary>
    /// If true, nearby mobs of the same type will be alerted about the damage
    /// </summary>
    [TraitProperty]
    public virtual bool AlertSameType => false;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// List of entity types that this mob can target when hurt by them
    /// </summary>
    [TraitProperty]
    public virtual dynamic EntityTypes => null;

    /// <summary>
    /// If true, the mob will hurt its owner and other mobs with the same owner as itself
    /// </summary>
    [TraitProperty]
    public virtual bool HurtOwner => false;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;
}
