// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_fire_at_target?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to attack by firing a shot with a delay. Anchor and offset parameters of this component overrides the anchor and offset from projectile component.
/// </summary>
[Trait("minecraft:behavior.fire_at_target", TraitSystem.TraitType.Entity)]
public interface IBehaviorFireAtTarget : IEntityTrait
{
    /// <summary>
    /// The cooldown time in seconds before this goal can be used again.
    /// </summary>
    [TraitProperty]
    public virtual float AttackCooldown => 0.5f;

    /// <summary>
    /// Target needs to be within this range for the attack to happen.
    /// </summary>
    [TraitProperty]
    public virtual dynamic AttackRange => null;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Conditions that need to be met for the behavior to start.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Filters => null;

    /// <summary>
    /// Maximum head rotation (in degrees), on the X-axis, that this entity can apply while trying to look at the target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxHeadRotationX => 30f;

    /// <summary>
    /// Maximum head rotation (in degrees), on the Y-axis, that this entity can apply while trying to look at the target.
    /// </summary>
    [TraitProperty]
    public virtual float MaxHeadRotationY => 30f;

    /// <summary>
    /// Entity anchor for the projectile spawn location.
    /// </summary>
    [TraitProperty]
    public virtual dynamic OwnerAnchor => null;

    /// <summary>
    /// Offset vector from the owner_anchor.
    /// </summary>
    [TraitProperty]
    public virtual int[] OwnerOffset => [0, 0, 0];

    /// <summary>
    /// Time in seconds between firing the projectile and ending the goal.
    /// </summary>
    [TraitProperty]
    public virtual float PostShootDelay => 0.20000000298023224f;

    /// <summary>
    /// Time in seconds before firing the projectile.
    /// </summary>
    [TraitProperty]
    public virtual float PreShootDelay => 0.75f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Actor definition to use as projectile for the ranged attack. The actor must be a projectile. This field is required for the goal to be usable.
    /// </summary>
    [TraitProperty]
    public virtual string? ProjectileDef => null;

    /// <summary>
    /// Field of view (in degrees) when using sensing to detect a target for attack.
    /// </summary>
    [TraitProperty]
    public virtual float RangedFov => 90f;

    /// <summary>
    /// Entity anchor for projectile target.
    /// </summary>
    [TraitProperty]
    public virtual dynamic TargetAnchor => null;

    /// <summary>
    /// Offset vector from the target_anchor.
    /// </summary>
    [TraitProperty]
    public virtual int[] TargetOffset => [0, 0, 0];
}
