// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_jump_to_block?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to jump to another random block.
/// </summary>
[Trait("minecraft:behavior.jump_to_block", TraitSystem.TraitType.Entity)]
public interface IBehaviorJumpToBlock : IEntityTrait
{
    /// <summary>
    /// Minimum and maximum cooldown time-range (positive, in seconds) between each attempted jump.
    /// </summary>
    [TraitProperty]
    public abstract int CooldownRange { get; }

    /// <summary>
    /// Blocks that the mob can't jump to.
    /// </summary>
    [TraitProperty]
    public virtual string[]? ForbiddenBlocks => null;

    /// <summary>
    /// The maximum velocity with which the mob can jump.
    /// </summary>
    [TraitProperty]
    public virtual float MaxVelocity => 1.5f;

    /// <summary>
    /// The minimum distance (in blocks) from the mob to a block, in order to consider jumping to it.
    /// </summary>
    [TraitProperty]
    public virtual int MinimumDistance => 2;

    /// <summary>
    /// The minimum length (in blocks) of the mobs path to a block, in order to consider jumping to it.
    /// </summary>
    [TraitProperty]
    public virtual int MinimumPathLength => 5;

    /// <summary>
    /// Blocks that the mob prefers jumping to.
    /// </summary>
    [TraitProperty]
    public virtual string[]? PreferredBlocks => null;

    /// <summary>
    /// Chance (between 0.0 and 1.0) that the mob will jump to a preferred block, if in range. Only matters if preferred blocks are defined.
    /// </summary>
    [TraitProperty]
    public virtual float PreferredBlocksChance => 1f;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public abstract int Priority { get; }

    /// <summary>
    /// The scalefactor of the bounding box of the mob while it is jumping.
    /// </summary>
    [TraitProperty]
    public virtual float ScaleFactor => 0.7f;

    /// <summary>
    /// The height (in blocks, in range [2, 15]) of the search box, centered around the mob.
    /// </summary>
    [TraitProperty]
    public virtual int SearchHeight => 10;

    /// <summary>
    /// The width (in blocks, in range [2, 15]) of the search box, centered around the mob.
    /// </summary>
    [TraitProperty]
    public virtual int SearchWidth => 8;
}
