// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitygoals/minecraftbehavior_follow_target_leader?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows mob to move towards its target leader.
/// </summary>
[Trait("minecraft:behavior.follow_target_leader", TraitSystem.TraitType.Entity)]
public interface IBehaviorFollowTargetLeader : IEntityTrait
{
    /// <summary>
    /// If true, the mob will always search for a valid leader to follow if none is found or current leader is not valid anymore
    /// </summary>
    [TraitProperty]
    public virtual bool AlwaysLookForLeader => false;

    [TraitProperty]
    public virtual dynamic ControlFlags => null;

    /// <summary>
    /// Defines the distance in blocks the mob will stay from its target while following.
    /// </summary>
    [TraitProperty]
    public virtual float FollowDistance => 0f;

    /// <summary>
    /// The filters to use when determining if a mob is a suitable leader or not.
    /// </summary>
    [TraitProperty]
    public virtual dynamic LeaderFilters => null;

    /// <summary>
    /// As priority approaches 0, the priority is increased. The higher the priority, the sooner this behavior will be executed as a goal.
    /// </summary>
    [TraitProperty]
    public virtual int Priority => 0;

    /// <summary>
    /// Number of ticks that must pass before a new search is initiated after a target is not found, lost, or becomes invalid.
    /// </summary>
    [TraitProperty]
    public virtual int SearchCooldown => 20;

    /// <summary>
    /// Movement speed multiplier of the mob when using this AI Goal
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;

    /// <summary>
    /// Defines the maximum distance in blocks a mob can get from its target leader before giving up trying to follow it.
    /// </summary>
    [TraitProperty]
    public virtual float WithinRadius => 0f;
}
