// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_allow_off_hand?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:allow_off_hand", TraitSystem.TraitType.Item)]
public interface IAllowOffHand : IItemTrait
{
    [TraitProperty]
    /* Determines whether the item can be placed in the off hand slot. */
    public abstract bool Value { get; }
}
