// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The allow_off_hand component determines whether the item can be placed in the off hand slot of the inventory.
/// </summary>
[Trait("minecraft:allow_off_hand", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IAllowOffHand : IItemTrait
{
    /// <summary>
    /// Determines whether the item can be placed in the off hand slot.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => false;
}
