// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_block_placer?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:block_placer", TraitSystem.TraitType.Item)]
public interface IBlockPlacer : IItemTrait
{
    /// <summary>
    /// If true, block placement through this item will be aligned while holding the interaction button down. Defaults to false.
    /// </summary>
    [TraitProperty]
    public virtual bool AlignedPlacement => false;

    /// <summary>
    /// Defines the block that will be placed.
    /// </summary>
    [TraitProperty]
    public abstract dynamic Block { get; }

    /// <summary>
    /// If true, the item will be registered as the item for this block.
    /// </summary>
    [TraitProperty]
    public virtual bool ReplaceBlockItem => false;

    /// <summary>
    /// List of block descriptors of the blocks that this item can be used on. If left empty, all blocks will be allowed. Value must have at most 256 items.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? UseOn => null;
}
