// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_block_placer?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:block_placer", TraitSystem.TraitType.Item)]
public interface IBlockPlacer
{
    [TraitProperty]
    /* If true, block placement through this item will be aligned while holding the interaction button down. Defaults to false. */
    public virtual bool AlignedPlacement => false;

    [TraitProperty]
    /* Defines the block that will be placed. */
    public abstract dynamic Block { get; }

    [TraitProperty]
    /* If true, the item will be registered as the item for this block. */
    public virtual bool ReplaceBlockItem => false;

    [TraitProperty]
    /* List of block descriptors of the blocks that this item can be used on. If left empty, all blocks will be allowed. Value must have at most 256 items. */
    public virtual string[] UseOn => [];
}
