// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_bundle_interaction?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Enables the bundle-specific interaction scheme and tooltip for an item.
/// </summary>
[Trait("minecraft:bundle_interaction", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.40")]
public interface IBundleInteraction : IItemTrait
{
    /// <summary>
    /// The maximum number of slots in the bundle viewable by the plater. Can be from 1 to 64. Default is 12. Value must be &gt;= 1. Value must be &lt;= 64.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 0, 64)]
    public virtual int NumViewableSlots => 12;
}