// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// [EXPERIMENTAL] Adds bundle-specific interactions and tooltip to the item. Requires a "minecraft:storage_item" component.
/// </summary>
[Trait("minecraft:bundle_interaction", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.30")]
public interface IBundleInteraction : IItemTrait
{
    /// <summary>
    /// The maximum number of slots in the bundle viewable by the plater. Can be from 1 to 64. Default is 12.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 1,64)]
    public virtual int NumViewableSlots => 12;
}
