// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_can_destroy_in_creative?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// The can_destroy_in_creative component determines if the item can be used by a player to break blocks when in creative mode.
/// </summary>
[Trait("minecraft:can_destroy_in_creative", TraitSystem.TraitType.Item)]
public interface ICanDestroyInCreative : IItemTrait
{
    /// <summary>
    /// Determines whether the item can be used to destroy blocks while in creative mode.
    /// </summary>
    [TraitProperty]
    public abstract bool Value { get; }
}
