// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_can_destroy_in_creative?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:can_destroy_in_creative", TraitSystem.TraitType.Item)]
public interface ICanDestroyInCreative
{
    [TraitProperty]
    /* Determines whether the item can be used to destroy blocks while in creative mode. */
    public abstract bool Value { get; }
}
