// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_compostable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:compostable", TraitSystem.TraitType.Item)]
public interface ICompostable : IItemTrait
{
    /// <summary>
    /// The chance of this item to create a layer upon composting with the composter. Valid value range is 1 - 100 inclusive Value must be &gt;= 1. Value must be &lt;= 100.
    /// </summary>
    [TraitProperty]
    public abstract int CompostingChance { get; }
}
