// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_cooldown?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Adds a cooldown to an item, preventing it from being used again for a specified duration. Items sharing the same category will enter cooldown together when any one of them is used.
/// </summary>
[Trait("minecraft:cooldown", TraitSystem.TraitType.Item)]
public interface ICooldown : IItemTrait
{
    /// <summary>
    /// A string identifier that groups items together. When an item with a cooldown is used, all items sharing the same category also enter cooldown.
    /// </summary>
    [TraitProperty]
    public abstract string Category { get; }

    /// <summary>
    /// The duration of time in seconds that items with the matching category will spend cooling down before becoming usable again.
    /// </summary>
    [TraitProperty]
    public abstract float Duration { get; }

    /// <summary>
    /// The type of action that triggers the cooldown. Use 'use' for items consumed on use, or 'attack' for weapons. Default is 'use'.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Type => null;
}
