// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Adds a cooldown to the item so that, after performing an action of the specified "type", all items with a "minecraft:cooldown" component in the same "category" become unable to perform that same type of action for the number of seconds defined in "duration".
/// </summary>
[Trait("minecraft:cooldown", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface ICooldown : IItemTrait
{
    /// <summary>Equivalent to <c>use</c></summary>
    public const string ItemCooldownType_Use = "use";
    /// <summary>Equivalent to <c>attack</c></summary>
    public const string ItemCooldownType_Attack = "attack";
    /// <summary>
    /// All items sharing the same "category" are put on cooldown when an action of the specified "type" is performed.
    /// </summary>
    [TraitProperty]
    public abstract string Category { get; }
    /// <summary>
    /// Duration of the cooldown, in seconds, before the item can perform an action of the specified "type" again.
    /// </summary>
    [TraitProperty]
    public abstract float Duration { get; }
    /// <summary>
    /// The type of action the cooldown applies to. Options are mutually exclusive, so cooldown for one type of action does not affect the others. Values: "use" (when using an item), "attack" (when attack with an item).
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "use","attack")]
    public virtual string Type => "use";
}
