// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_damage_absorption?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// It allows an item to absorb damage that would otherwise be dealt to its wearer. For this to happen, the item needs to be equipped in an armor slot. The absorbed damage reduces the item's durability, with any excess damage being ignored. Because of this, the item also needs a minecraft:durability component.
/// </summary>
[Trait("minecraft:damage_absorption", TraitSystem.TraitType.Item)]
public interface IDamageAbsorption : IItemTrait
{
    /// <summary>
    /// List of damage causes that can be absorbed by the item. By default, no damage cause is absorbed. Value must have at least 1 items.
    /// </summary>
    [TraitProperty]
    public abstract string[] AbsorbableCauses { get; }
}
