// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// It allows an item to absorb damage that would otherwise be dealt to its wearer. For this to happen, the item needs to be equipped in an armor slot. The absorbed damage reduces the item&apos;s durability, with any excess damage being ignored. Because of this, the item also needs a `minecraft:durability` component.
/// </summary>
[Trait("minecraft:damage_absorption", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.10")]
public interface IDamageAbsorption : IItemTrait
{
    /// <summary>
    /// List of damage causes that can be absorbed by the item. By default, no damage cause is absorbed.
    /// </summary>
    [TraitProperty]
    public abstract string[] AbsorbableCauses { get; }
}
