// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// The damage component determines how much extra damage the item does on attack.
/// </summary>
[Trait("minecraft:damage", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.26.0")]
public interface IDamage : IItemTrait
{
    /// <summary>
    /// Specifies how much extra damage the item does, must be a positive number.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 0,32767)]
    public virtual int Value => 0;
}
