// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_damage?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:damage", TraitSystem.TraitType.Item)]
public interface IDamage : IItemTrait
{
    /// <summary>
    /// The amount of extra damage this item deals when attacking. This value is added to the base attack damage. Must be a positive integer.
    /// </summary>
    [TraitProperty]
    public abstract int Value { get; }
}
