// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// Digger item component specifies how quickly this item can dig specific blocks.
/// </summary>
[Trait("minecraft:digger", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IDigger : IItemTrait
{
    /// <summary>
    /// Representation of the BlockInfo JSON object
    /// </summary>
    public struct BlockInfo
    {
        /// <summary>
        /// Block to be dug.
        /// </summary>
        [JsonProperty("block")]
        public required Either<BlockTypeDescriptor, string> Block;
        /// <summary>
        /// Digging speed for the correlating block(s).
        /// </summary>
        [JsonProperty("speed")]
        public required int Speed;
    }
    /// <summary>
    /// A list of blocks to dig with correlating speeds of digging.
    /// </summary>
    [TraitProperty]
    public virtual BlockInfo[] DestroySpeeds => [];
    /// <summary>
    /// Determines whether this item should be impacted if the efficiency enchantment is applied to it.
    /// </summary>
    [TraitProperty]
    public virtual bool UseEfficiency => false;
}
