// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_digger?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;

[Trait("minecraft:digger", TraitSystem.TraitType.Item)]
public interface IDigger : IItemTrait
{
    /// <summary>
    /// An array of objects that define which blocks this item can dig and at what speed. Each entry specifies a block (by ID or tag query) and a speed multiplier.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? DestroySpeeds => null;

    /// <summary>
    /// When true, the Efficiency enchantment will increase the dig speed of this item. Default is false.
    /// </summary>
    [TraitProperty]
    public virtual bool UseEfficiency => false;
}
