// autogenerated by ingot
// log: generated subtype BlockInfo (2 fields)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.Common.SharedConstructs;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using Newtonsoft.Json;
using Formatting = ingot.Core.Common.Formatting;

/// <summary>
/// Digger item component specifies how quickly this item can dig specific blocks.
/// </summary>
[Trait("minecraft:digger", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IDigger : IItemTrait
{
    /// <summary>
    /// A list of blocks to dig with correlating speeds of digging.
    /// </summary>
    [TraitProperty]
    public virtual BlockInfo[] DestroySpeeds => [];
    /// <summary>
    /// Determines whether this item should be impacted if the efficiency enchantment is applied to it.
    /// </summary>
    [TraitProperty]
    public virtual bool UseEfficiency => false;
}

/// <summary>
/// BlockInfo
/// </summary>
public class BlockInfo : ICompilableFragment
{
    /// <summary>
    /// Block to be dug.
    /// </summary>
    public required BlockTypeDescriptor Block;
    /// <summary>
    /// Digging speed for the correlating block(s).
    /// </summary>
    public required int Speed;

    /// <inheritdoc/>
    public void Compile(ref JsonTextWriter writer)
    {
        JsonHelper json = new(ref writer);
        json.Object("", () =>
        {
            json.Property(Formatting.PascalToSnakeCase(nameof(Block)), Block);
            json.Property(Formatting.PascalToSnakeCase(nameof(Speed)), Speed);
        });
    }
}
