// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_display_name?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:display_name", TraitSystem.TraitType.Item)]
public interface IDisplayName
{
    [TraitProperty]
    /* Name shown for an item. */
    public abstract string Value { get; }
}
