// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The display_name item component specifies the text shown whenever an item's name is displayed, like in hover text.
/// </summary>
[Trait("minecraft:display_name", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IDisplayName : IItemTrait
{
    /// <summary>
    /// Name shown for an item.
    /// </summary>
    [TraitProperty]
    public abstract string Value { get; }
}
