// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// Enables an item to emit effects when it receives damage. Because of this, the item also needs a `minecraft:durability` component.
/// </summary>
[Trait("minecraft:durability_sensor", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.10")]
public interface IDurabilitySensor : IItemTrait
{
    /// <summary>
    /// Representation of the DurabilitySensorDurabilityThreshold JSON object
    /// </summary>
    public struct DurabilitySensorDurabilityThreshold
    {
        /// <summary>
        /// The effects are emitted when the item durability value is less than or equal to this value.
        /// </summary>
        [JsonProperty("durability")]
        public int Durability;
        /// <summary>
        /// Particle effect to emit when the threshold is met.
        /// </summary>
        [JsonProperty("particle_type")]
        public string ParticleType;
        /// <summary>
        /// Sound effect to emit when the threshold is met.
        /// </summary>
        [JsonProperty("sound_event")]
        public string SoundEvent;
    }
    /// <summary>
    /// The list of both durability thresholds and effects emitted when each threshold is met. When multiple thresholds are met, only the threshold with the lowest durability after applying the damage is considered.
    /// </summary>
    [TraitProperty]
    public abstract DurabilitySensorDurabilityThreshold[] DurabilityThresholds { get; }
}
