// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Enables an item to emit effects when it receives damage. Because of this, the item also needs a `minecraft:durability` component.
/// </summary>
[Trait("minecraft:durability_sensor", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.10")]
public interface IDurabilitySensor : IItemTrait
{
    /// <summary>
    /// The list of both durability thresholds and effects emitted when each threshold is met. When multiple thresholds are met, only the threshold with the lowest durability after applying the damage is considered.
    /// </summary>
    [TraitProperty]
    public abstract string[] DurabilityThresholds { get; }
}
