// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_durability?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:durability", TraitSystem.TraitType.Item)]
public interface IDurability : IItemTrait
{
    [TraitProperty]
    /* Specifies the percentage chance of this item losing durability. */
    public virtual dynamic DamageChance => """{"max":100,"min":100}""";

    [TraitProperty]
    /* Max durability is the amount of damage that this item can take before breaking. This is a required parameter and has a minimum of 0. */
    public abstract int MaxDurability { get; }
}
