// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_durability?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Sets how much damage the item can take before breaking, and allows the item to be combined at an anvil, grindstone, or crafting table.
/// </summary>
[Trait("minecraft:durability", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.0")]
public interface IDurability : IItemTrait
{
    /// <summary>
    /// Specifies the percentage chance of this item losing durability.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? DamageChance => null;

    /// <summary>
    /// Max durability is the amount of damage that this item can take before breaking. This is a required parameter and has a minimum of 0.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraint.Constraint.Range, 0, 32767)]
    public abstract int MaxDurability { get; }
}