// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.Common.SharedConstructs;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The durability item component specifies how much damage the item takes before breaking, and allows the item to be combined to repair or augment them.
/// </summary>
[Trait("minecraft:durability", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IDurability : IItemTrait
{
    /// <summary>
    /// Specifies the percentage chance of this item losing durability. Default is set to 100. Defined as an int range with min and max value.
    /// </summary>
    [TraitProperty]
    public virtual Range? DamageChance => null;
    /// <summary>
    /// Max durability is the amount of damage that this item can take before breaking. This is a required parameter and has a minimum of 0.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.GreaterThanEq, 0)]
    public abstract int MaxDurability { get; }
}
