// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_durability_sensor?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:durability_sensor", TraitSystem.TraitType.Item)]
public interface IDurabilitySensor : IItemTrait
{
    /// <summary>
    /// The list of both durability thresholds and effects emitted when each threshold is met.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? DurabilityThresholds { get; }

    /// <summary>
    /// Sound effect to emit when the threshold is met.
    /// </summary>
    [TraitProperty]
    public abstract string SoundEvent { get; }
}
