// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// 
/// </summary>
[Trait("minecraft:dyeable", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.30")]
public interface IDyeable : IItemTrait
{
    /// <summary>
    /// 
    /// </summary>
    [TraitProperty]
    public virtual string? DefaultColor => "#ffffff";
}
