// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_dyeable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Enables players to dye this item using dyes in a crafting grid, like leather armor. Configure the default color when undyed. The item stores its color in NBT data and renders with the player-chosen tint, enabling customizable cosmetic appearances for armor and equipment.
/// </summary>
[Trait("minecraft:dyeable", TraitSystem.TraitType.Item)]
public interface IDyeable : IItemTrait
{
    /// <summary>
    /// Default RGB color when the item has not been dyed, as a JSON array string (e.g. <c>[255, 255, 255]</c>).
    /// </summary>
    [TraitProperty]
    public virtual string DefaultColor => "[255, 255, 255]";
}
