// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_dyeable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:dyeable", TraitSystem.TraitType.Item)]
public interface IDyeable
{
    [TraitProperty]
    public virtual string DefaultColor => "[255, 255, 255]";
}
