// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_enchantable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:enchantable", TraitSystem.TraitType.Item)]
public interface IEnchantable : IItemTrait
{
    /// <summary>
    /// Specifies which types of enchantments can be applied.
    /// </summary>
    [TraitProperty]
    public abstract string Slot { get; }

    /// <summary>
    /// Specifies the value of the enchantment (minimum of 0).
    /// </summary>
    [TraitProperty]
    public abstract int Value { get; }
}
