// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// The entity_placer item component specifies the blocks that the item can be placed on.
/// </summary>
[Trait("minecraft:entity_placer", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IEntityPlacer : IItemTrait
{
    /// <summary>
    /// List of block descriptors of the blocks that this item can be dispensed on. If left empty, all blocks will be allowed.
    /// </summary>
    [TraitProperty]
    public virtual Either<BlockTypeDescriptor, string>[] DispenseOn => [];
    /// <summary>
    /// The entity to be placed in the world.
    /// </summary>
    [TraitProperty]
    public abstract Identifier Entity { get; }
    /// <summary>
    /// List of block descriptors of the blocks that this item can be used on. If left empty, all blocks will be allowed.
    /// </summary>
    [TraitProperty]
    public virtual Either<BlockTypeDescriptor, string>[] UseOn => [];
}
