// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_fire_resistant?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:fire_resistant", TraitSystem.TraitType.Item)]
public interface IFireResistant : IItemTrait
{
    [TraitProperty]
    /* Determines whether the item is immune to burning when dropped in fire or lava. */
    public virtual bool Value => true;
}
