// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// Determines whether the item is immune to burning when dropped in fire or lava.
/// </summary>
[Trait("minecraft:fire_resistant", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.90")]
public interface IFireResistant : IItemTrait
{
    /// <summary>
    /// Determines whether the item is immune to burning when dropped in fire or lava.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => true;
}
