// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_food?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Sets the item as a food component, allowing it to be edible to the player.
/// </summary>
[Trait("minecraft:food", TraitSystem.TraitType.Item)]
public interface IFood : IItemTrait
{
    /// <summary>
    /// If true you can always eat this item (even when not hungry). Default is set to false.
    /// </summary>
    [TraitProperty]
    public virtual bool CanAlwaysEat => false;

    /// <summary>
    /// Value that is added to the entity's nutrition when the item is used. Default is set to 0.
    /// </summary>
    [TraitProperty]
    public virtual int Nutrition => 0;

    /// <summary>
    /// saturation_modifier is used in this formula: (nutrition * saturation_modifier * 2) when applying the saturation buff. Default is set to 0.6.
    /// </summary>
    [TraitProperty]
    public virtual float SaturationModifier => 0.6000000238418579f;

    /// <summary>
    /// When used, converts to the item specified by the string in this field. Default does not convert item.
    /// </summary>
    [TraitProperty]
    public virtual string UsingConvertsTo => "";
}