// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// When an item has a food component, it becomes edible to the player. Must have the 'minecraft:use_duration' component in order to function properly.
/// </summary>
[Trait("minecraft:food", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IFood : IItemTrait
{
    /// <summary>
    /// If true you can always eat this item (even when not hungry). Default is set to false.
    /// </summary>
    [TraitProperty]
    public virtual bool CanAlwaysEat => false;
    /// <summary>
    /// Value that is added to the entity's nutrition when the item is used. Default is set to 0.
    /// </summary>
    [TraitProperty]
    public virtual int Nutrition => 0;
    /// <summary>
    /// saturation_modifier is used in this formula: (nutrition * saturation_modifier * 2) when applying the saturation buff. Default is set to 0.6.
    /// </summary>
    [TraitProperty]
    public virtual float SaturationModifier => 0.6000000238418579f;
    /// <summary>
    /// When used, converts to the item specified by the string in this field. Default does not convert item.
    /// </summary>
    [TraitProperty]
    public virtual Either<string, Dictionary<string, string>> UsingConvertsTo => null;
}
