// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Fuel item component allows this item to be used as fuel in a furnace to 'cook' other items.
/// </summary>
[Trait("minecraft:fuel", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IFuel : IItemTrait
{
    /// <summary>
    /// Amount of time, in seconds, this fuel will cook items.
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 0.05000000074505806f;
}
