// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_glint?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Determines whether the item has the enchanted glint render effect on it.
/// </summary>
[Trait("minecraft:glint", TraitSystem.TraitType.Item)]
public interface IGlint : IItemTrait
{
    /// <summary>
    /// Whether the item has the enchanted glint render effect.
    /// </summary>
    [TraitProperty]
    public abstract bool Value { get; }
}