// autogenerated by ingot
// log: resolved root oneOf -> object form (1 properties)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The glint component determines whether the item has the enchanted glint render effect on it.
/// </summary>
[Trait("minecraft:glint", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IGlint : IItemTrait
{
    /// <summary>
    /// Determines whether the item has the glint effect.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => false;
}
