// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The hand_equipped component determines if an item is rendered like a tool while it is in a player's hand.
/// </summary>
[Trait("minecraft:hand_equipped", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IHandEquipped : IItemTrait
{
    /// <summary>
    /// Determines whether the item is rendered like a tool while in the player's hand.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => false;
}
