// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_hand_equipped?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:hand_equipped", TraitSystem.TraitType.Item)]
public interface IHandEquipped : IItemTrait
{
    /// <summary>
    /// Determines whether the item is rendered like a tool while in the player's hand.
    /// </summary>
    [TraitProperty]
    public abstract bool Value { get; }
}
