// autogenerated by ingot
// log: resolved root oneOf -> object form (1 properties)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The hover_text_color component specifies the color of the item name when the players hovers the cursor over the item.
/// </summary>
[Trait("minecraft:hover_text_color", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IHoverTextColor : IItemTrait
{
    /// <summary>
    /// Specifies the color of the item&apos;s hover text.
    /// </summary>
    [TraitProperty]
    public abstract string Value { get; }
}
