// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_hover_text_color?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Determines the color of the item name when hovering over it.
/// </summary>
[Trait("minecraft:hover_text_color", TraitSystem.TraitType.Item)]
public interface IHoverTextColor : IItemTrait
{
    /// <summary>
    /// The color of the item hover text.
    /// </summary>
    [TraitProperty]
    public abstract string Value { get; }
}
