// autogenerated by ingot
// log: unable to resolve type object on property Textures

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// Icon item component determines which icon graphic will be used to represent the item in the UI and elsewhere.
/// </summary>
[Trait("minecraft:icon", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.60")]
public interface IIcon : IItemTrait
{
    /// <summary>
    /// This map contains the different textures that can be used for the item's icon. Default will contain the actual icon texture. Armor trim textures and palettes can be specified here too. The icon textures are the keys from the resource_pack/textures/item_texture.json 'texture_data' object associated with the texture file.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Textures => null;
}
