// autogenerated by ingot
// log: resolved root oneOf -> object form (1 properties)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Icon item component determines which icon graphic will be used to represent the item in the UI and elsewhere.
/// </summary>
[Trait("minecraft:icon", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.80")]
public interface IIcon : IItemTrait
{
    /// <summary>
    /// This map contains the different textures that can be used for the item&apos;s icon. Default will contain the actual icon texture. Armor trim textures and palettes and bundle open textures can be specified here too. The icon textures are the keys from the resource_pack/textures/item_texture.json &apos;texture_data&apos; object associated with the texture file.
    /// </summary>
    [TraitProperty]
    public virtual Dictionary<string, string>? Textures => null;
}
