// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_icon?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:icon", TraitSystem.TraitType.Item)]
public interface IIcon
{
    [TraitProperty]
    /* This map contains the different textures that can be used for the item's icon. */
    public abstract dynamic Textures { get; }
}
