// autogenerated by ingot
// log: resolved root oneOf -> synthetic value property
// log: multi-primitive oneOf on Value [boolean|string] -> object + Type constraint

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// This component is a boolean or string that determines if the interact button is shown in touch controls and what text is displayed on the button. When set as true, default &quot;Use Item&quot; text will be displayed.
/// </summary>
[Trait("minecraft:interact_button", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IInteractButton : IItemTrait
{
    /// <summary>
    /// This component is a boolean or string that determines if the interact button is shown in touch controls and what text is displayed on the button. When set as true, default &quot;Use Item&quot; text will be displayed.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Type, "boolean", "string")]
    public abstract object Value { get; }
}
