// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// This component is a boolean or string that determines if the interact button is shown in touch controls and what text is displayed on the button. When set as true, default "Use Item" text will be displayed.
/// </summary>
[Trait("minecraft:interact_button", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IInteractButton : IItemTrait
{
    /// <summary>
    /// Value of the component. <c>true</c> shows the default "Use Item" label; a string sets custom button text.
    /// </summary>
    [TraitProperty]
    public abstract Either<bool, string> Value { get; }
}
