// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_interact_button?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// A boolean or string that determines if the interact button is shown in touch controls, and what text is displayed on the button. When set to 'true', the default 'Use Item' text will be used.
/// </summary>
[Trait("minecraft:interact_button", TraitSystem.TraitType.Item)]
public interface IInteractButton : IItemTrait
{
}