// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_kinetic_weapon?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Allows an item to deal kinetic damage and its effects. This happens every tick while in use, in a straight line along the user's view vector, with damage computed based on both the user's and the target's velocity projected onto the view vector (via a dot product). The more the user and target move toward each other, and the more this movement is aligned with the user's view vector, the higher the damage. After "damage_multiplier" and "damage_modifier" are applied, the resulting damage is floored to the nearest lower integer.
/// </summary>
[Trait("minecraft:kinetic_weapon", TraitSystem.TraitType.Item)]
public interface IKineticWeapon : IItemTrait
{
    /// <summary>
    /// Defines the reach used when the user is in Creative Mode. Defaults to "reach" if unspecified.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? CreativeReach { get; }

    /// <summary>
    /// Conditions that need to be satisfied for damage to be applied. If not specified, damage is not applied.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? DamageConditions { get; }

    /// <summary>
    /// Value added to the the scaled dot product (after applying "damage_multiplier").
    /// </summary>
    [TraitProperty]
    public virtual float DamageModifier => 0f;

    /// <summary>
    /// Value multiplied to sum of the dot products of the user and target's velocity vectors projected onto the view vector.
    /// </summary>
    [TraitProperty]
    public virtual float DamageMultiplier => 1f;

    /// <summary>
    /// Time, in ticks, after which kinetic damage and its effects start being applied.
    /// </summary>
    [TraitProperty]
    public virtual int Delay => 0;

    /// <summary>
    /// Conditions that need to be satisfied for riders to be dismounted. If not specified, riders cannot be dismounted.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? DismountConditions { get; }

    /// <summary>
    /// Added tolerance to the view vector raycast for detecting entity collisions.
    /// </summary>
    [TraitProperty]
    public virtual float HitboxMargin => 0f;

    /// <summary>
    /// Conditions that need to be satisfied for knockback to be applied. If not specified, knockback is not applied.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? KnockbackConditions { get; }

    /// <summary>
    /// Defines the range (in blocks) along the user's view vector where entities can be hit.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Reach => null;
}