// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_kinetic_weapon?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:kinetic_weapon", TraitSystem.TraitType.Item)]
public interface IKineticWeapon : IItemTrait
{
    [TraitProperty]
    /* Defines the reach used when the user is in Creative Mode. Defaults to "reach" if unspecified. */
    public abstract dynamic CreativeReach { get; }

    [TraitProperty]
    /* Conditions that need to be satisfied for damage to be applied. If not specified, damage is not applied. */
    public abstract dynamic DamageConditions { get; }

    [TraitProperty]
    /* Value added to the the scaled dot product (after applying "damage_multiplier"). */
    public virtual float DamageModifier => 0f;

    [TraitProperty]
    /* Value multiplied to sum of the dot products of the user and target's velocity vectors projected onto the view vector. */
    public virtual float DamageMultiplier => 1f;

    [TraitProperty]
    /* Time, in ticks, after which kinetic damage and its effects start being applied. */
    public virtual int Delay => 0;

    [TraitProperty]
    /* Conditions that need to be satisfied for riders to be dismounted. If not specified, riders cannot be dismounted. */
    public abstract dynamic DismountConditions { get; }

    [TraitProperty]
    /* Added tolerance to the view vector raycast for detecting entity collisions. */
    public virtual float HitboxMargin => 0f;

    [TraitProperty]
    /* Conditions that need to be satisfied for knockback to be applied. If not specified, knockback is not applied. */
    public abstract dynamic KnockbackConditions { get; }

    [TraitProperty]
    /* Defines the range (in blocks) along the user's view vector where entities can be hit. */
    public virtual dynamic Reach => """{"max":3,"min":0}""";
}
