// autogenerated by ingot
// log: resolved root oneOf -> object form (1 properties)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The liquid_clipped component determines whether the item interacts with liquid blocks on use.
/// </summary>
[Trait("minecraft:liquid_clipped", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface ILiquidClipped : IItemTrait
{
    /// <summary>
    /// Deterines whether the item interacts with liquid blocks on use.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => false;
}
