// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_liquid_clipped?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:liquid_clipped", TraitSystem.TraitType.Item)]
public interface ILiquidClipped
{
    [TraitProperty]
    /* Deterines whether the item interacts with liquid blocks on use. */
    public abstract bool Value { get; }
}
