// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// The max_stack_size component specifies how many of the item can be stacked together.
/// </summary>
[Trait("minecraft:max_stack_size", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IMaxStackSize : IItemTrait
{
    /// <summary>
    /// Specifies how many of the item that can be stacked.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 1,64)]
    public virtual int Value => 1;
}
