// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_max_stack_size?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:max_stack_size", TraitSystem.TraitType.Item)]
public interface IMaxStackSize
{
    [TraitProperty]
    /* How many of an item that can be stacked together. */
    public virtual int Value => 64;
}
