// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_piercing_weapon?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:piercing_weapon", TraitSystem.TraitType.Item)]
public interface IPiercingWeapon : IItemTrait
{
    /// <summary>
    /// Defines the reach used when the user is in Creative Mode. Defaults to "reach" if unspecified.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? CreativeReach { get; }

    /// <summary>
    /// Added tolerance to the view vector raycast for detecting entity collisions.
    /// </summary>
    [TraitProperty]
    public virtual float HitboxMargin => 0f;

    /// <summary>
    /// Defines the range (in blocks) along the user's view vector where entities can be hit.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Reach => null;
}
