// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_piercing_weapon?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:piercing_weapon", TraitSystem.TraitType.Item)]
public interface IPiercingWeapon : IItemTrait
{
    [TraitProperty]
    /* Defines the reach used when the user is in Creative Mode. Defaults to "reach" if unspecified. */
    public abstract dynamic CreativeReach { get; }

    [TraitProperty]
    /* Added tolerance to the view vector raycast for detecting entity collisions. */
    public virtual float HitboxMargin => 0f;

    [TraitProperty]
    /* Defines the range (in blocks) along the user's view vector where entities can be hit. */
    public virtual dynamic Reach => """{"max":3,"min":0}""";
}
