// autogenerated by ingot
// log: unable to resolve type object on property CreativeReach
// log: unable to resolve type object on property Reach

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Allows an item to deal damage to all entities detected in a straight line along the user's view vector. Items with this component cannot destroy blocks, as the attack action always takes priority, regardless of what the user is looking at.
/// </summary>
[Trait("minecraft:piercing_weapon", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.90")]
public interface IPiercingWeapon : IItemTrait
{
    /// <summary>
    /// Defines the reach used when the user is in Creative Mode. Defaults to "reach" if unspecified.
    /// </summary>
    [TraitProperty]
    public abstract dynamic CreativeReach { get; }
    /// <summary>
    /// Added tolerance to the view vector raycast for detecting entity collisions.
    /// </summary>
    [TraitProperty]
    public virtual float HitboxMargin => 0;
    /// <summary>
    /// Defines the range (in blocks) along the user's view vector where entities can be hit. Only targets within this distance are considered. Block collisions between the user and target block damage and its effects.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Reach => null;
}
