// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.Common.SharedConstructs;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Allows an item to deal damage to all entities detected in a straight line along the user&apos;s view vector. Items with this component cannot destroy blocks, as the attack action always takes priority, regardless of what the user is looking at.
/// </summary>
[Trait("minecraft:piercing_weapon", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.90")]
public interface IPiercingWeapon : IItemTrait
{
    /// <summary>
    /// Defines the reach used when the user is in Creative Mode. Defaults to &quot;reach&quot; if unspecified.
    /// </summary>
    [TraitProperty]
    public virtual Range? CreativeReach => null;
    /// <summary>
    /// Added tolerance to the view vector raycast for detecting entity collisions.
    /// </summary>
    [TraitProperty]
    public virtual float HitboxMargin => 0f;
    /// <summary>
    /// Defines the range (in blocks) along the user&apos;s view vector where entities can be hit. Only targets within this distance are considered. Block collisions between the user and target block damage and its effects.
    /// </summary>
    [TraitProperty]
    public virtual Range? Reach => null;
}
