// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Projectile items shoot out, like an arrow.
/// </summary>
[Trait("minecraft:projectile", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IProjectile : IItemTrait
{
    /// <summary>
    /// Specifies how long a player must charge a projectile for it to critically hit.
    /// </summary>
    [TraitProperty]
    public virtual float MinimumCriticalPower => 0;
    /// <summary>
    /// Which entity is to be fired as a projectile.
    /// </summary>
    [TraitProperty]
    public abstract string ProjectileEntity { get; }
}
