// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_projectile?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:projectile", TraitSystem.TraitType.Item)]
public interface IProjectile : IItemTrait
{
    [TraitProperty]
    /* Specifies how long a player must charge a projectile for it to critically hit. */
    public virtual float MinimumCriticalPower => 0f;

    [TraitProperty]
    /* Which entity is to be fired as a projectile. Value must match a regular expression pattern of "^(?:\w+(?:.\w+):(?=\w))?(?:\w+(?:.\w+))(?:&lt;((?:\w+(?:.\w+):(?=\w))?\w+(?:.\w+))*&gt;)?$". */
    public abstract string ProjectileEntity { get; }
}
