// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Specifies the base rarity and subsequently color of the item name when the player hovers the cursor over the item.
/// </summary>
[Trait("minecraft:rarity", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.30")]
public interface IRarity : IItemTrait
{
    /// <summary>
    /// Sets the base rarity of the item. The rarity of an item automatically increases when enchanted, either to Rare when the base rarity is Common or Uncommon, or Epic when the base rarity is Rare.
    /// </summary>
    [TraitProperty]
    public abstract string Value { get; }
}
