// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_record?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:record", TraitSystem.TraitType.Item)]
public interface IRecord : IItemTrait
{
    [TraitProperty]
    /* Specifies signal strength for comparator blocks to use, from 1 - 13. */
    public virtual int ComparatorSignal => 1;

    [TraitProperty]
    /* Specifies duration of sound event in seconds, float value. */
    public virtual float Duration => 0f;

    [TraitProperty]
    /* Sound event type: 13, cat, blocks, chirp, far, mall, mellohi, stal, strad, ward, 11, wait, pigstep, otherside, 5, relic. */
    public virtual dynamic SoundEvent => """undefined""";
}
