// autogenerated by ingot
// log: generated subtype Repair (2 fields)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.Common.SharedConstructs;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using Newtonsoft.Json;
using Formatting = ingot.Core.Common.Formatting;

/// <summary>
/// The repairable item component specifies which items can be used to repair this item, along with how much durability is gained.
/// </summary>
[Trait("minecraft:repairable", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IRepairable : IItemTrait
{
    /// <summary>
    /// List of repair item entries. Each entry needs to define a list of strings for `items` that can be used for the repair and an optional `repair_amount` for how much durability is gained.
    /// </summary>
    [TraitProperty]
    public virtual Repair[] RepairItems => [];
}

/// <summary>
/// Repair
/// </summary>
public class Repair : ICompilableFragment
{
    /// <summary>
    /// Items that may be used to repair an item.
    /// </summary>
    public required ItemTypeDescriptor[] Items;
    /// <summary>
    /// How much the item is repaired.
    /// </summary>
    public object? RepairAmount = null;

    /// <inheritdoc/>
    public void Compile(ref JsonTextWriter writer)
    {
        JsonHelper json = new(ref writer);
        json.Object("", () =>
        {
            json.Property(Formatting.PascalToSnakeCase(nameof(Items)), Items);
            json.Property(Formatting.PascalToSnakeCase(nameof(RepairAmount)), RepairAmount);
        });
    }
}
