// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_seed?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Sets the item as a seed that can be planted to grow crops. When used on valid ground, the seed will place the specified crop block.
/// </summary>
[Trait("minecraft:seed", TraitSystem.TraitType.Item)]
public interface ISeed : IItemTrait
{
    /// <summary>
    /// The block identifier that will be placed when the seed is planted (e.g., 'wheat', 'beetroot', 'cave_vines').
    /// </summary>
    [TraitProperty]
    public abstract string CropResult { get; }

    /// <summary>
    /// Array of block identifiers that this seed can be planted on or attached to. If not specified, standard farmland rules apply.
    /// </summary>
    [TraitProperty]
    public abstract string[] PlantAt { get; }
}