// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_should_despawn?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

using ingot.Core.Common;

/// <summary>
/// Should_despawn component determines if the item should eventually despawn while floating in the world.
/// </summary>
[Trait("minecraft:should_despawn", TraitSystem.TraitType.Item)]
public interface IShouldDespawn : IItemTrait
{
    /// <summary>
    /// Determines whether the item should eventually despawn while floating in the world.
    /// </summary>
    [TraitProperty]
    public abstract bool Value { get; }
}