// autogenerated by ingot
// log: generated subtype Ammunition (4 fields)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.Common.SharedConstructs;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using Newtonsoft.Json;
using Formatting = ingot.Core.Common.Formatting;

/// <summary>
/// Shooter Item Component.
/// </summary>
[Trait("minecraft:shooter", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IShooter : IItemTrait
{
    /// <summary>
    /// Ammunition.
    /// </summary>
    [TraitProperty]
    public virtual Ammunition[] Ammunition => [];
    /// <summary>
    /// Charge on draw? Default is set to false.
    /// </summary>
    [TraitProperty]
    public virtual bool ChargeOnDraw => false;
    /// <summary>
    /// Draw Duration. Default is set to 0.
    /// </summary>
    [TraitProperty]
    public virtual float MaxDrawDuration => 0f;
    /// <summary>
    /// Scale power by draw duration? Default is set to false.
    /// </summary>
    [TraitProperty]
    public virtual bool ScalePowerByDrawDuration => false;
}

/// <summary>
/// Ammunition
/// </summary>
public class Ammunition : ICompilableFragment
{
    /// <summary>
    /// Ammunition item description identifier.
    /// </summary>
    public required ItemTypeDescriptor Item;
    /// <summary>
    /// Can search inventory? Default is set to false.
    /// </summary>
    public bool SearchInventory = false;
    /// <summary>
    /// Can use in creative mode? Default is set to false.
    /// </summary>
    public bool UseInCreative = false;
    /// <summary>
    /// Can use off-hand? Default is set to false.
    /// </summary>
    public bool UseOffhand = false;

    /// <inheritdoc/>
    public void Compile(ref JsonTextWriter writer)
    {
        JsonHelper json = new(ref writer);
        json.Object("", () =>
        {
            json.Property(Formatting.PascalToSnakeCase(nameof(Item)), Item);
            json.Property(Formatting.PascalToSnakeCase(nameof(SearchInventory)), SearchInventory);
            json.Property(Formatting.PascalToSnakeCase(nameof(UseInCreative)), UseInCreative);
            json.Property(Formatting.PascalToSnakeCase(nameof(UseOffhand)), UseOffhand);
        });
    }
}
