// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Should_despawn component determines if the item should eventually despawn while floating in the world
/// </summary>
[Trait("minecraft:should_despawn", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IShouldDespawn : IItemTrait
{
    /// <summary>
    /// Determines whether the item should eventually despawn while floating in the world.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => false;
}
