// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_shooter?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

/// <summary>
/// Compels an item to shoot projectiles, similarly to a bow or crossbow. Must have the minecraft:use_modifiers component in order to function properly.
/// </summary>
[Trait("minecraft:shooter", TraitSystem.TraitType.Item)]
public interface IShooter : IItemTrait
{
    /// <summary>
    /// A list of ammunition entries that define which items can be used as projectiles for this shooter.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Ammunition => null;

    /// <summary>
    /// When true, the shooter begins charging when the player starts drawing, similar to a crossbow. Default is false.
    /// </summary>
    [TraitProperty]
    public virtual bool ChargeOnDraw => false;

    /// <summary>
    /// The maximum time in seconds that a player can draw the shooter before it automatically fires or reaches maximum power. Default is 0.
    /// </summary>
    [TraitProperty]
    public virtual float MaxDrawDuration => 0f;

    /// <summary>
    /// When true, the projectile's launch power increases based on how long the player holds the use button before releasing. Default is false.
    /// </summary>
    [TraitProperty]
    public virtual bool ScalePowerByDrawDuration => false;
}
