// autogenerated by ingot
// log: resolved root oneOf -> object form (1 properties)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// The stacked_by_data component determines whether the same items with different aux values can stack. Also defines whether the item entities can merge while floating in the world.
/// </summary>
[Trait("minecraft:stacked_by_data", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IStackedByData : IItemTrait
{
    /// <summary>
    /// Determines whether the same item with different aux values can stack. Also defines whether the item entities can merge while floating in the world.
    /// </summary>
    [TraitProperty]
    public virtual bool Value => false;
}
