// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_storage_item?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:storage_item", TraitSystem.TraitType.Item)]
public interface IStorageItem : IItemTrait
{
    /// <summary>
    /// Determines whether another Storage Item is allowed inside of this item. Default is true.
    /// </summary>
    [TraitProperty]
    public virtual bool AllowNestedStorageItems => true;

    /// <summary>
    /// List of items that are exclusively allowed in this Storage Item. If empty all items are allowed.
    /// </summary>
    [TraitProperty]
    public virtual string AllowedItems => "[]";

    /// <summary>
    /// List of items that are not allowed in this Storage Item.
    /// </summary>
    [TraitProperty]
    public virtual string BannedItems => "[]";

    /// <summary>
    /// The maximum allowed weight of the sum of all contained items. Maximum is 64. Default is 64. Value must be &lt;= 64.
    /// </summary>
    [TraitProperty]
    public virtual int MaxSlots => 64;
}
