// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_storage_item?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:storage_item", TraitSystem.TraitType.Item)]
public interface IStorageItem
{
    [TraitProperty]
    /* Determines whether another Storage Item is allowed inside of this item. Default is true. */
    public virtual bool AllowNestedStorageItems => true;

    [TraitProperty]
    /* List of items that are exclusively allowed in this Storage Item. If empty all items are allowed. */
    public virtual string AllowedItems => "[]";

    [TraitProperty]
    /* List of items that are not allowed in this Storage Item. */
    public virtual string BannedItems => "[]";

    [TraitProperty]
    /* The maximum allowed weight of the sum of all contained items. Maximum is 64. Default is 64. Value must be &lt;= 64. */
    public virtual int MaxSlots => 64;
}
