// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// Specifies the maximum weight limit that a storage item can hold
/// </summary>
[Trait("minecraft:storage_weight_modifier", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.60")]
public interface IStorageWeightModifier : IItemTrait
{
    /// <summary>
    /// The weight of this item when inside another Storage Item. Default is 4. 0 means item is not allowed in another Storage Item.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.GreaterThanEq, 0)]
    public virtual int WeightInStorageItem => 4;
}
