// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Specifies the maximum weight limit that a storage item can hold
/// </summary>
[Trait("minecraft:storage_weight_limit", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.60")]
public interface IStorageWeightLimit : IItemTrait
{
    /// <summary>
    /// The maximum allowed weight of the sum of all contained items. Maximum is 64. Default is 64.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.LessThanEq, 64)]
    public virtual int MaxWeightLimit => 64;
}
