// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_storage_weight_modifier?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:storage_weight_modifier", TraitSystem.TraitType.Item)]
public interface IStorageWeightModifier : IItemTrait
{
    /// <summary>
    /// The weight of this item when inside another Storage Item. Default is 4. 0 means item is not allowed in another Storage Item.
    /// </summary>
    [TraitProperty]
    public virtual int WeightInStorageItem => 4;
}
