// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_storage_weight_limit?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:storage_weight_limit", TraitSystem.TraitType.Item)]
public interface IStorageWeightLimit : IItemTrait
{
    /// <summary>
    /// The maximum allowed weight of the sum of all contained items. Maximum is 64. Default is 64. Value must be &lt;= 64.
    /// </summary>
    [TraitProperty]
    public virtual int MaxWeightLimit => 64;
}
