// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Duration, in seconds, of the item&apos;s swing animation played when mining or attacking. Affects visuals only and does not impact attack frequency or other gameplay mechanics.
/// </summary>
[Trait("minecraft:swing_duration", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.90")]
public interface ISwingDuration : IItemTrait
{
    /// <summary>
    /// Duration, in seconds, of the item&apos;s swing animation played when mining or attacking. Affects visuals only and does not impact attack frequency or other gameplay mechanics.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.GreaterThanEq, 0)]
    public virtual float Value => 0.3f;
}
