// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_swing_duration?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:swing_duration", TraitSystem.TraitType.Item)]
public interface ISwingDuration : IItemTrait
{
    [TraitProperty]
    /* Duration, in seconds, of the item's swing animation played when mining or attacking. Affects visuals only and does not impact attack frequency or other gameplay mechanics. */
    public virtual float Value => 0.30000001192092896f;
}
