// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// Duration, in seconds, of the item's swing animation played when mining or attacking. Affects visuals only and does not impact attack frequency or other gameplay mechanics.
/// </summary>
[Trait("minecraft:swing_duration", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.90")]
public interface ISwingDuration : IItemTrait
{
    /// <summary>
    /// Duration, in seconds, of the item's swing animation played when mining or attacking. Affects visuals only and does not impact attack frequency or other gameplay mechanics.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 0.30000001192092896f;
}
