// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_swing_sounds?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:swing_sounds", TraitSystem.TraitType.Item)]
public interface ISwingSounds : IItemTrait
{
    [TraitProperty]
    /* Sound played when an attack hits and deals critical damage. */
    public abstract dynamic AttackCriticalHit { get; }

    [TraitProperty]
    /* Sound played when an attack hits. */
    public abstract dynamic AttackHit { get; }

    [TraitProperty]
    /* Sound played when an attack misses or deals no damage due to invulnerability. */
    public abstract dynamic AttackMiss { get; }
}
