// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Overrides the swing sounds emitted by the user.
/// </summary>
[Trait("minecraft:swing_sounds", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.0")]
public interface ISwingSounds : IItemTrait
{
    /// <summary>
    /// Sound played when an attack hits and deals critical damage.
    /// </summary>
    [TraitProperty]
    public abstract string AttackCriticalHit { get; }
    /// <summary>
    /// Sound played when an attack hits.
    /// </summary>
    [TraitProperty]
    public abstract string AttackHit { get; }
    /// <summary>
    /// Sound played when an attack misses or deals no damage due to invulnerability.
    /// </summary>
    [TraitProperty]
    public abstract string AttackMiss { get; }
}
