// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;
using ingot.Core.Common.SharedConstructs;
using Newtonsoft.Json;

/// <summary>
/// The tags component specifies which tags an item has on it.
/// </summary>
[Trait("minecraft:tags", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface ITags : IItemTrait
{
    /// <summary>
    /// An array that can contain multiple item tags.
    /// </summary>
    [TraitProperty]
    public virtual string[] Tags => [];
}
