// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_use_modifiers?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:use_modifiers", TraitSystem.TraitType.Item)]
public interface IUseModifiers : IItemTrait
{
    /// <summary>
    /// Whether vibrations are emitted when the item starts or stops being used.
    /// </summary>
    [TraitProperty]
    public virtual bool EmitVibrations => true;

    /// <summary>
    /// Multiplier applied to the player's movement speed while the item is in use. Value must be &lt;= 1.
    /// </summary>
    [TraitProperty]
    public abstract float MovementModifier { get; }

    /// <summary>
    /// Sound played when the item starts being used.
    /// </summary>
    [TraitProperty]
    public abstract dynamic? StartSound { get; }

    /// <summary>
    /// Controls how using the item triggers start using behavior. "if_first" only starts if no other component has started using yet; "always" always restarts using. Defaults to "if_first".
    /// </summary>
    [TraitProperty]
    public virtual dynamic? StartUsing => null;

    /// <summary>
    /// Time, in seconds, that the item takes to use.
    /// </summary>
    [TraitProperty]
    public virtual float UseDuration => 0f;
}
