// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_use_animation?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:use_animation", TraitSystem.TraitType.Item)]
public interface IUseAnimation : IItemTrait
{
    [TraitProperty]
    /* Specifies which animation to play when the item is used. */
    public abstract string Value { get; }
}
