// autogenerated by ingot
// log: resolved root oneOf -> object form (1 properties)

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Use_animation specifies which animation is played when the player uses the item.
/// </summary>
[Trait("minecraft:use_animation", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.20.50")]
public interface IUseAnimation : IItemTrait
{
    /// <summary>Equivalent to <c>none</c></summary>
    public const string Animation_None = "none";
    /// <summary>Equivalent to <c>eat</c></summary>
    public const string Animation_Eat = "eat";
    /// <summary>Equivalent to <c>drink</c></summary>
    public const string Animation_Drink = "drink";
    /// <summary>Equivalent to <c>block</c></summary>
    public const string Animation_Block = "block";
    /// <summary>Equivalent to <c>bow</c></summary>
    public const string Animation_Bow = "bow";
    /// <summary>Equivalent to <c>camera</c></summary>
    public const string Animation_Camera = "camera";
    /// <summary>Equivalent to <c>crossbow</c></summary>
    public const string Animation_Crossbow = "crossbow";
    /// <summary>Equivalent to <c>spear</c></summary>
    public const string Animation_Spear = "spear";
    /// <summary>Equivalent to <c>spyglass</c></summary>
    public const string Animation_Spyglass = "spyglass";
    /// <summary>Equivalent to <c>brush</c></summary>
    public const string Animation_Brush = "brush";
    /// <summary>
    /// Specifies which animation to play when the the item is used.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "none","eat","drink","block","bow","camera","crossbow","spear","spyglass","brush")]
    public virtual string? Value => "none";
}
