// autogenerated by ingot

namespace ingot.Core.TraitSystem.Traits.Item;
using ingot.Core.Common;
using ingot.Core.TraitSystem;
using ingot.Core.TraitSystem.Traits;

/// <summary>
/// Modifies use behavior, including how long the item takes to use and the player&apos;s movement speed.
/// </summary>
[Trait("minecraft:use_modifiers", TraitSystem.TraitType.Item)]
[TraitFormatVersion("1.21.0")]
public interface IUseModifiers : IItemTrait
{
    /// <summary>Equivalent to <c>if_first</c></summary>
    public const string StartUsing_IfFirst = "if_first";
    /// <summary>Equivalent to <c>always</c></summary>
    public const string StartUsing_Always = "always";
    /// <summary>
    /// Whether vibrations are emitted when the item starts or stops being used.
    /// </summary>
    [TraitProperty]
    public virtual bool EmitVibrations => true;
    /// <summary>
    /// Multiplier applied to the player&apos;s movement speed while the item is in use.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.Range, 0,1)]
    public abstract float MovementModifier { get; }
    /// <summary>
    /// Sound played when the item starts being used. Accepts a sound event name string.
    /// </summary>
    [TraitProperty]
    public abstract string StartSound { get; }
    /// <summary>
    /// Controls how using the item triggers start using behavior. &quot;if_first&quot; only starts if no other component has started using yet; &quot;always&quot; always restarts using. Defaults to &quot;if_first&quot;.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.OneOf, "if_first","always")]
    public virtual string? StartUsing => "if_first";
    /// <summary>
    /// Time, in seconds, that the item takes to use.
    /// </summary>
    [TraitProperty]
    [TraitPropertyConstraint(TraitPropertyConstraintAttribute.Constraint.GreaterThanEq, 0)]
    public virtual float UseDuration => 0f;
}
