// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_use_animation?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;
using System.Numerics;
using System.Collections.Generic;
using ingot.Core.Common;

[Trait("minecraft:use_animation", TraitSystem.TraitType.Item)]
public interface IUseAnimation : IItemTrait
{
    /// <summary>
    /// Specifies which animation to play when the item is used.
    /// </summary>
    [TraitProperty]
    public abstract string Value { get; }
}
