// autogenerated from 
//https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_wearable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Item;

[Trait("minecraft:wearable", TraitSystem.TraitType.Item)]
public interface IWearable
{
    [TraitProperty]
    /* Determines whether the Player's location is hidden on Locator Maps and the Locator Bar when the wearable item is worn. Default is false. */
    public virtual bool HidesPlayerLocation => false;

    [TraitProperty]
    /* How much protection the wearable item provides. Default is set to 0. */
    public virtual int Protection => 0;

    [TraitProperty]
    /* Specifies where the item can be worn. If any non-hand slot is chosen, the max stack size is set to 1. */
    public abstract dynamic Slot { get; }

    [TraitProperty]
    public abstract bool Dispensable { get; }
}
