// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_addrider?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Adds a rider to the entity.
/// </summary>
[Trait("minecraft:addrider", TraitSystem.TraitType.Entity)]
public interface IAddrider : IEntityTrait
{
    /// <summary>
    /// Type of entity to acquire as a rider
    /// </summary>
    [TraitProperty]
    public abstract string EntityType { get; }

    /// <summary>
    /// List of riders to be added to the entity. Can only spawn as many riders as "minecraft:rideable" has "seat_count".
    /// </summary>
    [TraitProperty]
    public virtual EntityRider[] Riders => [];

    /// <summary>
    /// Trigger event when a rider is acquired
    /// </summary>
    [TraitProperty]
    public abstract Identifier SpawnEvent { get; }
}
