// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_ambient_sound_interval?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Delay for an entity playing its sound.
/// </summary>
[Trait("minecraft:ambient_sound_interval", TraitSystem.TraitType.Entity)]
public interface IAmbientSoundInterval : IEntityTrait
{
    /// <summary>
    /// Level sound event to be played as the ambient sound.
    /// </summary>
    [TraitProperty]
    public virtual string EventName => "ambient";

    /// <summary>
    /// List of dynamic level sound events, with conditions for choosing between them. Evaluated in order, first one wins. If none evaluate to true, 'event_name' will take precedence.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? EventNames => null;

    /// <summary>
    /// Maximum time in seconds to randomly add to the ambient sound delay time.
    /// </summary>
    [TraitProperty]
    public virtual float Range => 16f;

    /// <summary>
    /// Minimum time in seconds before the entity plays its ambient sound again.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 8f;
}
