// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_apply_knockback_rules?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines how an entity applies knockback.
/// </summary>
[Trait("minecraft:apply_knockback_rules", TraitSystem.TraitType.Entity)]
public interface IApplyKnockbackRules : IEntityTrait
{
    /// <summary>
    /// Array of rules instances defining how knockback should be applied to the entity.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Presets => null;
}
