// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_area_attack?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// A component that does damage to entities that get within range.
/// </summary>
[Trait("minecraft:area_attack", TraitSystem.TraitType.Entity)]
public interface IAreaAttack : IEntityTrait
{
    /// <summary>
    /// The type of damage that is applied to entities that enter the damage range.
    /// </summary>
    [TraitProperty]
    public virtual string? Cause => null;

    /// <summary>
    /// Attack cooldown (in seconds) for how often this entity can attack a target.
    /// </summary>
    [TraitProperty]
    public virtual float DamageCooldown => 0f;

    /// <summary>
    /// How much damage per tick is applied to entities that enter the damage range.
    /// </summary>
    [TraitProperty]
    public virtual int DamagePerTick => 2;

    /// <summary>
    /// How close a hostile entity must be to have the damage applied.
    /// </summary>
    [TraitProperty]
    public virtual float DamageRange => 0.2f;

    /// <summary>
    /// A localization key to use as the death message when the area attack kills an entity. If empty, the default death message for the damage cause is used.
    /// </summary>
    [TraitProperty]
    public virtual string? DeathMessageOverride => null;

    /// <summary>
    /// The set of entities that are valid to apply the damage to when within range.
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? EntityFilter => null;

    /// <summary>
    /// If the entity should play their attack sound when attacking a target.
    /// </summary>
    [TraitProperty]
    public virtual bool PlayAttackSound => true;

    /// <summary>
    /// Whether the entity is treated as the source of the area damage.
    /// </summary>
    [TraitProperty]
    public virtual bool UseSelfAsDamageSource => true;
}
