// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_balloonable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to have a balloon attached and defines the conditions and events for this entity when is ballooned.
/// </summary>
[Trait("minecraft:balloonable", TraitSystem.TraitType.Entity)]
public interface IBalloonable : IEntityTrait
{
    /// <summary>
    /// Mass that this entity will have when computing balloon pull forces.
    /// </summary>
    [TraitProperty]
    public virtual float Mass => 1f;

    /// <summary>
    /// Distance in blocks at which the balloon breaks.
    /// </summary>
    [TraitProperty]
    public virtual float MaxDistance => 10f;

    /// <summary>
    /// Event to call when this entity is ballooned.
    /// </summary>
    [TraitProperty]
    public abstract EntityEventTrigger OnBalloon { get; }

    /// <summary>
    /// Event to call when this entity is unballooned.
    /// </summary>
    [TraitProperty]
    public abstract EntityEventTrigger OnUnballoon { get; }

    /// <summary>
    /// Distance in blocks at which the 'spring' effect that lifts it.
    /// </summary>
    [TraitProperty]
    public virtual float SoftDistance => 2f;
}
