// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_barter?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Enables the component to drop an item as a barter exchange.
/// </summary>
[Trait("minecraft:barter", TraitSystem.TraitType.Entity)]
public interface IBarter : IEntityTrait
{
    /// <summary>
    /// Loot table that's used to drop a random item.
    /// </summary>
    [TraitProperty]
    public abstract string BarterTable { get; }

    /// <summary>
    /// Duration, in seconds, for which mob won't barter items if it was hurt.
    /// </summary>
    [TraitProperty]
    public virtual int CooldownAfterBeingAttacked => 0;
}
