// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_body_rotation_blocked?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// When set, the entity will no longer visually rotate their body to match their facing direction.
/// </summary>
[Trait("minecraft:body_rotation_blocked", TraitSystem.TraitType.Entity)]
public interface IBodyRotationBlocked : IEntityTrait
{
}
