// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_body_rotation_always_follows_head?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Causes the entity's body rotation to match the one of their head. Does not override the "minecraft:body_rotation_blocked" component.
/// </summary>
[Trait("minecraft:body_rotation_always_follows_head", TraitSystem.TraitType.Entity)]
public interface IBodyRotationAlwaysFollowsHead : IEntityTrait
{
}
