// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_boostable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the conditions and behavior of a rideable entity's boost.
/// </summary>
[Trait("minecraft:boostable", TraitSystem.TraitType.Entity)]
public interface IBoostable : IEntityTrait
{
    /// <summary>
    /// List of items that can be used to boost while riding this entity.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? BoostItems => null;

    /// <summary>
    /// Time in seconds for the boost.
    /// </summary>
    [TraitProperty]
    public virtual float Duration => 3f;

    /// <summary>
    /// Factor by which the entity's normal speed increases. E.g. 2.0 means go twice as fast.
    /// </summary>
    [TraitProperty]
    public virtual float SpeedMultiplier => 1f;
}
