// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_boss?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the current state of the boss for updating the boss HUD.
/// </summary>
[Trait("minecraft:boss", TraitSystem.TraitType.Entity)]
public interface IBoss : IEntityTrait
{
    /// <summary>
    /// The max distance from the boss at which the boss's health bar is present on the players screen.
    /// </summary>
    [TraitProperty]
    public virtual int HudRange => 55;

    /// <summary>
    /// The name that will be displayed above the boss's health bar.
    /// </summary>
    [TraitProperty]
    public virtual string Name => "55";

    /// <summary>
    /// Whether the sky should darken in the presence of the boss.
    /// </summary>
    [TraitProperty]
    public virtual bool ShouldDarkenSky => false;
}
