// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_breathable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines what blocks this entity can breathe in and gives them the ability to suffocate.
/// </summary>
[Trait("minecraft:breathable", TraitSystem.TraitType.Entity)]
public interface IBreathable : IEntityTrait
{
    /// <summary>
    /// List of blocks this entity can breathe in, in addition to the selected items above.
    /// </summary>
    [TraitProperty]
    public abstract string[] BreatheBlocks { get; }

    /// <summary>
    /// If set, this entity can breathe in air.
    /// </summary>
    [TraitProperty]
    public virtual bool BreathesAir => true;

    /// <summary>
    /// If set, this entity can breathe in lava.
    /// </summary>
    [TraitProperty]
    public virtual bool BreathesLava => true;

    /// <summary>
    /// If set, this entity can breathe in solid blocks.
    /// </summary>
    [TraitProperty]
    public virtual bool BreathesSolids => false;

    /// <summary>
    /// If set, this entity can breathe in water.
    /// </summary>
    [TraitProperty]
    public virtual bool BreathesWater => false;

    /// <summary>
    /// If true, entities that only breathe water (for example, fish) will take dehydration damage when out of water. This item requires a format version of at least 1.21.130.
    /// </summary>
    [TraitProperty]
    public virtual bool CanDehydrate => false;

    /// <summary>
    /// If set, this entity will have visible bubbles while in water.
    /// </summary>
    [TraitProperty]
    public virtual bool GeneratesBubbles => true;

    /// <summary>
    /// Time in seconds to recover breath to maximum.
    /// </summary>
    [TraitProperty]
    public virtual float InhaleTime => 0f;

    /// <summary>
    /// List of blocks this entity cannot breathe in, in addition to the selected items above.
    /// </summary>
    [TraitProperty]
    public abstract string[] NonBreatheBlocks { get; }

    /// <summary>
    /// Time in seconds between suffocation damage.
    /// </summary>
    [TraitProperty]
    public virtual int SuffocateTime => -20;

    [TraitProperty]
    public abstract float Suffocatetime { get; }

    /// <summary>
    /// Time in seconds the entity can hold its breath.
    /// </summary>
    [TraitProperty]
    public virtual int TotalSupply => 15;

    [TraitProperty]
    public abstract float Totalsupply { get; }
}
