// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_breedable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to establish a way to get into the love state used for breeding.
/// </summary>
[Trait("minecraft:breedable", TraitSystem.TraitType.Entity)]
public interface IBreedable : IEntityTrait
{
    /// <summary>
    /// If true, entities can breed while sitting
    /// </summary>
    [TraitProperty]
    public virtual bool AllowSitting => false;

    /// <summary>
    /// If true, the entities will blend their attributes in the offspring after they breed. For example, horses blend their health, movement, and jump_strength in their offspring.
    /// Moved/removed on current entity schemas; omitted by default.
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual bool BlendAttributes => true;

    /// <summary>
    /// Time in seconds before the Entity can breed again.
    /// </summary>
    [TraitProperty]
    public virtual float BreedCooldown => 60f;

    /// <summary>
    /// The list of items that can be used to get the entity into the 'love' state. Can be a single item or an array.
    /// </summary>
    [TraitProperty]
    public abstract Either<string, string[]> BreedItems { get; }

    /// <summary>
    /// The entity definitions that this entity can breed with. Can be a single object or an array.
    /// </summary>
    [TraitProperty]
    public abstract Either<Dictionary<string, object>, Dictionary<string, object>[]> BreedsWith { get; }

    /// <summary>
    /// If true, the entity will become pregnant instead of spawning a baby.
    /// </summary>
    [TraitProperty]
    public virtual bool CausesPregnancy => false;

    /// <summary>
    /// If true and no color mutation occurs, the baby's minecraft:color is set to a blend of the parents' colors (following DyeItem combination rules).
    /// Omitted by default (not valid on current entity schemas).
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual bool CombineParentColors => false;

    /// <summary>
    /// Determines how likely the baby of parents with the same variant will deny that variant and take a random variant within the given range instead.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? DenyParentsVariant => null;

    /// <summary>
    /// The list of nearby block requirements to get the entity into the 'love' state.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? EnvironmentRequirements => null;

    /// <summary>
    /// Chance that up to 16 babies will spawn.
    /// </summary>
    [TraitProperty]
    public virtual dynamic ExtraBabyChance => null;

    /// <summary>
    /// If true, the babies will be automatically tamed if its parents are.
    /// Omitted by default (not valid on current entity schemas; use offspring for inheritance).
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual bool InheritTamed => true;

    /// <summary>
    /// The filters to run when attempting to fall in love.
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? LoveFilters => null;

    /// <summary>
    /// Determines how likely the babies are to NOT inherit one of their parent's variances.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? MutationFactor => null;

    /// <summary>
    /// If true, the entity needs to be at full health before it can breed.
    /// </summary>
    [TraitProperty]
    public virtual bool RequireFullHealth => false;

    /// <summary>
    /// If true, the entities need to be tamed first before they can breed.
    /// </summary>
    [TraitProperty]
    public virtual bool RequireTame => true;
}
