// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_buoyant?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Enables an entity to float on the specified liquid blocks.
/// </summary>
[Trait("minecraft:buoyant", TraitSystem.TraitType.Entity)]
public interface IBuoyant : IEntityTrait
{
    /// <summary>
    /// Applies gravity each tick. Causes "movement_type" to be more impactful, but also gravity to be applied more intensely outside liquids.
    /// </summary>
    [TraitProperty]
    public virtual bool ApplyGravity => true;

    /// <summary>
    /// Base buoyancy used to calculate how much will a entity float.
    /// </summary>
    [TraitProperty]
    public virtual float BaseBuoyancy => 1f;

    /// <summary>
    /// Probability for a big wave hitting the entity. Only used if "movement_type" is "waves".
    /// </summary>
    [TraitProperty]
    public virtual float BigWaveProbability => 0.03f;

    /// <summary>
    /// Multiplier for the speed to make a big wave. Triggered depending on "big_wave_probability".
    /// </summary>
    [TraitProperty]
    public virtual float BigWaveSpeed => 10f;

    /// <summary>
    /// Whether the entity can step out of a liquid block onto a neighboring solid block when pushed against it. This item requires a format version of at least 1.26.10.
    /// </summary>
    [TraitProperty]
    public virtual bool CanAutoStepFromLiquid => false;

    /// <summary>
    /// How much an entity will be dragged down when the component is removed.
    /// </summary>
    [TraitProperty]
    public virtual float DragDownOnBuoyancyRemoved => 0f;

    /// <summary>
    /// List of blocks this entity can float on. Must be a liquid block.
    /// </summary>
    [TraitProperty]
    public virtual string[]? LiquidBlocks => null;

    /// <summary>
    /// Type of vertical movement applied to the entity.
    /// </summary>
    [TraitProperty]
    public virtual string MovementType => "waves";
}
