// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_burns_in_daylight?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Specifies that this entity takes fire damage when exposed to direct sunlight. This component is used by undead mobs like zombies, skeletons, and phantoms. The entity will catch fire when in sunlight unless it is wearing armor in the protection slot, standing in water, or in a shaded area.
/// </summary>
[Trait("minecraft:burns_in_daylight", TraitSystem.TraitType.Entity)]
public interface IBurnsInDaylight : IEntityTrait
{
    /// <summary>
    /// The equipment slot that provides protection from burning in sunlight.
    /// </summary>
    [TraitProperty]
    public virtual dynamic ProtectionSlot => null;
}
