// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_can_power_jump?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the entity to power jump like the Horse does in Vanilla.
/// </summary>
[Trait("minecraft:can_power_jump", TraitSystem.TraitType.Entity)]
public interface ICanPowerJump : IEntityTrait
{
}
