// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_celebrate_hunt?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Specifies hunt celebration behaviour.
/// </summary>
[Trait("minecraft:celebrate_hunt", TraitSystem.TraitType.Entity)]
public interface ICelebrateHunt : IEntityTrait
{
    /// <summary>
    /// If true, celebration will be broadcasted to other entities in the radius.
    /// </summary>
    [TraitProperty]
    public virtual bool Broadcast => true;

    /// <summary>
    /// The list of conditions that target of hunt must satisfy to initiate celebration.
    /// </summary>
    [TraitProperty]
    public abstract EntityFilter CeleberationTargets { get; }

    /// <summary>
    /// The sound event to play when the mob is celebrating
    /// </summary>
    [TraitProperty]
    public abstract string CelebrateSound { get; }

    /// <summary>
    /// Duration, in seconds, of celebration
    /// </summary>
    [TraitProperty]
    public virtual int Duration => 4;

    /// <summary>
    /// If broadcast is enabled, specifies the radius in which it will notify other entities for celebration.
    /// </summary>
    [TraitProperty]
    public virtual float Radius => 16f;

    /// <summary>
    /// The range of time in seconds to randomly wait before playing the sound again
    /// </summary>
    [TraitProperty]
    public virtual int SoundInterval => 0;
}
