// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_color2?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's second texture color.
/// </summary>
[Trait("minecraft:color2", TraitSystem.TraitType.Entity)]
public interface IColor2 : IEntityTrait
{
    /// <summary>
    /// The second Palette Color value of the entity.
    /// </summary>
    [TraitProperty]
    public virtual int Value => 0;
}
