// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_collision_box?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets the width and height of the Entity's collision box.
/// </summary>
[Trait("minecraft:collision_box", TraitSystem.TraitType.Entity)]
public interface ICollisionBox : IEntityTrait
{
    /// <summary>
    /// Height of the collision box in blocks. A negative value will be assumed to be 0.
    /// </summary>
    [TraitProperty]
    public virtual float Height => 1f;

    /// <summary>
    /// Width of the collision box in blocks. A negative value will be assumed to be 0. Min value is -100000000.000000 Max value is 100000000.000000
    /// </summary>
    [TraitProperty]
    public virtual float Width => 1f;
}
