// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_combat_regeneration?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Gives Regeneration I and removes Mining Fatigue from the mob that kills the entity's attack target.
/// </summary>
[Trait("minecraft:combat_regeneration", TraitSystem.TraitType.Entity)]
public interface ICombatRegeneration : IEntityTrait
{
    /// <summary>
    /// Determines if the mob will grant mobs of the same type combat buffs if they kill the target.
    /// </summary>
    [TraitProperty]
    public virtual bool ApplyToFamily => false;

    /// <summary>
    /// Determines if the mob will grant itself the combat buffs if it kills the target.
    /// </summary>
    [TraitProperty]
    public virtual bool ApplyToSelf => false;

    /// <summary>
    /// The duration in seconds of Regeneration I added to the mob. Can also be set to "infinite"
    /// </summary>
    [TraitProperty]
    public virtual int RegenerationDuration => 5;
}
