// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_custom_hit_test?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// List of hitboxes for melee and ranged hits against the entity.
/// </summary>
[Trait("minecraft:custom_hit_test", TraitSystem.TraitType.Entity)]
public interface ICustomHitTest : IEntityTrait
{
    /// <summary>
    /// List of hitboxes for melee and ranged hits against the entity.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Hitboxes => null;
}
