// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_damage_sensor?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines what events to call when this entity is damaged by specific entities or items.
/// </summary>
[Trait("minecraft:damage_sensor", TraitSystem.TraitType.Entity)]
public interface IDamageSensor : IEntityTrait
{
    [TraitProperty]
    public virtual bool DealsDamage => false;

    /// <summary>
    /// List of triggers with the events to call when taking specific kinds of damage.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Triggers => null;
}
