// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_damage_over_time?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Applies defined amount of damage to the entity at specified intervals.
/// </summary>
[Trait("minecraft:damage_over_time", TraitSystem.TraitType.Entity)]
public interface IDamageOverTime : IEntityTrait
{
    /// <summary>
    /// Amount of damage caused each hurt.
    /// </summary>
    [TraitProperty]
    public virtual int DamagePerHurt => 1;

    /// <summary>
    /// Time in seconds between damage.
    /// </summary>
    [TraitProperty]
    public virtual float TimeBetweenHurt => 0f;
}
