// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_dash_action?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Ability for a rideable entity to dash.
/// </summary>
[Trait("minecraft:dash_action", TraitSystem.TraitType.Entity)]
public interface IDashAction : IEntityTrait
{
    /// <summary>
    /// Whether the entity can dash underwater. Default value is false.
    /// </summary>
    [TraitProperty]
    public virtual bool CanDashUnderwater => false;

    /// <summary>
    /// The dash cooldown in seconds. Default value is 1.000000.
    /// </summary>
    [TraitProperty]
    public virtual float CooldownTime => 1f;

    /// <summary>
    /// Should the momentum be applied in the direction of the 'entity' or 'passenger'.
    /// </summary>
    [TraitProperty]
    public virtual string Direction => "entity";

    /// <summary>
    /// Horizontal momentum of the dash.
    /// </summary>
    [TraitProperty]
    public virtual float HorizontalMomentum => 1f;

    /// <summary>
    /// Vertical momentum of the dash.
    /// </summary>
    [TraitProperty]
    public virtual float VerticalMomentum => 1f;
}
