// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_default_look_angle?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets this entity's default head rotation angle.
/// </summary>
[Trait("minecraft:default_look_angle", TraitSystem.TraitType.Entity)]
public interface IDefaultLookAngle : IEntityTrait
{
    /// <summary>
    /// Angle in degrees.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 0f;
}
