// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_despawn?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Despawns the Actor when the despawn rules or optional filters evaluate to true.
/// </summary>
[Trait("minecraft:despawn", TraitSystem.TraitType.Entity)]
public interface IDespawn : IEntityTrait
{
    /// <summary>
    /// Determines if "min_range_random_chance" is used in the standard despawn rules
    /// </summary>
    [TraitProperty]
    public virtual bool DespawnFromChance => true;

    /// <summary>
    /// Specifies if the 'min_distance' and 'max_distance' are used in the standard despawn rules.
    /// </summary>
    [TraitProperty]
    public abstract dynamic DespawnFromDistance { get; }

    /// <summary>
    /// Determines if the "min_range_inactivity_timer" is used in the standard despawn rules.
    /// </summary>
    [TraitProperty]
    public virtual bool DespawnFromInactivity => true;

    /// <summary>
    /// Determines if the mob is instantly despawned at the edge of simulation distance in the standard despawn rules.
    /// </summary>
    [TraitProperty]
    public virtual bool DespawnFromSimulationEdge => true;

    /// <summary>
    /// The list of conditions that must be satisfied before the Actor is despawned. If a filter is defined then standard despawn rules are ignored.
    /// </summary>
    [TraitProperty]
    public abstract EntityFilter Filters { get; }

    /// <summary>
    /// The amount of time in seconds that the mob must be inactive.
    /// </summary>
    [TraitProperty]
    public virtual int MinRangeInactivityTimer => 30;

    /// <summary>
    /// A random chance between 1 and the given value.
    /// </summary>
    [TraitProperty]
    public virtual int MinRangeRandomChance => 800;

    /// <summary>
    /// If true, all entities linked to this entity in a child relationship (eg. leashed) will also be despawned.
    /// </summary>
    [TraitProperty]
    public virtual bool RemoveChildEntities => false;
}
