// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_equipment?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets the Equipment table to use for this Entity.
/// </summary>
[Trait("minecraft:equipment", TraitSystem.TraitType.Entity)]
public interface IEquipment : IEntityTrait
{
    /// <summary>
    /// A list of slots with the chance to drop an equipped item from that slot. Can be an array of slot name strings or an array of objects with slot and drop_chance properties.
    /// </summary>
    [TraitProperty]
    public abstract string[] SlotDropChance { get; }

    /// <summary>
    /// The file path to the equipment table, relative to the behavior pack's root.
    /// </summary>
    [TraitProperty]
    public abstract string Table { get; }
}
