// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_equip_item?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// The entity puts on the desired equipment.
/// </summary>
[Trait("minecraft:equip_item", TraitSystem.TraitType.Entity)]
public interface IEquipItem : IEntityTrait
{
    /// <summary>
    /// If true, the entity can pick up and wear armor items from the ground.
    /// </summary>
    [TraitProperty]
    public virtual bool CanWearArmor => false;

    /// <summary>
    /// List of items that the entity should not equip.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? ExcludedItems => null;
}
