// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_exhaustion_values?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines how much exhaustion each player action should take.
/// </summary>
[Trait("minecraft:exhaustion_values", TraitSystem.TraitType.Entity)]
public interface IExhaustionValues : IEntityTrait
{
    /// <summary>
    /// Amount of exhaustion applied when attacking.
    /// </summary>
    [TraitProperty]
    public virtual float Attack => 0.1f;

    /// <summary>
    /// Amount of exhaustion applied when taking damage.
    /// </summary>
    [TraitProperty]
    public virtual float Damage => 0.1f;

    /// <summary>
    /// Amount of exhaustion applied when healed through food regeneration.
    /// </summary>
    [TraitProperty]
    public virtual float Heal => 6f;

    /// <summary>
    /// Amount of exhaustion applied when jumping.
    /// </summary>
    [TraitProperty]
    public virtual float Jump => 0.05f;

    /// <summary>
    /// Amount of exhaustion applied when triggering the Lunge enchantment, multiplied by the enchantment level. This item requires a format version of at least 1.21.130.
    /// </summary>
    [TraitProperty]
    public virtual float Lunge => 4f;

    /// <summary>
    /// Amount of exhaustion applied when mining.
    /// </summary>
    [TraitProperty]
    public virtual float Mine => 0.005f;

    /// <summary>
    /// Amount of exhaustion applied when sprinting.
    /// </summary>
    [TraitProperty]
    public virtual float Sprint => 0.01f;

    /// <summary>
    /// Amount of exhaustion applied when sprint jumping.
    /// </summary>
    [TraitProperty]
    public virtual float SprintJump => 0.2f;

    /// <summary>
    /// Amount of exhaustion applied when swimming.
    /// </summary>
    [TraitProperty]
    public virtual float Swim => 0.01f;

    /// <summary>
    /// Amount of exhaustion applied when walking.
    /// </summary>
    [TraitProperty]
    public virtual float Walk => 0f;
}
