// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_experience_reward?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// .
/// </summary>
[Trait("minecraft:experience_reward", TraitSystem.TraitType.Entity)]
public interface IExperienceReward : IEntityTrait
{
    [TraitProperty]
    public abstract float OnBred { get; }

    [TraitProperty]
    public abstract float OnDeath { get; }
}
