// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_explode?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines how the entity explodes.
/// </summary>
[Trait("minecraft:explode", TraitSystem.TraitType.Entity)]
public interface IExplode : IEntityTrait
{
    [TraitProperty]
    public abstract dynamic Add { get; }

    /// <summary>
    /// If true, the explosion will affect blocks and entities under water. This item requires a format version of at least 1.21.40.
    /// </summary>
    [TraitProperty]
    public virtual bool AllowUnderwater => false;

    /// <summary>
    /// If true, the explosion will destroy blocks in the explosion radius.
    /// </summary>
    [TraitProperty]
    public virtual bool BreaksBlocks => true;

    /// <summary>
    /// If true, blocks in the explosion radius will be set on fire.
    /// </summary>
    [TraitProperty]
    public virtual bool CausesFire => false;

    /// <summary>
    /// A scale factor applied to the explosion's damage to entities.
    /// </summary>
    [TraitProperty]
    public virtual float DamageScaling => 1f;

    /// <summary>
    /// If true, whether the explosion breaks blocks is affected by the mob griefing game rule.
    /// </summary>
    [TraitProperty]
    public virtual bool DestroyAffectedByGriefing => false;

    /// <summary>
    /// If true, whether the explosion causes fire is affected by the mob griefing game rule.
    /// </summary>
    [TraitProperty]
    public virtual bool FireAffectedByGriefing => false;

    /// <summary>
    /// The range for the random amount of time the fuse will be lit before exploding, a negative value means the explosion will be immediate.
    /// </summary>
    [TraitProperty]
    public abstract int FuseLength { get; }

    /// <summary>
    /// If true, the fuse is already lit when this component is added to the entity.
    /// </summary>
    [TraitProperty]
    public virtual bool FuseLit => false;

    /// <summary>
    /// A scale factor applied to the knockback force caused by the explosion. This item requires a format version of at least 1.21.40.
    /// </summary>
    [TraitProperty]
    public virtual float KnockbackScaling => 1f;

    /// <summary>
    /// A blocks explosion resistance will be capped at this value when an explosion occurs.
    /// </summary>
    [TraitProperty]
    public virtual float MaxResistance => 3.40282e+38f;

    /// <summary>
    /// Defines whether the explosion should apply fall damage negation to Players above the point of collision. This item requires a format version of at least 1.21.40.
    /// </summary>
    [TraitProperty]
    public virtual bool NegatesFallDamage => false;

    /// <summary>
    /// The name of the particle effect to use. The accepted strings are 'explosion', 'wind_burst', or 'breeze_wind_burst'. This item requires a format version of at least 1.21.40.
    /// </summary>
    [TraitProperty]
    public virtual string ParticleEffect => "explosion";

    /// <summary>
    /// The radius of the explosion in blocks and the amount of damage the explosion deals.
    /// </summary>
    [TraitProperty]
    public virtual float Power => 3f;

    /// <summary>
    /// The name of the sound effect played when the explosion triggers. This item requires a format version of at least 1.21.40.
    /// </summary>
    [TraitProperty]
    public virtual string SoundEffect => "explode";

    /// <summary>
    /// If true, the explosion will toggle blocks in the explosion radius. This item requires a format version of at least 1.21.40.
    /// </summary>
    [TraitProperty]
    public virtual bool TogglesBlocks => false;
}
