// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_floats_in_liquid?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets that this entity can float in liquid blocks.
/// </summary>
[Trait("minecraft:floats_in_liquid", TraitSystem.TraitType.Entity)]
public interface IFloatsInLiquid : IEntityTrait
{
}
