// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_follow_range?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the maximum range, in blocks, that a mob will pursue a target. This affects AI behaviors like chasing players or attacking.
/// </summary>
[Trait("minecraft:follow_range", TraitSystem.TraitType.Entity)]
public interface IFollowRange : IEntityTrait
{
    /// <summary>
    /// Maximum follow distance in blocks. The entity will not pursue targets beyond this range.
    /// </summary>
    [TraitProperty]
    public abstract int Max { get; }

    /// <summary>
    /// The default follow range in blocks. Entities will attempt to stay within this radius of their target.
    /// </summary>
    [TraitProperty]
    public abstract int Value { get; }
}
