// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_free_camera_controlled?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// When configured as a rideable entity, the entity will be controlled using WASD controls and mouse to move in three dimensions.
/// </summary>
[Trait("minecraft:free_camera_controlled", TraitSystem.TraitType.Entity)]
public interface IFreeCameraControlled : IEntityTrait
{
    /// <summary>
    /// Modifies speed going backwards.
    /// </summary>
    [TraitProperty]
    public virtual float BackwardsMovementModifier => 0.5f;

    /// <summary>
    /// Modifies the strafe speed.
    /// </summary>
    [TraitProperty]
    public virtual float StrafeSpeedModifier => 0.4f;
}
