// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_friction_modifier?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines how much friction affects this entity.
/// </summary>
[Trait("minecraft:friction_modifier", TraitSystem.TraitType.Entity)]
public interface IFrictionModifier : IEntityTrait
{
    /// <summary>
    /// The higher the number, the more friction affects this entity. A value of 1.0 means regular friction, while 2.0 means twice as much.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 1f;
}
