// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_game_event_movement_tracking?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to emit entityMove, swim and flap game events, depending on the block the entity is moving through. It is added by default to every mob. Add it again to override its behavior.
/// </summary>
[Trait("minecraft:game_event_movement_tracking", TraitSystem.TraitType.Entity)]
public interface IGameEventMovementTracking : IEntityTrait
{
    /// <summary>
    /// If true, the flap game event will be emitted when the entity moves through air.
    /// </summary>
    [TraitProperty]
    public virtual bool EmitFlap => false;

    /// <summary>
    /// If true, the entityMove game event will be emitted when the entity moves on ground or through a solid.
    /// </summary>
    [TraitProperty]
    public virtual bool EmitMove => true;

    /// <summary>
    /// If true, the swim game event will be emitted when the entity moves through a liquid.
    /// </summary>
    [TraitProperty]
    public virtual bool EmitSwim => true;
}
