// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_genetics?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the way a mob's genes and alleles are passed on to its offspring, and how those traits manifest in the child. Compatible parent genes are crossed together, the alleles are handed down from the parents to the child, and any matching genetic variants fire off JSON events to modify the child and express the traits.
/// </summary>
[Trait("minecraft:genetics", TraitSystem.TraitType.Entity)]
public interface IGenetics : IEntityTrait
{
    /// <summary>
    /// The list of genes that this entity has and will cross with a partner during breeding.
    /// </summary>
    [TraitProperty]
    public abstract dynamic Genes { get; }

    /// <summary>
    /// Chance that an allele will be replaced with a random one instead of the parent's allele during birth.
    /// </summary>
    [TraitProperty]
    public virtual float MutationRate => 0.03125f;
}
