// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_giveable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines sets of items that can be used to trigger events when used on this entity. The item will also be taken and placed in the entity's inventory.
/// </summary>
[Trait("minecraft:giveable", TraitSystem.TraitType.Entity)]
public interface IGiveable : IEntityTrait
{
    /// <summary>
    /// An optional cool down in seconds to prevent spamming interactions.
    /// </summary>
    [TraitProperty]
    public virtual float Cooldown => 0f;

    /// <summary>
    /// The list of items that can be given to the entity to place in their inventory. Can be an array or a single item string.
    /// </summary>
    [TraitProperty]
    public abstract string[] Items { get; }

    [TraitProperty]
    public abstract string OnGive { get; }
}
