// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_ground_offset?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets the offset from the ground that the entity is actually at.
/// </summary>
[Trait("minecraft:ground_offset", TraitSystem.TraitType.Entity)]
public interface IGroundOffset : IEntityTrait
{
    /// <summary>
    /// The value of the entity's offset from the terrain, in blocks.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 0f;
}
