// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_healable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// How entities heal.
/// </summary>
[Trait("minecraft:healable", TraitSystem.TraitType.Entity)]
public interface IHealable : IEntityTrait
{
    /// <summary>
    /// The filter group that defines the conditions for using this item to heal the entity.
    /// </summary>
    [TraitProperty]
    public abstract EntityFilter Filters { get; }

    /// <summary>
    /// Determines if item can be used regardless of entity being at full health.
    /// </summary>
    [TraitProperty]
    public virtual bool ForceUse => false;

    /// <summary>
    /// The array of items that can be used to heal this entity.
    /// </summary>
    [TraitProperty]
    public abstract dynamic Items { get; }
}
