// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_heartbeat?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's heartbeat.
/// </summary>
[Trait("minecraft:heartbeat", TraitSystem.TraitType.Entity)]
public interface IHeartbeat : IEntityTrait
{
    /// <summary>
    /// A Molang expression defining the inter-beat interval in seconds. A value of zero or less means no heartbeat.
    /// </summary>
    [TraitProperty]
    public virtual string Interval => "1.00";

    /// <summary>
    /// Level sound event to be played as the heartbeat sound.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? SoundEvent => null;
}
