// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_home?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Saves a home position for when the entity is spawned. This component allows entities like bees to remember and return to a specific location such as a hive or nest.
/// </summary>
[Trait("minecraft:home", TraitSystem.TraitType.Entity)]
public interface IHome : IEntityTrait
{
    /// <summary>
    /// Optional list of blocks that can be considered a valid home.
    /// </summary>
    [TraitProperty]
    public abstract string[] HomeBlockList { get; }

    /// <summary>
    /// Optional radius that the entity will be restricted to in relation to its home.
    /// </summary>
    [TraitProperty]
    public virtual int RestrictionRadius => 0;

    /// <summary>
    /// Defines how the entity will be restricted to its home position.
    /// </summary>
    [TraitProperty]
    public virtual string RestrictionType => "none";
}
