// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_horse.jump_strength?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Determines the jump height for a horse or similar entity, like a donkey.
/// </summary>
[Trait("minecraft:horse.jump_strength", TraitSystem.TraitType.Entity)]
public interface IHorseJumpStrength : IEntityTrait
{
    [TraitProperty]
    public abstract float Value { get; }
}
