// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_hurt_on_condition?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines a set of conditions under which an entity should take damage.
/// </summary>
[Trait("minecraft:hurt_on_condition", TraitSystem.TraitType.Entity)]
public interface IHurtOnCondition : IEntityTrait
{
    /// <summary>
    /// List of damage conditions that when met can cause damage to the entity.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? DamageConditions => null;
}
