// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_ignore_cannot_be_attacked?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// When set, blocks entities from attacking the owner entity unless they have the "minecraft:ignore_cannot_be_attacked" component.
/// </summary>
[Trait("minecraft:ignore_cannot_be_attacked", TraitSystem.TraitType.Entity)]
public interface IIgnoreCannotBeAttacked : IEntityTrait
{
    /// <summary>
    /// Defines which entities are exceptions and are allowed to be attacked by the owner entity, potentially attacked entity is subject "other".
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? Filters => null;
}
