// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_inside_block_notifier?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Verifies whether the entity is inside any of the listed blocks.
/// </summary>
[Trait("minecraft:inside_block_notifier", TraitSystem.TraitType.Entity)]
public interface IInsideBlockNotifier : IEntityTrait
{
    /// <summary>
    /// List of blocks, with certain block states, that we are monitoring to see if the entity is inside.
    /// </summary>
    [TraitProperty]
    public abstract dynamic BlockList { get; }
}
