// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_interact?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines interactions with this entity.
/// </summary>
[Trait("minecraft:interact", TraitSystem.TraitType.Entity)]
public interface IInteract : IEntityTrait
{
    /// <summary>
    /// Per-interaction field; not valid at the root of <c>minecraft:interact</c>.
    /// Put cooldown on individual entries in <see cref="Interactions"/>.
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual float Cooldown => 0f;

    /// <summary>
    /// Per-interaction field; not valid at the root of <c>minecraft:interact</c>.
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual float CooldownAfterBeingAttacked => 0f;

    /// <summary>
    /// The entity's slot to remove and drop the item from, if any, upon successful interaction.
    /// </summary>
    [TraitProperty]
    public abstract string DropItemSlot { get; }

    /// <summary>
    /// Per-interaction field; not valid at the root of <c>minecraft:interact</c>.
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual float DropItemYOffset => 0f;

    /// <summary>
    /// The entity's slot to equip the item to, if any, upon successful interaction.
    /// </summary>
    [TraitProperty]
    public abstract string EquipItemSlot { get; }

    /// <summary>
    /// Per-interaction field; not valid at the root of <c>minecraft:interact</c>.
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual int HealthAmount => 0;

    /// <summary>
    /// Per-interaction field; not valid at the root of <c>minecraft:interact</c>.
    /// </summary>
    [TraitProperty]
    [IngotExclude]
    public virtual int HurtItem => 0;

    /// <summary>
    /// Text to show when the player is able to interact in this way with this entity when playing with touch-screen controls.
    /// </summary>
    [TraitProperty]
    public abstract string InteractText { get; }

    /// <summary>
    /// The list of interactions for this entity.
    /// </summary>
    [TraitProperty]
    public abstract dynamic Interactions { get; }
}
