// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_is_baby?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets that this entity is a baby. This is used to set the is_baby value for use in query functions like Molang and Filters.
/// </summary>
[Trait("minecraft:is_baby", TraitSystem.TraitType.Entity)]
public interface IIsBaby : IEntityTrait
{
}
