// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_is_charged?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets that this entity is charged. This is used to set the is_charged value for use in query functions like Molang and Filters.
/// </summary>
[Trait("minecraft:is_charged", TraitSystem.TraitType.Entity)]
public interface IIsCharged : IEntityTrait
{
}
