// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_is_dyeable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows dyes to be used on this entity to change its color.
/// </summary>
[Trait("minecraft:is_dyeable", TraitSystem.TraitType.Entity)]
public interface IIsDyeable : IEntityTrait
{
    /// <summary>
    /// The text that will display when interacting with this entity with a dye when playing with Touch-screen controls.
    /// </summary>
    [TraitProperty]
    public virtual string? InteractText => null;
}
