// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_is_hidden_when_invisible?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// The entity can hide from hostile mobs while invisible.
/// </summary>
[Trait("minecraft:is_hidden_when_invisible", TraitSystem.TraitType.Entity)]
public interface IIsHiddenWhenInvisible : IEntityTrait
{
}
