// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_is_illager_captain?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets that this entity is an Illager Captain.
/// </summary>
[Trait("minecraft:is_illager_captain", TraitSystem.TraitType.Entity)]
public interface IIsIllagerCaptain : IEntityTrait
{
}
