// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_is_tamed?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets that this entity is currently tamed.
/// </summary>
[Trait("minecraft:is_tamed", TraitSystem.TraitType.Entity)]
public interface IIsTamed : IEntityTrait
{
}
