// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_jump.dynamic?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines a dynamic type jump control that will change jump properties based on the speed modifier of the mob.Requires minecraft:movement.skip to be used.
/// </summary>
[Trait("minecraft:jump.dynamic", TraitSystem.TraitType.Entity)]
public interface IJumpDynamic : IEntityTrait
{
    /// <summary>
    /// Jump data used while traveling quickly with skip movement. Object with the same shape as regular_skip_data. This item requires a format version of at least 1.26.0.
    /// </summary>
    [TraitProperty]
    public virtual dynamic FastSkipData => null;

    /// <summary>
    /// Jump data used during normal skip movement.
    /// </summary>
    [TraitProperty]
    public virtual dynamic RegularSkipData => null;
}
