// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_jump.static?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Gives the entity the ability to jump.
/// </summary>
[Trait("minecraft:jump.static", TraitSystem.TraitType.Entity)]
public interface IJumpStatic : IEntityTrait
{
    /// <summary>
    /// The initial vertical velocity for the jump.
    /// </summary>
    [TraitProperty]
    public virtual float JumpPower => 0.41999998688697815f;
}
