// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_knockback_resistance?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Determines an entity's resistance to knockback from melee attacks. A value of 0.0 means no resistance, while 1.0 provides full immunity to knockback (like iron golems).
/// </summary>
[Trait("minecraft:knockback_resistance", TraitSystem.TraitType.Entity)]
public interface IKnockbackResistance : IEntityTrait
{
    /// <summary>
    /// Maximum potential knockback resistance for this entity.
    /// </summary>
    [TraitProperty]
    public abstract float Max { get; }

    /// <summary>
    /// The amount of knockback resistance, from 0.0 (none) to 1.0 (full immunity).
    /// </summary>
    [TraitProperty]
    public abstract float Value { get; }
}
