// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_lava_movement?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows a custom movement speed across lava blocks.
/// </summary>
[Trait("minecraft:lava_movement", TraitSystem.TraitType.Entity)]
public interface ILavaMovement : IEntityTrait
{
    /// <summary>
    /// The speed the mob moves over a lava block.
    /// </summary>
    [TraitProperty]
    public abstract float Value { get; }
}
