// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_leashable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Describes how this mob can be leashed to other items.
/// </summary>
[Trait("minecraft:leashable", TraitSystem.TraitType.Entity)]
public interface ILeashable : IEntityTrait
{
    /// <summary>
    /// If true, players can cut both incoming and outgoing leashes by using shears on the entity. This item requires a format version of at least 1.21.90.
    /// </summary>
    [TraitProperty]
    public virtual bool CanBeCut => true;

    /// <summary>
    /// If true, players can leash this entity even if it is already leashed to another entity.
    /// </summary>
    [TraitProperty]
    public virtual bool CanBeStolen => false;

    /// <summary>
    /// Distance in blocks at which the leash stiffens, restricting movement.
    /// </summary>
    [TraitProperty]
    public virtual int HardDistance => 6;

    /// <summary>
    /// Distance in blocks it which the leash breaks.
    /// </summary>
    [TraitProperty]
    public virtual int MaxDistance => 0;

    [TraitProperty]
    public abstract string OnLeash { get; }

    [TraitProperty]
    public abstract string OnUnleash { get; }

    /// <summary>
    /// When set to true, "on_unleash" does not trigger when the entity gets unleashed for reasons other than the player directly interacting with it.
    /// </summary>
    [TraitProperty]
    public virtual bool OnUnleashInteractOnly => false;

    /// <summary>
    /// Defines how this entity behaves when leashed to another entity. The first preset which "filter" conditions are met will be applied; if none match, a default configuration is used instead.
    /// </summary>
    [TraitProperty]
    public abstract dynamic Presets { get; }

    /// <summary>
    /// Distance in blocks at which the 'spring' effect starts acting to keep this entity close to the entity that leashed it.
    /// </summary>
    [TraitProperty]
    public virtual int SoftDistance => 4;

    /// <summary>
    /// If true, the entity is unleashed when this component is removed. Defaults to true. This item requires a format version of at least 1.26.30.
    /// </summary>
    [TraitProperty]
    public virtual bool UnleashOnRemoval => true;
}
