// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_loot?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Specifies the loot table that determines what items this entity drops upon death. The table path is relative to the behavior pack's root folder.
/// </summary>
[Trait("minecraft:loot", TraitSystem.TraitType.Entity)]
public interface ILoot : IEntityTrait
{
    /// <summary>
    /// Path to the loot table JSON file, relative to the behavior pack's root (e.g., 'loot_tables/entities/zombie.json').
    /// </summary>
    [TraitProperty]
    public abstract string Table { get; }
}
