// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_looked_at?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the behavior when another entity looks at the owner entity.
/// </summary>
[Trait("minecraft:looked_at", TraitSystem.TraitType.Entity)]
public interface ILookedAt : IEntityTrait
{
    /// <summary>
    /// Defines, in degrees, the width of the field of view for entities looking at the owner entity.
    /// </summary>
    [TraitProperty]
    public virtual float FieldOfView => 26f;

    /// <summary>
    /// Defines which entities are considered when searching for entities looking at the owner entity.
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? Filters => null;

    /// <summary>
    /// Limits the search to only the nearest Player that meets the specified "filters" rather than all nearby entities.
    /// </summary>
    [TraitProperty]
    public virtual bool FindPlayersOnly => false;

    /// <summary>
    /// Defines the type of block shape used to check for line of sight obstructions. Valid values: "outline", "collision", "collision_for_camera".
    /// </summary>
    [TraitProperty]
    public virtual string LineOfSightObstructionType => "collision";

    /// <summary>
    /// A list of locations on the owner entity towards which line of sight checks are performed. At least one location must be unobstructed for the entity to be considered as looked at.
    /// </summary>
    [TraitProperty]
    public virtual string[]? LookAtLocations => null;

    /// <summary>
    /// Specifies the range for the random number of seconds that must pass before the owner entity can check again for entities looking at it, after detecting an entity looking at it.
    /// </summary>
    [TraitProperty]
    public abstract int LookedAtCooldown { get; }

    /// <summary>
    /// Defines the event to trigger when an entity is detected looking at the owner entity.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? LookedAtEvent => null;

    /// <summary>
    /// Defines the minimum, continuous time the owner entity has to be looked at before being considered as such. Defaults to 0 if not explicitly specified.
    /// </summary>
    [TraitProperty]
    public virtual float MinLookedAtDuration => 0f;

    /// <summary>
    /// Defines the event to trigger when no entity is found looking at the owner entity.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? NotLookedAtEvent => null;

    /// <summary>
    /// When true, the field of view narrows as the distance between the owner entity and the entity looking at it increases.
    /// </summary>
    [TraitProperty]
    public virtual bool ScaleFovByDistance => true;

    /// <summary>
    /// Maximum distance the owner entity will search for entities looking at it.
    /// </summary>
    [TraitProperty]
    public virtual float SearchRadius => 10f;

    /// <summary>
    /// Set to true/false for legacy boolean targeting behavior.
    /// </summary>
    [TraitProperty]
    public abstract int SetTarget { get; }
}
