// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_managed_wandering_trader?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Manages the entity's ability to trade.
/// </summary>
[Trait("minecraft:managed_wandering_trader", TraitSystem.TraitType.Entity)]
public interface IManagedWanderingTrader : IEntityTrait
{
}
