// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_mark_variant?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Mark Variant is typically used as an additional per-type way (besides variant) to express a different visual form of the same mob.
/// </summary>
[Trait("minecraft:mark_variant", TraitSystem.TraitType.Entity)]
public interface IMarkVariant : IEntityTrait
{
    /// <summary>
    /// The Id of the mark_variant. By convention, 0 is the Id of the base entity.
    /// </summary>
    [TraitProperty]
    public virtual int Value => 0;
}
