// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_mob_effect_immunity?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Entities with this component will have an immunity to the provided mob effects.
/// </summary>
[Trait("minecraft:mob_effect_immunity", TraitSystem.TraitType.Entity)]
public interface IMobEffectImmunity : IEntityTrait
{
    /// <summary>
    /// List of names of effects the entity is immune to.
    /// </summary>
    [TraitProperty]
    public abstract string[] MobEffects { get; }
}
