// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_movement.jump?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Move control that causes the mob to jump as it moves with a specified delay between jumps.
/// </summary>
[Trait("minecraft:movement.jump", TraitSystem.TraitType.Entity)]
public interface IMovementJump : IEntityTrait
{
    /// <summary>
    /// Delay in seconds after landing when using the slime move control. Can be a single number, an array [min, max], or an object with range_min and range_max.
    /// </summary>
    [TraitProperty]
    public virtual FloatRange? JumpDelay => null;

    /// <summary>
    /// The maximum number in degrees the mob can turn per tick.
    /// </summary>
    [TraitProperty]
    public virtual float MaxTurn => 30f;
}
