// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_movement?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the base movement speed of an entity. Typical values: creeper (0.2), cow (0.25), zombie baby (0.35).
/// </summary>
[Trait("minecraft:movement", TraitSystem.TraitType.Entity)]
public interface IMovement : IEntityTrait
{
    /// <summary>
    /// The base movement speed value. Higher values result in faster movement. Can be a single number or a range object with range_min and range_max properties.
    /// </summary>
    [TraitProperty]
    public abstract Either<float, FloatRange> Value { get; }

    /// <summary>
    /// Maximum movement speed this entity can have. Defaults to <see cref="Value"/>.
    /// </summary>
    [TraitProperty]
    public virtual float Max => Value.Value is FloatRange range ? range.RangeMax : Convert.ToSingle(Value.Value);
}
