// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_movement.basic?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// This component accents the movement of an entity.
/// </summary>
[Trait("minecraft:movement.basic", TraitSystem.TraitType.Entity)]
public interface IMovementBasic : IEntityTrait
{
    /// <summary>
    /// The maximum number in degrees the mob can turn per tick.
    /// </summary>
    [TraitProperty]
    public virtual float MaxTurn => 30f;
}
