// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_navigation.generic?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to generate paths by walking, swimming, flying and/or climbing around and jumping up and down a block.
/// </summary>
[Trait("minecraft:navigation.generic", TraitSystem.TraitType.Entity)]
public interface INavigationGeneric : IEntityTrait
{
    /// <summary>
    /// Tells the pathfinder to avoid blocks that cause damage when finding a path
    /// </summary>
    [TraitProperty]
    public virtual bool AvoidDamageBlocks => false;

    /// <summary>
    /// Tells the pathfinder to avoid portals (like nether portals) when finding a path
    /// </summary>
    [TraitProperty]
    public virtual bool AvoidPortals => false;

    /// <summary>
    /// Whether or not the pathfinder should avoid tiles that are exposed to the sun when creating paths
    /// </summary>
    [TraitProperty]
    public virtual bool AvoidSun => false;

    /// <summary>
    /// Tells the pathfinder to avoid water when creating a path
    /// </summary>
    [TraitProperty]
    public virtual bool AvoidWater => false;

    /// <summary>
    /// Tells the pathfinder which blocks to avoid when creating a path
    /// </summary>
    [TraitProperty]
    public abstract string[] BlocksToAvoid { get; }

    /// <summary>
    /// Tells the pathfinder whether or not it can jump out of water (like a dolphin)
    /// </summary>
    [TraitProperty]
    public virtual bool CanBreach => false;

    /// <summary>
    /// Tells the pathfinder that it can path through a closed door and break it
    /// </summary>
    [TraitProperty]
    public virtual bool CanBreakDoors => false;

    /// <summary>
    /// Tells the pathfinder whether or not it can jump up blocks
    /// </summary>
    [TraitProperty]
    public virtual bool CanJump => true;

    /// <summary>
    /// Tells the pathfinder that it can path through a closed door assuming the AI will open the door
    /// </summary>
    [TraitProperty]
    public virtual bool CanOpenDoors => false;

    /// <summary>
    /// Tells the pathfinder that it can path through a closed iron door assuming the AI will open the door
    /// </summary>
    [TraitProperty]
    public virtual bool CanOpenIronDoors => false;

    /// <summary>
    /// Whether a path can be created through a door
    /// </summary>
    [TraitProperty]
    public virtual bool CanPassDoors => true;

    /// <summary>
    /// Tells the pathfinder that it can start pathing when in the air
    /// </summary>
    [TraitProperty]
    public virtual bool CanPathFromAir => false;

    /// <summary>
    /// Tells the pathfinder whether or not it can travel on the surface of the lava
    /// </summary>
    [TraitProperty]
    public virtual bool CanPathOverLava => false;

    /// <summary>
    /// Tells the pathfinder whether or not it can travel on the surface of the water
    /// </summary>
    [TraitProperty]
    public virtual bool CanPathOverWater => false;

    /// <summary>
    /// Tells the pathfinder whether or not it will be pulled down by gravity while in water
    /// </summary>
    [TraitProperty]
    public virtual bool CanSink => true;

    /// <summary>
    /// Tells the pathfinder whether or not it can path anywhere through water and plays swimming animation along that path
    /// </summary>
    [TraitProperty]
    public virtual bool CanSwim => false;

    /// <summary>
    /// Tells the pathfinder whether or not it can walk on the ground outside water
    /// </summary>
    [TraitProperty]
    public virtual bool CanWalk => true;

    /// <summary>
    /// Tells the pathfinder whether or not it can travel in lava like walking on ground
    /// </summary>
    [TraitProperty]
    public virtual bool CanWalkInLava => false;

    /// <summary>
    /// Tells the pathfinder whether or not it can walk on the ground underwater
    /// </summary>
    [TraitProperty]
    public virtual bool IsAmphibious => false;

    [TraitProperty]
    public abstract string UsingDoorAnnotation { get; }
}
