// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_offspring?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the way an entity can create a born offspring.
/// </summary>
[Trait("minecraft:offspring", TraitSystem.TraitType.Entity)]
public interface IOffspring : IEntityTrait
{
    /// <summary>
    /// If true, the entities will blend their attributes in the offspring after they breed.
    /// </summary>
    [TraitProperty]
    public virtual bool BlendAttributes => true;

    /// <summary>
    /// Determines how likely the baby of parents with the same variant will deny that variant and take a random variant within the given range instead.
    /// </summary>
    [TraitProperty]
    public abstract dynamic DenyParentsVariant { get; }

    /// <summary>
    /// If true, the babies will be automatically tamed if its parents are
    /// </summary>
    [TraitProperty]
    public virtual bool InheritTamed => true;

    /// <summary>
    /// Determines how likely the babies are to NOT inherit one of their parent's variances. Values are between 0.0 and 1.0, with a higher number meaning more likely to mutate.
    /// </summary>
    [TraitProperty]
    public abstract dynamic MutationFactor { get; }

    /// <summary>
    /// The map of entity to offspring definitions that this entity can make offspring with
    /// (e.g. <c>{ "minecraft:cow": "minecraft:cow" }</c>).
    /// </summary>
    [TraitProperty]
    public abstract dynamic OffspringPairs { get; }

    /// <summary>
    /// List of attributes that should benefit from parent centric attribute blending. For example, horses blend their health, movement, and jump_strength in their offspring.
    /// </summary>
    [TraitProperty]
    public abstract string[] ParentCentricAttributeBlending { get; }

    /// <summary>
    /// Entity properties that should be inherited from the parent entities (map or list).
    /// </summary>
    [TraitProperty]
    public abstract dynamic PropertyInheritance { get; }

    /// <summary>
    /// Range used to determine random extra variant.
    /// </summary>
    [TraitProperty]
    public virtual int RandomExtraVariantMutationInterval => 0;

    /// <summary>
    /// Range used to determine random variant.
    /// </summary>
    [TraitProperty]
    public virtual int RandomVariantMutationInterval => 0;
}
