// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_out_of_control?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's 'out of control' state.
/// </summary>
[Trait("minecraft:out_of_control", TraitSystem.TraitType.Entity)]
public interface IOutOfControl : IEntityTrait
{
}
