// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_peek?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's 'peek' behavior, defining the events that should be called during it.
/// </summary>
[Trait("minecraft:peek", TraitSystem.TraitType.Entity)]
public interface IPeek : IEntityTrait
{
    /// <summary>
    /// Event to call when the entity is done peeking.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? OnClose => null;

    /// <summary>
    /// Event to call when the entity starts peeking.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? OnOpen => null;

    /// <summary>
    /// Event to call when the entity's target entity starts peeking.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? OnTargetOpen => null;
}
