// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_persistent?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines whether an entity should be persistent in the game world.
/// </summary>
[Trait("minecraft:persistent", TraitSystem.TraitType.Entity)]
public interface IPersistent : IEntityTrait
{
}
