// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_player.level?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the player's level.
/// </summary>
[Trait("minecraft:player.level", TraitSystem.TraitType.Entity)]
public interface IPlayerLevel : IEntityTrait
{
    /// <summary>
    /// The maximum player level value of the entity.
    /// </summary>
    [TraitProperty]
    public abstract int Max { get; }

    /// <summary>
    /// The initial value of the player level.
    /// </summary>
    [TraitProperty]
    public abstract int Value { get; }
}
