// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_player.exhaustion?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the player's exhaustion level.
/// </summary>
[Trait("minecraft:player.exhaustion", TraitSystem.TraitType.Entity)]
public interface IPlayerExhaustion : IEntityTrait
{
    /// <summary>
    /// A maximum value for a player's exhaustion.
    /// </summary>
    [TraitProperty]
    public abstract int Max { get; }

    /// <summary>
    /// The initial value of a player's exhaustion level.
    /// </summary>
    [TraitProperty]
    public abstract int Value { get; }
}
