// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_player.saturation?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the player's need for food.
/// </summary>
[Trait("minecraft:player.saturation", TraitSystem.TraitType.Entity)]
public interface IPlayerSaturation : IEntityTrait
{
    /// <summary>
    /// The maximum player saturation value.
    /// </summary>
    [TraitProperty]
    public abstract int Max { get; }

    /// <summary>
    /// The initial value of player saturation.
    /// </summary>
    [TraitProperty]
    public abstract int Value { get; }
}
