// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_preferred_path?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Specifies costing information for mobs that prefer to walk on preferred paths.
/// </summary>
[Trait("minecraft:preferred_path", TraitSystem.TraitType.Entity)]
public interface IPreferredPath : IEntityTrait
{
    /// <summary>
    /// Cost for non-preferred blocks
    /// </summary>
    [TraitProperty]
    public virtual float DefaultBlockCost => 0f;

    /// <summary>
    /// Added cost for jumping up a node
    /// </summary>
    [TraitProperty]
    public virtual int JumpCost => 0;

    /// <summary>
    /// Distance mob can fall without taking damage
    /// </summary>
    [TraitProperty]
    public virtual int MaxFallBlocks => 3;

    /// <summary>
    /// A list of block types with their associated pathfinding costs. Each entry specifies blocks and their cost value.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? PreferredPathBlocks => null;
}
