// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_projectile?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using System.Numerics;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Turns the entity into a projectile: a thrown or shot entity that flies along a ballistic arc and reacts when it impacts a block, a fluid, or another entity.
/// </summary>
[Trait("minecraft:projectile", TraitSystem.TraitType.Entity)]
public interface IProjectile : IEntityTrait
{
    /// <summary>
    /// Reference point on the shooter used to position the projectile at spawn: 0 = origin (feet), 1 = eye height, 2 = middle of the bounding box.
    /// </summary>
    [TraitProperty]
    public virtual int Anchor => 0;

    /// <summary>
    /// Additional upwards pitch (in degrees) applied to the shooter's aim direction at launch. Negative values aim downward.
    /// </summary>
    [TraitProperty]
    public virtual float AngleOffset => 0f;

    /// <summary>
    /// Determines whether the entity hit will be set on fire.
    /// </summary>
    [TraitProperty]
    public virtual bool CatchFire => false;

    /// <summary>
    /// If true, critical-hit particles are spawned on the projectile when it is struck.
    /// </summary>
    [TraitProperty]
    public virtual bool CritParticleOnHurt => false;

    /// <summary>
    /// If true, the projectile is removed from the world when struck.
    /// </summary>
    [TraitProperty]
    public virtual bool DestroyOnHurt => false;

    /// <summary>
    /// Downward acceleration (blocks per tick squared) applied each tick while in flight. Higher values make the projectile fall faster.
    /// </summary>
    [TraitProperty]
    public virtual float Gravity => 0.05f;

    /// <summary>
    /// Identifier of the sound to play when the projectile hits a block. Defaults to hit_sound when empty.
    /// </summary>
    [TraitProperty]
    public virtual string? HitGroundSound => null;

    /// <summary>
    /// If true, when the projectile hits a vehicle with at least one passenger, the on-hit behavior is applied to the passenger closest to the impact point instead of the vehicle itself.
    /// </summary>
    [TraitProperty]
    public virtual bool HitNearestPassenger => false;

    /// <summary>
    /// Identifier of the sound to play when the projectile hits an entity. Also used for block hits when hit_ground_sound is not specified.
    /// </summary>
    [TraitProperty]
    public virtual string? HitSound => null;

    /// <summary>
    /// If true, the projectile steers towards an active target while in flight.
    /// </summary>
    [TraitProperty]
    public virtual bool Homing => false;

    /// <summary>
    /// Array of entity identifiers that the projectile will pass through without registering a hit.
    /// </summary>
    [TraitProperty]
    public virtual string[]? IgnoredEntities => null;

    /// <summary>
    /// Fraction of the projectile's velocity preserved each tick while traveling through air. Values below 1.0 cause it to slow down over time.
    /// </summary>
    [TraitProperty]
    public virtual float Inertia => 0.99f;

    /// <summary>
    /// If true, the projectile is flagged as dangerous, affecting AI reactions and certain client-side behaviors.
    /// </summary>
    [TraitProperty]
    public virtual bool IsDangerous => false;

    /// <summary>
    /// If true, this projectile is not affected by outside forces such as friction and drag.
    /// </summary>
    [TraitProperty]
    public virtual bool IsolatedPhysics => true;

    /// <summary>
    /// If true, the projectile can channel a lightning bolt when it hits an entity during a thunderstorm.
    /// </summary>
    [TraitProperty]
    public virtual bool Lightning => false;

    /// <summary>
    /// Fraction of the projectile's velocity preserved each tick while traveling through a fluid.
    /// </summary>
    [TraitProperty]
    public virtual float LiquidInertia => 0.6f;

    /// <summary>
    /// If true, the projectile can hit more than one entity over the course of its flight; if false, it stops at the first entity it hits.
    /// </summary>
    [TraitProperty]
    public virtual bool MultipleTargets => true;

    /// <summary>
    /// Offset, relative to the anchor, at which the projectile is spawned when fired by the shooter.
    /// </summary>
    [TraitProperty]
    public virtual Vector3 Offset => new Vector3(0,0,0);

    /// <summary>
    /// Duration in seconds for which an entity set on fire by this projectile remains burning. Applied both by the legacy top-level catch_fire flag and by the catch_fire on-hit subcomponent.
    /// </summary>
    [TraitProperty]
    public virtual float OnFireTime => 5f;

    /// <summary>
    /// Map of on-hit subcomponents that drive what happens when the projectile impacts a block, fluid, or entity. Each key is a subcomponent name and its value is that subcomponent's configuration.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? OnHit => null;

    /// <summary>
    /// Number of ticks immediately after launch during which the projectile cannot hit its own shooter.
    /// </summary>
    [TraitProperty]
    public virtual int OwnerLaunchImmunityTicks => 5;

    /// <summary>
    /// Particle effect emitted at the impact location when the projectile hits something.
    /// </summary>
    [TraitProperty]
    public virtual string Particle => "iconcrack";

    /// <summary>
    /// Default potion aux value associated with the projectile.
    /// </summary>
    [TraitProperty]
    public virtual int PotionEffect => -1;

    /// <summary>
    /// Initial speed (in blocks per tick) at which the projectile is launched.
    /// </summary>
    [TraitProperty]
    public virtual float Power => 1.3f;

    /// <summary>
    /// Duration in seconds after launch during which the projectile cannot be reflected by being struck.
    /// </summary>
    [TraitProperty]
    public virtual float ReflectImmunity => 0f;

    /// <summary>
    /// If true, this projectile will be reflected back when hit by another projectile or by taking damage.
    /// </summary>
    [TraitProperty]
    public virtual bool ReflectOnHurt => false;

    /// <summary>
    /// Identifier of the sound to play when the projectile is fired.
    /// </summary>
    [TraitProperty]
    public virtual string? ShootSound => null;

    /// <summary>
    /// If true, the projectile is aimed at the shooter's current target (when one exists) rather than straight ahead.
    /// </summary>
    [TraitProperty]
    public virtual bool ShootTarget => true;

    /// <summary>
    /// If true, the projectile bounces off surfaces and entities on impact instead of stopping.
    /// </summary>
    [TraitProperty]
    public virtual bool ShouldBounce => false;

    /// <summary>
    /// Splash radius (in blocks) used when applying potion effects via the splash/lingering potion code path.
    /// </summary>
    [TraitProperty]
    public virtual float SplashRange => 4f;

    /// <summary>
    /// If true, the projectile has its velocity zeroed out when struck.
    /// </summary>
    [TraitProperty]
    public virtual bool StopOnHurt => false;

    /// <summary>
    /// Base inaccuracy added to the launch direction. The total inaccuracy is uncertainty_base - difficultyLevel * uncertainty_multiplier.
    /// </summary>
    [TraitProperty]
    public virtual float UncertaintyBase => 0f;

    /// <summary>
    /// Per-difficulty-level reduction in inaccuracy. See uncertainty_base for the full formula.
    /// </summary>
    [TraitProperty]
    public virtual float UncertaintyMultiplier => 0f;
}
