// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_push_through?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets the distance through which the entity can push through.
/// </summary>
[Trait("minecraft:push_through", TraitSystem.TraitType.Entity)]
public interface IPushThrough : IEntityTrait
{
    /// <summary>
    /// The value of the entity's push-through, in blocks.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 0f;
}
