// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_pushable_by_entity?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows an entity to be pushed by other entities.
/// </summary>
[Trait("minecraft:pushable_by_entity", TraitSystem.TraitType.Entity)]
public interface IPushableByEntity : IEntityTrait
{
    /// <summary>
    /// Defines how this entity behaves when pushed by another entity. The first preset whose "filter" conditions are met will be applied; if none match, a default configuration is used instead.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Presets => null;
}
