// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_rail_movement?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's movement on the rails. An entity with this component is only allowed to move on the rail.
/// </summary>
[Trait("minecraft:rail_movement", TraitSystem.TraitType.Entity)]
public interface IRailMovement : IEntityTrait
{
    /// <summary>
    /// Maximum speed that this entity will move at when on the rail.
    /// </summary>
    [TraitProperty]
    public virtual float MaxSpeed => 0.4f;
}
