// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_rail_sensor?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Enables minecart-type entities to detect powered rails and respond to activation state changes. Triggers events when the entity passes over activated or deactivated rails, enabling custom minecart behaviors like launching at boosted speed, stopping at braking rails, or triggering special effects at detector rails.
/// </summary>
[Trait("minecraft:rail_sensor", TraitSystem.TraitType.Entity)]
public interface IRailSensor : IEntityTrait
{
    /// <summary>
    /// If true, on tick this entity will trigger its on_deactivate behavior
    /// </summary>
    [TraitProperty]
    public virtual bool CheckBlockTypes => false;

    /// <summary>
    /// If true, this entity will eject all of its riders when it passes over an activated rail
    /// </summary>
    [TraitProperty]
    public virtual bool EjectOnActivate => true;

    /// <summary>
    /// If true, this entity will eject all of its riders when it passes over a deactivated rail
    /// </summary>
    [TraitProperty]
    public virtual bool EjectOnDeactivate => false;

    /// <summary>
    /// Event to call when the rail is activated
    /// </summary>
    [TraitProperty]
    public abstract EntityEventTrigger OnActivate { get; }

    /// <summary>
    /// Event to call when the rail is deactivated
    /// </summary>
    [TraitProperty]
    public abstract EntityEventTrigger OnDeactivate { get; }

    /// <summary>
    /// If true, command blocks will start ticking when passing over an activated rail
    /// </summary>
    [TraitProperty]
    public virtual bool TickCommandBlockOnActivate => true;

    /// <summary>
    /// If false, command blocks will stop ticking when passing over a deactivated rail
    /// </summary>
    [TraitProperty]
    public virtual bool TickCommandBlockOnDeactivate => false;
}
