// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_ravager_blocked?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the ravager's response to their melee attack being blocked.
/// </summary>
[Trait("minecraft:ravager_blocked", TraitSystem.TraitType.Entity)]
public interface IRavagerBlocked : IEntityTrait
{
    /// <summary>
    /// The strength with which blocking entities should be knocked back
    /// </summary>
    [TraitProperty]
    public virtual float KnockbackStrength => 3f;

    /// <summary>
    /// A list of weighted responses to the melee attack being blocked
    /// </summary>
    [TraitProperty]
    public virtual string[] ReactionChoices => new[] { "[ ]" };
}
