// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_reflect_projectiles?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// [EXPERIMENTAL] Allows an entity to reflect projectiles.
/// </summary>
[Trait("minecraft:reflect_projectiles", TraitSystem.TraitType.Entity)]
public interface IReflectProjectiles : IEntityTrait
{
    /// <summary>
    /// [EXPERIMENTAL] A Molang expression defining the angle in degrees to add to the projectile's y axis rotation.
    /// </summary>
    [TraitProperty]
    public virtual string AzimuthAngle => "0";

    /// <summary>
    /// [EXPERIMENTAL] A Molang expression defining the angle in degrees to add to the projectile's x axis rotation.
    /// </summary>
    [TraitProperty]
    public virtual string ElevationAngle => "0";

    /// <summary>
    /// [EXPERIMENTAL] An array of strings defining the types of projectiles that are reflected when they hit the entity.
    /// </summary>
    [TraitProperty]
    public virtual string[]? ReflectedProjectiles => null;

    /// <summary>
    /// [EXPERIMENTAL] A Molang expression defining the velocity scaling of the reflected projectile. Values below 1 decrease the projectile's velocity, and values above 1 increase it.
    /// </summary>
    [TraitProperty]
    public virtual string ReflectionScale => "1";

    /// <summary>
    /// [EXPERIMENTAL] A string defining the name of the sound event to be played when a projectile is reflected. "reflect" unless specified.
    /// </summary>
    [TraitProperty]
    public virtual string ReflectionSound => "reflect";
}
