// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_rotation_locked_to_vehicle?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Causes the entity's rotation to match their vehicle's facing direction.
/// </summary>
[Trait("minecraft:rotation_locked_to_vehicle", TraitSystem.TraitType.Entity)]
public interface IRotationLockedToVehicle : IEntityTrait
{
}
