// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_scale?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets the entity's visual size multiplier. A value of 1.0 means normal size, 0.5 is half size (commonly used for baby mobs), and values above 1.0 make the entity larger.
/// </summary>
[Trait("minecraft:scale", TraitSystem.TraitType.Entity)]
public interface IScale : IEntityTrait
{
    /// <summary>
    /// The scale multiplier for visual size. 1.0 = normal, 0.5 = half (babies), 2.0 = double size.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 1f;
}
