// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_scale_by_age?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's size interpolation based on the entity's age.
/// </summary>
[Trait("minecraft:scale_by_age", TraitSystem.TraitType.Entity)]
public interface IScaleByAge : IEntityTrait
{
    /// <summary>
    /// Ending scale of the entity when it's fully grown.
    /// </summary>
    [TraitProperty]
    public virtual float EndScale => 1f;

    /// <summary>
    /// Initial scale of the newborn entity.
    /// </summary>
    [TraitProperty]
    public virtual float StartScale => 1f;
}
