// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_shooter?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's ranged attack behavior. The "minecraft:behavior.ranged_attack" goal uses this component to determine which projectiles to shoot.
/// </summary>
[Trait("minecraft:shooter", TraitSystem.TraitType.Entity)]
public interface IShooter : IEntityTrait
{
    /// <summary>
    /// ID of the Potion effect for the default projectile to be applied on hit.
    /// </summary>
    [TraitProperty]
    public virtual int AuxVal => -1;

    /// <summary>
    /// Actor definition to use as the default projectile for the ranged attack. The actor definition must have the projectile component to be able to be shot as a projectile.
    /// </summary>
    [TraitProperty]
    public virtual string? Def => null;

    /// <summary>
    /// If set, the projectiles are flagged as magic and the ranged attack goal will not run at the same time as other magic goals (for example, drink_potion).
    /// </summary>
    [TraitProperty]
    public virtual bool Magic => false;

    /// <summary>
    /// Velocity at which projectiles will be shot. A power of 0 falls back to the default projectile throw power. This item requires a format version of at least 1.19.60.
    /// </summary>
    [TraitProperty]
    public virtual float Power => 0f;

    /// <summary>
    /// List of projectiles that can be used by the shooter.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Projectiles => null;

    /// <summary>
    /// Sound that is played when the shooter shoots a projectile.
    /// </summary>
    [TraitProperty]
    public virtual string? Sound => null;
}
