// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_sittable?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's 'sit' state.
/// </summary>
[Trait("minecraft:sittable", TraitSystem.TraitType.Entity)]
public interface ISittable : IEntityTrait
{
    [TraitProperty]
    public virtual string? SitEvent => null;

    [TraitProperty]
    public virtual string? StandEvent => null;
}
