// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_skin_id?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Skin ID value. Can be used to differentiate skins, such as base skins for villagers.
/// </summary>
[Trait("minecraft:skin_id", TraitSystem.TraitType.Entity)]
public interface ISkinId : IEntityTrait
{
    /// <summary>
    /// The ID of the skin. By convention, 0 is the ID of the base skin.
    /// </summary>
    [TraitProperty]
    public virtual int Value => 0;
}
