// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_spawn_on_death?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Component for spawning entities when an entity perishes.
/// </summary>
[Trait("minecraft:spawn_on_death", TraitSystem.TraitType.Entity)]
public interface ISpawnOnDeath : IEntityTrait
{
    /// <summary>
    /// Additional random range of entities to spawn, defaults to 0, 0 when not set
    /// </summary>
    [TraitProperty]
    public virtual dynamic AdditionalSpawnRange => null;

    /// <summary>
    /// What entity to spawn, defaults to owning entity when not set
    /// </summary>
    [TraitProperty]
    public virtual string EntityToSpawn => "self";

    /// <summary>
    /// Conditions that need to be met for the behavior to start.
    /// </summary>
    [TraitProperty]
    public virtual dynamic Filters => null;

    /// <summary>
    /// If true, the entity will inherit the name of the parent entity, defaults to true when not set
    /// </summary>
    [TraitProperty]
    public virtual bool InheritParentName => true;

    /// <summary>
    /// How many entities to spawn, defaults to 1 when not set Value must be &gt; 0.
    /// </summary>
    [TraitProperty]
    public virtual int SpawnAmount => 1;

    /// <summary>
    /// Spawn method. born, spawned, or summoned, defaults to spawned when not set
    /// </summary>
    [TraitProperty]
    public virtual string SpawnMethod => "spawned";
}
