// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_spawn_entity?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Adds a timer after which this entity will spawn another entity or item (similar to vanilla's chicken's egg-laying behavior).
/// </summary>
[Trait("minecraft:spawn_entity", TraitSystem.TraitType.Entity)]
public interface ISpawnEntity : IEntityTrait
{
    /// <summary>
    /// List of entity spawn definitions. Can be a single object or an array of objects.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Entities => null;

    /// <summary>
    /// If present, the specified entity will only spawn if the filter evaluates to true.
    /// </summary>
    [TraitProperty]
    public virtual EntityFilter? Filters => null;

    /// <summary>
    /// Maximum amount of time to randomly wait in seconds before another entity is spawned.
    /// </summary>
    [TraitProperty]
    public virtual int MaxWaitTime => 600;

    /// <summary>
    /// Minimum amount of time to randomly wait in seconds before another entity is spawned.
    /// </summary>
    [TraitProperty]
    public virtual int MinWaitTime => 300;

    /// <summary>
    /// The number of entities of this type to spawn each time that this triggers.
    /// </summary>
    [TraitProperty]
    public virtual int NumToSpawn => 1;

    /// <summary>
    /// If true, this the spawned entity will be leashed to the parent.
    /// </summary>
    [TraitProperty]
    public virtual bool ShouldLeash => false;

    /// <summary>
    /// If true, this component will only ever spawn the specified entity once.
    /// </summary>
    [TraitProperty]
    public virtual bool SingleUse => false;

    /// <summary>
    /// Identifier of the entity to spawn, leave empty to spawn the item defined by "spawn_item" instead.
    /// </summary>
    [TraitProperty]
    public virtual string? SpawnEntity => null;

    /// <summary>
    /// Event to call on the spawned entity when it spawns.
    /// </summary>
    [TraitProperty]
    virtual EntityEventTrigger SpawnEvent => new EntityEventTrigger()
    {
        Event = "minecraft:entity_born", Filters = null,
    };

    /// <summary>
    /// Item identifier of the item to spawn.
    /// </summary>
    [TraitProperty]
    public virtual string SpawnItem => "egg";

    /// <summary>
    /// Event to call on this entity when the item is spawned.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? SpawnItemEvent => null;

    /// <summary>
    /// Method to use to spawn the entity.
    /// </summary>
    [TraitProperty]
    public virtual string SpawnMethod => "born";

    /// <summary>
    /// Identifier of the sound effect to play when the entity is spawned.
    /// </summary>
    [TraitProperty]
    public virtual string SpawnSound => "plop";
}
