// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_suspect_tracking?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows this entity to remember suspicious locations.
/// </summary>
[Trait("minecraft:suspect_tracking", TraitSystem.TraitType.Entity)]
public interface ISuspectTracking : IEntityTrait
{
}
