// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_tamemount?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Allows the Entity to be tamed by mounting it.
/// </summary>
[Trait("minecraft:tamemount", TraitSystem.TraitType.Entity)]
public interface ITamemount : IEntityTrait
{
    /// <summary>
    /// The amount the entity's temper will increase when mounted.
    /// </summary>
    [TraitProperty]
    public virtual int AttemptTemperMod => 5;

    [TraitProperty]
    public virtual dynamic? AutoRejectItems => null;

    /// <summary>
    /// The list of items that, if carried while interacting with the entity, will anger it.
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Autorejectitems => null;

    /// <summary>
    /// The list of items that can be used to increase the entity's temper and speed up the taming process.
    /// </summary>
    [TraitProperty]
    public virtual EntityFeedItem[]? FeedItems => null;

    /// <summary>
    /// The text that shows in the feeding interact button.
    /// </summary>
    [TraitProperty]
    public virtual string? FeedText => null;

    /// <summary>
    /// The maximum value for the entity's random starting temper.
    /// </summary>
    [TraitProperty]
    public virtual int MaxTemper => 100;

    /// <summary>
    /// The minimum value for the entity's random starting temper.
    /// </summary>
    [TraitProperty]
    public virtual int MinTemper => 0;

    /// <summary>
    /// The text that shows in the riding interact button.
    /// </summary>
    [TraitProperty]
    public virtual string? RideText => null;

    /// <summary>
    /// Event that triggers when the entity becomes tamed.
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? TameEvent => null;
}
