// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_target_nearby_sensor?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the entity's range within which it can see or sense other entities to target them.
/// </summary>
[Trait("minecraft:target_nearby_sensor", TraitSystem.TraitType.Entity)]
public interface ITargetNearbySensor : IEntityTrait
{
    /// <summary>
    /// Maximum distance in blocks that another entity will be considered in the 'inside' range
    /// </summary>
    [TraitProperty]
    public virtual float InsideRange => 1f;

    /// <summary>
    /// Whether the other entity needs to be visible to trigger 'inside' events
    /// </summary>
    [TraitProperty]
    public virtual bool MustSee => false;

    [TraitProperty]
    public virtual string? OnInsideRange => null;

    [TraitProperty]
    public virtual string? OnOutsideRange => null;

    /// <summary>
    /// Event to call when an entity exits visual range. Can specify 'event' for the name of the event and 'target' for the target of the event
    /// </summary>
    [TraitProperty]
    public virtual EntityEventTrigger? OnVisionLostInsideRange => null;

    /// <summary>
    /// Maximum distance in blocks that another entity will be considered in the 'outside' range
    /// </summary>
    [TraitProperty]
    public virtual float OutsideRange => 5f;
}
