// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_teleport?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using System.Numerics;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines an entity's teleporting behavior.
/// </summary>
[Trait("minecraft:teleport", TraitSystem.TraitType.Entity)]
public interface ITeleport : IEntityTrait
{
    /// <summary>
    /// Modifies the chance that the entity will teleport if the entity is in darkness
    /// </summary>
    [TraitProperty]
    public virtual float DarkTeleportChance => 0.01f;

    /// <summary>
    /// Modifies the chance that the entity will teleport if the entity is in daylight
    /// </summary>
    [TraitProperty]
    public virtual float LightTeleportChance => 0.01f;

    /// <summary>
    /// Maximum amount of time in seconds between random teleports
    /// </summary>
    [TraitProperty]
    public virtual float MaxRandomTeleportTime => 20f;

    /// <summary>
    /// Minimum amount of time in seconds between random teleports
    /// </summary>
    [TraitProperty]
    public virtual float MinRandomTeleportTime => 0f;

    /// <summary>
    /// Entity will teleport to a random position within the area defined by this cube
    /// </summary>
    [TraitProperty]
    public virtual Vector3 RandomTeleportCube => new Vector3([32, 16, 32]);

    /// <summary>
    /// If true, the entity will teleport randomly
    /// </summary>
    [TraitProperty]
    public virtual bool RandomTeleports => true;

    /// <summary>
    /// Maximum distance the entity will teleport when chasing a target
    /// </summary>
    [TraitProperty]
    public virtual float TargetDistance => 16f;

    /// <summary>
    /// The chance that the entity will teleport between 0.0 and 1.0. 1.0 means 100%
    /// </summary>
    [TraitProperty]
    public virtual float TargetTeleportChance => 1f;
}
