// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_tick_world?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines if the entity ticks the world and the radius around it to tick.
/// </summary>
[Trait("minecraft:tick_world", TraitSystem.TraitType.Entity)]
public interface ITickWorld : IEntityTrait
{
    /// <summary>
    /// The distance at which the closest player has to be before this entity despawns. This option will be ignored if never_despawn is true. Value must be &gt;= 128.
    /// </summary>
    [TraitProperty]
    public virtual float DistanceToPlayers => 128f;

    /// <summary>
    /// If true, this entity will not despawn even if players are far away. If false, distance_to_players will be used to determine when to despawn.
    /// </summary>
    [TraitProperty]
    public virtual bool NeverDespawn => true;

    /// <summary>
    /// The area around the entity to tick. Value must be &gt;= 2. Value must be &lt;= 6.
    /// </summary>
    [TraitProperty]
    public virtual int Radius => 2;
}
