// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_timer?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Adds a timer after which an event will fire.
/// </summary>
[Trait("minecraft:timer", TraitSystem.TraitType.Entity)]
public interface ITimer : IEntityTrait
{
    /// <summary>
    /// If true, the timer will restart every time after it fires.
    /// </summary>
    [TraitProperty]
    public virtual bool Looping => true;

    /// <summary>
    /// This is a list of objects, representing one value in seconds that can be picked before firing the event and an optional weight. Incompatible with time.
    /// </summary>
    [TraitProperty]
    public virtual string[] RandomTimeChoices => new[] { "[ ]" };

    /// <summary>
    /// If true, the amount of time on the timer will be random between the min and max values specified in time.
    /// </summary>
    [TraitProperty]
    public virtual bool Randominterval => true;

    /// <summary>
    /// Amount of time in seconds for the timer. Can be specified as a number or a pair of numbers (min and max). Incompatible with random_time_choices.
    /// </summary>
    [TraitProperty]
    public virtual Either<float, FloatRange>? Time => null;

    [TraitProperty]
    public virtual string? TimeDownEvent => null;
}
