// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_trail?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using System.Numerics;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Causes an entity to leave a trail of blocks as it moves about the world.
/// </summary>
[Trait("minecraft:trail", TraitSystem.TraitType.Entity)]
public interface ITrail : IEntityTrait
{
    /// <summary>
    /// The type of block you wish to be spawned by the entity as it move about the world. Solid blocks may not be spawned at an offset of (0,0,0).
    /// </summary>
    [TraitProperty]
    public virtual string BlockType => "air";

    /// <summary>
    /// One or more conditions that must be met in order to cause the chosen block type to spawn.
    /// </summary>
    [TraitProperty]
    public abstract EntityFilter SpawnFilter { get; }

    /// <summary>
    /// The distance from the entities current position to spawn the block.
    /// </summary>
    [TraitProperty]
    public virtual Vector3 SpawnOffset => new Vector3([0, 0, 0]);
}
