// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_transient?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// An entity with this component will NEVER persist, and forever disappear when unloaded.
/// </summary>
[Trait("minecraft:transient", TraitSystem.TraitType.Entity)]
public interface ITransient : IEntityTrait
{
}
