// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_transformation?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines an entity's transformation from the current definition into another.
/// </summary>
[Trait("minecraft:transformation", TraitSystem.TraitType.Entity)]
public interface ITransformation : IEntityTrait
{
    /// <summary>
    /// List of components to add to the entity after the transformation
    /// </summary>
    [TraitProperty]
    public virtual dynamic? Add => null;

    /// <summary>
    /// Sound to play when the transformation starts
    /// </summary>
    [TraitProperty]
    public virtual string? BeginTransformSound => null;

    [TraitProperty]
    public abstract float Delay { get; }

    /// <summary>
    /// Cause the entity to drop all equipment upon transformation
    /// </summary>
    [TraitProperty]
    public virtual bool DropEquipment => false;

    /// <summary>
    /// Cause the entity to drop all items in inventory upon transformation
    /// </summary>
    [TraitProperty]
    public virtual bool DropInventory => false;

    /// <summary>
    /// Entity Definition that this entity will transform into
    /// </summary>
    [TraitProperty]
    public virtual string? Into => null;

    /// <summary>
    /// If this entity has trades and has leveled up, it should maintain that level after transformation.
    /// </summary>
    [TraitProperty]
    public virtual bool KeepLevel => false;

    /// <summary>
    /// If this entity is owned by another entity, it should remain owned after transformation.
    /// </summary>
    [TraitProperty]
    public virtual bool KeepOwner => false;

    /// <summary>
    /// Cause the entity to keep equipment after going through transformation
    /// </summary>
    [TraitProperty]
    public virtual bool PreserveEquipment => false;

    /// <summary>
    /// Sound to play when the entity is done transforming
    /// </summary>
    [TraitProperty]
    public virtual string? TransformationSound => null;
}
