// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_trusting?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the rules for a mob to trust players.
/// </summary>
[Trait("minecraft:trusting", TraitSystem.TraitType.Entity)]
public interface ITrusting : IEntityTrait
{
    /// <summary>
    /// The chance of the entity trusting with each item use between 0.0 and 1.0, where 1.0 is 100%.
    /// </summary>
    [TraitProperty]
    public virtual float Probability => 1f;

    [TraitProperty]
    public virtual string? TrustEvent => null;

    /// <summary>
    /// The list of items that can be used to get the entity to trust players. Can be an array or a single item string.
    /// </summary>
    [TraitProperty]
    public virtual string[]? TrustItems => null;
}
