// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_underwater_mount_breathing?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Pauses this entity's breathing under water.
/// </summary>
[Trait("minecraft:underwater_mount_breathing", TraitSystem.TraitType.Entity)]
public interface IUnderwaterMountBreathing : IEntityTrait
{
}
