// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_underwater_movement?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Defines the speed with which an entity can move through water.
/// </summary>
[Trait("minecraft:underwater_movement", TraitSystem.TraitType.Entity)]
public interface IUnderwaterMovement : IEntityTrait
{
    /// <summary>
    /// Movement speed of the entity under water.
    /// </summary>
    [TraitProperty]
    public abstract float Value { get; }
}
