// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_variable_max_auto_step?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Entities with this component will have a maximum auto step height that is different depending on whether they are on a block that prevents jumping. Incompatible with "runtime_identifier": "minecraft:horse".
/// </summary>
[Trait("minecraft:variable_max_auto_step", TraitSystem.TraitType.Entity)]
public interface IVariableMaxAutoStep : IEntityTrait
{
    /// <summary>
    /// The maximum auto step height when on any other block.
    /// </summary>
    [TraitProperty]
    public virtual float BaseValue => 0.5625f;

    /// <summary>
    /// The maximum auto step height when on any other block and controlled by the player.
    /// </summary>
    [TraitProperty]
    public virtual float ControlledValue => 0.5625f;

    /// <summary>
    /// The maximum auto step height when on a block that prevents jumping.
    /// </summary>
    [TraitProperty]
    public virtual float JumpPreventedValue => 0.5625f;
}
