// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_variant?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Variant is typically used as a per-type way to express a different visual form of the same mob. For example, for cats, variant is a number that defines the breed of cat.
/// </summary>
[Trait("minecraft:variant", TraitSystem.TraitType.Entity)]
public interface IVariant : IEntityTrait
{
    /// <summary>
    /// The Id of the variant. By convention, 0 is the Id of the base entity/default appearance.
    /// </summary>
    [TraitProperty]
    public virtual int Value => 0;
}
