// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_vibration_damper?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Vibrations emitted by an entity with this component will be ignored.
/// </summary>
[Trait("minecraft:vibration_damper", TraitSystem.TraitType.Entity)]
public interface IVibrationDamper : IEntityTrait
{
}
