// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_walk_animation_speed?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets the speed multiplier for this entity's walk animation speed.
/// </summary>
[Trait("minecraft:walk_animation_speed", TraitSystem.TraitType.Entity)]
public interface IWalkAnimationSpeed : IEntityTrait
{
    /// <summary>
    /// The higher the number, the faster the animation for walking plays. A value of 1.0 means normal speed, while 2.0 means twice as fast.
    /// </summary>
    [TraitProperty]
    public virtual float Value => 1f;
}
