// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_wants_jockey?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Sets that this entity wants to become a jockey.
/// </summary>
[Trait("minecraft:wants_jockey", TraitSystem.TraitType.Entity)]
public interface IWantsJockey : IEntityTrait
{
}
