// autogenerated by ingot trait generator from
// https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_water_movement?view=minecraft-bedrock-stable

namespace ingot.Core.TraitSystem.Traits.Entity;
using ingot.Core.Common;
using ingot.Core.Behaviour.Entity;

/// <summary>
/// Customizes how the entity moves through water by adjusting drag coefficient. Lower values let entities glide through water easily like fish, while higher values create resistance for entities that struggle in water. Essential for aquatic mobs, boats, and any entity needing custom underwater physics.
/// </summary>
[Trait("minecraft:water_movement", TraitSystem.TraitType.Entity)]
public interface IWaterMovement : IEntityTrait
{
    /// <summary>
    /// Drag factor to determine movement speed when in water.
    /// </summary>
    [TraitProperty]
    public virtual float DragFactor => 0.8f;
}
