using System.Text;

namespace ingot.Core.Scripting;

/// <summary>
/// Wraps service handler bodies in a Script API tick loop.
/// </summary>
internal static class ScriptServiceGenerator
{
    /// <summary>
    /// Generates a service script that runs <paramref name="body"/> on the given tick interval.
    /// </summary>
    /// <param name="body">Service tick handler body.</param>
    /// <param name="intervalTicks">Ticks between each invocation.</param>
    public static string Generate(string body, int intervalTicks)
    {
        (IReadOnlyList<string> imports, string handlerBody) = ScriptImportHoist.Split(body);

        StringBuilder sb = new();
        sb.AppendLine("// autogenerated by ingot");
        sb.AppendLine();
        sb.AppendLine("import { system, world } from \"@minecraft/server\";");
        foreach (string import in imports)
            sb.AppendLine(import);
        sb.AppendLine();
        sb.AppendLine("system.runInterval(() => {");
        sb.AppendLine(handlerBody);
        sb.AppendLine($"}}, {intervalTicks});");
        return sb.ToString();
    }
}