using System.Text;

using ingot.Core.Common;

namespace ingot.Core.Scripting;

/// <summary>
/// Generates Script API custom component registration scripts.
/// </summary>
internal static class ScriptEventsGenerator
{
    /// <summary>
    /// Generates the JSON component name and JavaScript source for the given bindings.
    /// </summary>
    public static (string jsonComponentName, string code) Generate(Identifier id, IScriptEvents events)
    {
        StringBuilder sb = new();
        sb.AppendLine("// autogenerated by ingot");
        sb.AppendLine();
        sb.AppendLine("import { system } from \"@minecraft/server\";");
        sb.AppendLine();

        string suffix = events.ComponentKind == ScriptComponentKind.Block
            ? "block_events_component"
            : "item_events_component";

        string codeComponentName = Formatting.SnakeToPascalCase(string.Join('_', [
            id.Namespace,
            id.Name,
            suffix,
        ]));
        string jsonComponentName = $"{id.Namespace}:" + Formatting.PascalToSnakeCase(codeComponentName);

        sb.AppendLine($"const {codeComponentName} = {{");

        foreach (ScriptEventBinding binding in events.Bindings)
        {
            string body = binding.Handler.ResolveBody();
            sb.AppendLine(ComponentEvent(binding.ScriptApiEvent, body));
        }

        sb.AppendLine("};");
        sb.AppendLine();

        string registryName = events.ComponentKind == ScriptComponentKind.Block
            ? "blockComponentRegistry"
            : "itemComponentRegistry";

        sb.AppendLine("system.beforeEvents.startup.subscribe(({ " + registryName + " }) => {");
        sb.AppendLine($"    {registryName}.registerCustomComponent(");
        sb.AppendLine($"        \"{jsonComponentName}\",");
        sb.AppendLine($"        {codeComponentName}");
        sb.AppendLine("    );");
        sb.AppendLine("});");

        return (jsonComponentName, sb.ToString());
    }

    /// <summary>
    /// Builds the JSON component name for the given identifier and component kind.
    /// </summary>
    public static string GetJsonComponentName(Identifier id, ScriptComponentKind kind)
    {
        string suffix = kind == ScriptComponentKind.Block
            ? "block_events_component"
            : "item_events_component";

        string codeComponentName = Formatting.SnakeToPascalCase(string.Join('_', [
            id.Namespace,
            id.Name,
            suffix,
        ]));

        return $"{id.Namespace}:" + Formatting.PascalToSnakeCase(codeComponentName);
    }

    private static string ComponentEvent(string name, string content)
    {
        StringBuilder sb = new();
        sb.Append(name);
        sb.AppendLine("(event) {");
        sb.AppendLine(content);
        sb.AppendLine("},");
        return sb.ToString();
    }
}